### ISSUE TITLE
Combine similar New Relic CLI articles

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#1012]
### Summary

The following articles cover almost identical content:

- [Get started with the New Relic CLI](https://developer.newrelic.com/automate-workflows/get-started-new-relic-cli)
- [Quickly tag a set of resources](https://developer.newrelic.com/automate-workflows/5-mins-tag-resources)
- [Repo: Getting started](https://github.com/newrelic/newrelic-cli/blob/master/docs/GETTING_STARTED.md)

We should consider combining these into a single document and link to that document from other places. We'll need to consider what other sources—if any—are linking to these documents to avoid leaving bad links.

### What type of documentation change are you suggesting?

Edit existing documents

### Motivation

Combining like-articles into a single article would help clear up the organization on the docs site and help users find what they're looking for faster.

### Writing the documentation

If you are interested in helping us create this documentation please let us know. 
We encourage community contributions and can more quickly move your idea to publication if you suggest changes, or create an outline or rough draft. We'll collaborate with you to hone whatever content you provide.

**Comment by alexronquillo** [comment]
@zlesnr @ctrombley @sanderblue As authors of the original document in the repository, do you see advantages of keeping the Getting Started guide in the repo versus linking from the README to a guide on the dev site?

**Comment by zlesnr** [comment]
I don't @alexronquillo.  We can locate the content wherever makes sense and link out to it in my opinion.

**Comment by jpvajda** [comment]
@alexronquillo yes! more explicit instructions on using the new relic CLI would be great. Similar to how we structured our content for the NR1 CLI, may be a good approach to follow this pattern. https://developer.newrelic.com/explore-docs/nr1-cli

Also I was recently made the PM of the DevTool Kit team so feel free to hit me up with these types of questions as well. Hapy to help.

**Comment by jpvajda** [comment]
@alexronquillo this went stale but I thought could add it to your list of content improvements. 😄
