### ISSUE TITLE
Add a build validation workflow for PRs into `main`

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1058]
## Description
Since Amplify does not reliably communicate the success status of PRs, we added a GitHub workflow to build the docs site when a new PR is created. This is a feature we would like to have for the developer site repository as well.

## Helpful Links
* https://github.com/newrelic/docs-website/issues/485
* https://github.com/newrelic/docs-website/issues/518
* https://github.com/newrelic/docs-website/pull/546
* https://github.com/aws-amplify/amplify-console/issues/550

**Comment by jerelmiller** [comment]
This is done
