### ISSUE TITLE
Reduce toil required to update component docs version

### ISSUE THREAD

**Issue by timglaser** [newrelic/developer-website#1077]
Relates to `JIRA` `NR1UI-2734`

Currently, updating the version of the UI component docs requires the following toil:

1. **Find out if the docs are out of date**: There is currently not a process setup to trigger response to the 3rd party components being updated. This leaves the documentation getting out of date too easily.

2. **Determine which components to include from 1st party bundle**: We do not yet have access to a 3rd party UI components bundle that includes the documentation and live preview code. Rather we are relying on the 1st party bundle, requiring us to determine which components are ok to show in the developer site. 

3. **Manually create an mdx file per component**: There are changes already in progress to address this step but time will need to be invested to carry the intentions forwaara

4. Add side nav entries for each added component

5. Add any newly necessary mocks to allow the 1st party sdk bundle to execute during build time of the developer site. This is a step added towards no longer needing to create the mdx files. Presumably this will only be needed once in a while, not every time. If a new mock is needed it will fail the build.

6. Determine if the live preview for any of the new components are not functioning well in the developer site. If not, add them to the exclusion list until ready.

### Describe the solution you'd like

The dream: When 3rd party SDK updates are made available for customers to use them on production, the component docs on the developer site are also updated on the same day.

Here are the things that seem necessary for the toil to be reduced enough for that to become a reality:
* Generate a 3rd party sdk docs bundle (includes docs, live previews and the component category where the component category would be used in site navigation). Alternatively, if generating the 3rd party sdk docs bundle is still not feasible, the 1st party docs bundle could include metadata about which components, props, methods, etc are also available for 3rd party.
* Provide a clean and reliable/stable way to programmatically find out what the current version of the 3rd party sdk is on in production, either by polling or via a signal that triggers a notification to the developer site team or the developer site automation.
* Minimize and eventually eliminate code changes necessary in the developer site in order to point to a new version of the 3rd party sdk. No more creating mdx files (a plan is underway on that already). No more updating side nav (generate it based on metadata provided in the sdk bundle).

The above could of course get worked towards in phases, approaching closer and closer to full automation.

### Describe why this important to you

The public docs should be kept up to date as the 3rd party components get updated. At times the components are getting updated at least weekly in which case the docs should get updated at least weekly. Stepping through the above toil weekly would be unfortunate.

**Comment by jerelmiller** [comment]
+1

**Comment by jpvajda** [comment]
@jerelmiller you mentioned you resolved some of this toil, could you provide what you've done so we can keep track of what's left. 😄

**Comment by jpvajda** [comment]
@jerelmiller can you document how this works now that you've done some of this work in the contributing guide?

**Comment by jerelmiller** [comment]
Certainly! We just released an update to the developer site that now sources the documentation into GraphQL and uses that to power the SDK docs pages (#1078). With that change, we now auto generate a page for each component/API which removes the need for creating `.mdx` files for each of them. 

I've also just opened a PR that will talk about how to upgrade the SDK (#1082) in the contributing guide. I'm not sure we'll fully be able to get rid of the step to add the component to the sidenav, mostly due to the fact that we "categorize" each of those components into a specific nav subsection, but the number steps now needed to upgrade the SDK should be much more reasonable.

Now all we need is a 3rd party docs bundle and that would make things super nice for us 😄

**Comment by jpvajda** [comment]
@jerelmiller we haven't demo'd the dev site lately, could we briefly touch on what we did here in next week's demo?

**Comment by jerelmiller** [comment]
Sure thing!

**Comment by jpvajda** [comment]
This came up again.. 🙌

**Comment by jpvajda** [comment]
I've linked the internal JIRA ticket and will try to get a status on this from the Core team.
