### ISSUE TITLE
Cannot read property 'id' of undefined error in hello world application

### ISSUE THREAD

**Issue by chilupa** [newrelic/developer-website#1087]
## Description
Trying to build [hello world application](https://developer.newrelic.com/build-apps/build-hello-world-app) following Docs. I'm running into the issue where I see this error when I change the app name in `nr1.json` file

[NOTE]: # (Describe the problem you're encountering.)
[TIP]: # (Do NOT give us access or passwords to your New Relic account or API keys!)

## Steps to Reproduce
- Follow the steps in this [page](https://developer.newrelic.com/build-apps/build-hello-world-app) for creating hello world application.
- Run the app using `nr1 nerdpack:serve --verbose`
- Modify the `displayName` in `nr1.json` file in `launchers` folder and save it.
- It shows your the error in console

[NOTE]: # (Please be as specific as possible.)

## Expected Behavior
Should run the application without any error as I haven't changed the `Id` in any of the config files.

[NOTE]: # (Tell us what you expected to happen.)

## Relevant Logs / Console output

```bash
TypeError: Cannot read property 'id' of undefined
at Artifact.get id [as id] (/usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack-common/models/Artifact.js:75:33)
at artifacts.find (/usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack/src/build/BuildManager.js:216:67)
at Array.find (<anonymous>)
at FSWatcher.watcher.on (/usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack/src/build/BuildManager.js:215:51)
✖  Error: Something went wrong while parsing /apps/nr-app/nerdlets/nr-app-nerdlet/nr1.json
```

[NOTE]: # (Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible.)

## Your Environment
```bash
NR: @datanerd/nr1/1.28.9 darwin-x64 node-v10.16.3
Node: v12.20.1
Browser: Google Chrome
OS: macOS Big Sur
```

[TIP]: # (Include as many relevant details about your environment as possible.)
[TIP]: # (ex: Browser name and version)
[TIP]: # (ex: Operating System and version)

## Additional context

[TIP]: # (Add any other context about the problem here.)

**Comment by jerelmiller** [comment]
Hey @chilupa! Thanks for opening an issue! Let me see if I can get some help determining whether this is an issue with the guide itself, or whether there is a bug in the platform.

@mjesun do you mind doing a quick skim of that "Hello world" guide and see if maybe something needs to be updated, or if you know of a change to the platform behavior?
