### ISSUE TITLE
Add the ability to embed page content

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1116]
## Description
We would like to add the ability to embed content from the developer site into other pages (i.e. learn.newrelic.com). This could be done in a few different ways:
- Expose the page via a JSON "endpoint"
- Build a stripped-down version of the page (without nav, header, footer, etc) for loading in an iframe

_Note: this would be advantageous to complete (and document) by the end of February._

**Comment by jpvajda** [comment]
closing as it's a dup of #1134
