### ISSUE TITLE
Table SDK component documentation shows an error

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1163]
## Description
```
Invariant Violation: Unable to find node on an unmounted component.
```

### Doc information (don't delete this section)
* https://developer.newrelic.com/components/table
* **OS**: Mac OS 11.2.2
* **Browser**: Chrome 88.0.4324.192
* **Device**: Unknown

<img width="1666" alt="Screen Shot 2021-03-11 at 7 48 52 AM" src="https://user-images.githubusercontent.com/1395158/110805384-43158880-823e-11eb-8319-74e900378609.png">

### Acceptance Criteria

- [ ] This has been fixed by One Core, so we need to pull in a new version of the SDK bundle to fix this problem.
- [ ] Document where you can obtain the release verison in our bundle [update docs section](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#updating-the-documentation-bundle)

**Comment by jpvajda** [comment]
I wonder if this has always been there since our last SDK update? Perhaps it's something the Nr1 Core Team can help us with.

**Comment by jpvajda** [comment]
I'll see if the NR1 Core Hero can give us some direction here.

**Comment by jpvajda** [comment]
Still waiting on a response... 😓

**Comment by jpvajda** [comment]
I believe our dev site should render these example tables, as it's rendered on NR1 core site. That seems to be what the error is indicating.

![Screen Shot 2021-03-15 at 5 58 41 PM](https://user-images.githubusercontent.com/1395158/111236418-6df23a80-85b8-11eb-9d8f-7154894c242f.png)

![Screen Shot 2021-03-15 at 5 58 47 PM](https://user-images.githubusercontent.com/1395158/111236421-6f236780-85b8-11eb-9394-14689948c84a.png)

**Comment by jpvajda** [comment]
Interesting this does render locally... 🤔  

![Screen Shot 2021-03-15 at 6 07 26 PM](https://user-images.githubusercontent.com/1395158/111236860-739c5000-85b9-11eb-8f15-dcaa1b45f3e7.png)

**Comment by LizBaker** [comment]
this is broken locally for me. it looks to be a react versioning issue, if I roll the react version we're using back to 16.8 the tables load just fine. the dev site upgraded to react 17 12 days ago so I'm thinking that's when we ran into this issue. I would think it was a version mismatch/issue with react-live which we're using to render these previews, but that appears to function normally for everything but tables, continuing to poke around

**Comment by jpvajda** [comment]
@LizBaker interesting, how did the Developer Site get bumped to Reach 17?

**Comment by LizBaker** [comment]
seems like it's part of the work to upgrade gatsby from v2 to v3, happened here https://github.com/newrelic/developer-website/pull/1160

**Comment by jpvajda** [comment]
Cool. It's nice that we are exploring the upgrade to Gastby V3 and I think it was something @jerelmiller did before he left the team.  v3 is going to provide a lot of cool features for our sites. However if we find it's creating a lot of extra effort we may want to hold off on any V3 exploratory work and actually bucket some time for that in upcoming sprint. @zstix let me know what you think. 

`ps` We also have a entire roadmap initiative planned for the v3 upgrade targeting in June right now.

**Comment by jerelmiller** [comment]
Its also possible the React upgrade fails because we are loading 2 versions of React as per this file: https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/gatsby-ssr.js#L17-L26

We could try updating that to match the React version from `package.json` and see if that resolves the issue.

**Comment by jerelmiller** [comment]
Apologies, I clicked around the site a bunch when checking the React 17 upgrade and thought everything looked good, but didn't catch this particular case.

**Comment by LizBaker** [comment]
@jerelmiller gave that version bump a try but no dice, maybe they haven't updated it?

**Comment by jpvajda** [comment]
Moving back to `todo` as we have some higher priority items to work on at the moment.

**Comment by LizBaker** [comment]
got a chance to pair with Jerel and we nearly fixed it, but we encountered a bug with the newer versions of the sdk (which we need to use). that bug is being tracked in jira (`ONECORE-382`) and once it's resolved we can update with our fix

**Comment by jpvajda** [comment]
It sounds like from our discussions with the One Core Team this fix may be a ways out, so we have 3 options:

1. We can either keep the developer site as-is and remove the Table examples
2. or update the bundle and remove the Chart examples.
3. Or leave it as is, and present the error to the end user.

**Comment by jpvajda** [comment]
The core team said this `should` be resolve next week, so I'll leave it blocked until the internal JIRA issue is resolved.
