### ISSUE TITLE
Guide CTA order should be the same as the navigation order

### ISSUE THREAD

**Issue by kaizer113** [newrelic/developer-website#1169]
### ISSUE 

the guide CTA boxes should be ordered similarly to the left menu on the [Build Apps page](https://developer.newrelic.com/build-apps)  and [Automate workflows](https://developer.newrelic.com/automate-workflows) and [Collect Data](https://developer.newrelic.com/collect-data)

### Acceptance Criteria

- [ ] the guide CTAs should mimic the navigation of the site for the pages where CTAs are used. 
- [ ] This should be an automate process so when a user changes the navigation in [nav.yml](https://github.com/newrelic/developer-website/blob/develop/src/data/nav.yml) these CTA components are automatically sorted in the same order.

**Comment by jpvajda** [comment]
@kaizer113 Hi there 👋 when you say "widgets" are you referring to what is under the Guides to build apps section of this page?

**Comment by kaizer113** [comment]
yes the guides are not ordered

**Comment by jpvajda** [comment]
closing as we are soon moving our guide content over to docs.newrelic.com so this is a wont' fix.
