### ISSUE TITLE
Syntax not specified for nr1.json configuration options(namespace, collection inside collection)

### ISSUE THREAD

**Issue by utsavtulsyan** [newrelic/developer-website#1181]
### Tell us what you need

*Document does not specify how to use "namespace", any syntax would be very helpful.
*I am unable to use collection inside a collection, is that not supported or requires a different syntax?

### Anything else you'd like to share?

Please refer to Step 3 of (https://developer.newrelic.com/build-apps/build-visualization#create-a-new-visualization)

### Doc information (don't delete this section)

* https://developer.newrelic.com/build-apps/build-visualization
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 89.0.4389.82
* **Device**: Unknown

**Comment by jpvajda** [comment]
@alexronquillo does this improvement interest you? 😄

**Comment by alexronquillo** [comment]
Very much so! In addition, I'm focusing on writing centralized docs for custom visualization and nerdlet stuff. Right now, so much of the informational docs are scattered throughout tutorials; there isn't a source-of-truth place to look like there is for the SDK components, for example. I think that source-of-truth documentation is a better place for this content than in the tutorial. The tutorial can just link out to the docs for users who want to learn more.

**Comment by utsavtulsyan** [comment]
This has been Implemented, so closing the issue.
