### ISSUE TITLE
Wrong link and text at the bottom of the Intro to New Relic One SDK page

### ISSUE THREAD

**Issue by mcaronnewrelic** [newrelic/developer-website#1213]
The last line on the page https://developer.newrelic.com/explore-docs/intro-to-sdk

"nerdlet: an object that provides write access to the Nerdlet URL state."

I believe that the description is wrong. That's not a nerdlet or what it does, looks like a copy paste error from the line above it for NerdletStateContext.

Also, the link directs the user to the 'navigation' component (https://developer.newrelic.com/apis/navigation).

**Comment by jpvajda** [comment]
@alexronquillo would you mind looking at this one?

**Comment by alexronquillo** [comment]
@mcaronnewrelic That is part of its function:

```js
nerdlet.setUrlState({
  foo: 'bar',
});
```

I would add that it allows you to configure your Nerdlet.

How does this sound?

> nerdlet: allows you to configure your Nerdlet and  write to your Nerdlet's URL state.

**Comment by jpvajda** [comment]
The definition of `nerdlet` API  is taken directly from the One Core documentation which defines the SDK and use. As for the link on `nerdlet` we can change that to link `https://developer.newrelic.com/apis/nerdlet`

<img width="672" alt="Screen Shot 2021-05-02 at 10 02 11 AM" src="https://user-images.githubusercontent.com/1395158/116819565-cd3ae880-ab2d-11eb-9e3c-821bec331360.png">

**Comment by jpvajda** [comment]
@alexronquillo I submitted a PR for this fix, #1294 can I get your 👍 ?
