### ISSUE TITLE
[GH Workflows]: Improve workflow runs for deploys

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1221]
## Description
Twice this week I encountered this issue when deploying. The one required check on `main` branch is the `checkout-and-build` job in `release.yml`. 

When I created a PR from `develop` to `main`, it ran all its checks successfully, but the last job to run (as part of `release.yml`) adds a `chore(release)` commit to the `develop` branch (for semantic release and what not). As soon as that commit is pushed to `develop`, the `checkout-and-build` job check goes back to expected, but the job is never triggered (presumably because the workflow that committed is still running / won't run twice?). Since that job check is required, the PR / deploy get stuck until `develop` gets another trivial push to trigger the `release.yml` workflow again (which doesn't push another `chore(release)` commit and leaves the `checkout-and-build` job status as successful.

I also noticed we run 3 separate gatsby build jobs when merging to `main`.

## Acceptance Criteria

~Change required job check on merges to `main` to the `validate-pr.yml` workflow.~
~Reduce build jobs triggered on merges to `main`~
* [x] Remove `checkout-and-build` workflow
* [x] Update branch protection to block for the Gatsby Cloud build
* [x] Update any documentation to reflect this change

## Related PRs
https://github.com/newrelic/developer-website/pull/1218

**Comment by jpvajda** [comment]
@aswanson-nr isn't this the problem you faced on the Dev Site?

**Comment by rudouglas** [comment]
#1353 should close this out

Documentation:

- [ ] Altered [this Doc](https://docs.google.com/document/d/1O1SGS0i3OmPfvPhylpFe1CTMkE20889iAOF_cMFJ344/edit#)
- [ ] Changed the Branch Protection Architecture Diagram
