### ISSUE TITLE
Add `NODE_EXTRA_CA_CERTS` docs

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#1235]
### Summary

We need to write content to help debug a situation where the user is interacting with `nr1` behind a proxy.

The solution:

> Add their own corporate certificate by NODE_EXTRA_CA_CERTS's environment variable.

### What type of documentation change are you suggesting?

Update to existing docs

### Motivation

This will help users debug a specific proxy-related issue.

### Writing the documentation

If you are interested in helping us create this documentation please let us know. 
We encourage community contributions and can more quickly move your idea to publication if you suggest changes, or create an outline or rough draft. We'll collaborate with you to hone whatever content you provide.

**Comment by jpvajda** [comment]
There is some documentation on proxy setups here: not sure if this is relevant to this case: https://developer.newrelic.com/build-apps/build-hello-world-app#proxy-browser-setup
