### ISSUE TITLE
callouts can be set to hidden and not shown when used in /embed URLs

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#1237]
For multi-guide series (courses), we're considering using course-specific meta callouts that tell the user that the guide they're reading is part of a series, as well as surfacing the previous and next guides in the series. This works really well for users who are reading the guides on the dev site, but it doesn't work well if the guide is embedded into another context (say, an NRU course). 

`problem` The callouts are confusing because the other context doesn't necessarily reference the other guides in the same way.

### Solution

We're getting a lot of feedback in the context we're embedding content in about how the course callouts are confusing. But if we remove the course meta callouts from the dev site, that will make the dev site context more confusing.

I'd like to be able to optionally hide all callouts of a particular variant when a page is embedded (`/embed`). This way, the author can control when to hide callouts depending on context.

### Acceptance Criteria

- [x] in the [theme](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/Callout.js) callouts can be set to hidden via a prop
- [x] a user who wants to hide callouts on /embed pages can simply set this in the component code such as:

```
<Callout variant="tip" title="Course" hidden="true">

```

### Additional context

[Here's](https://developer.newrelic.com/build-apps/ab-test/create-nerdpack) an example site guide that's a part of a larger course. It uses these course callouts:

<img width="800" alt="Screen Shot 2021-04-09 at 11 37 02 AM" src="https://user-images.githubusercontent.com/8672090/114205090-ef26be00-9927-11eb-98c2-79b1c7525185.png">

<img width="800" alt="Screen Shot 2021-04-09 at 11 37 11 AM" src="https://user-images.githubusercontent.com/8672090/114205806-b2a79200-9928-11eb-9ca8-450b6509af17.png">

### Related issue

https://github.com/newrelic/developer-website/issues/1239

**Comment by zstix** [comment]
@alexronquillo Would it be acceptable to hide all the Callouts / tips when viewing a guide in the embedded format?

**Comment by jpvajda** [comment]
IDK, I think some tips would be useful in the /embed view, but I defer to @alexronquillo  🤔

**Comment by alexronquillo** [comment]
@zstix No, I don't think so. Most callouts are useful, particularly "important" callouts, so I don't think we'd want to hide them all.
