### ISSUE TITLE
Create a new variant for course tips

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1239]
For content that is embed as course Content on NRU, such as this page: https://developer.newrelic.com/ab-test we want to use a different call variant that doesn't look just like the tip variant.

### Acceptance Criteria 

- [x] Make a new variant for course tips with a different color.
- [x] name of variant = `course`
- [x] Color of variant = blue

**Comment by jpvajda** [comment]
I think this is as simple as added a new const variant to [this file](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/Callout.js)

**Comment by LizBaker** [comment]
Added a new variant to the theme and am waiting on a jp translation of `course` just in case we ever use that variant on the docs site

**Comment by jpvajda** [comment]
PR: https://github.com/newrelic/gatsby-theme-newrelic/pull/344
