### ISSUE TITLE
OverviewTemplate.js should support embedding functionality

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1240]
Relates to #1227 and PR #1201 

### Enhancement 

We'd like to be able embed index pages such as

- https://developer.newrelic.com/build-apps
- https://developer.newrelic.com/ab-test

currently when you apply `/embed/` to these  pages you receive a 404 page

### Acceptance Criteria

- The OverviewTemplate.js should support embedding functionality
- All Overview index pages can now have /embed to their path and the content will be embedable.

**Comment by jpvajda** [comment]
This may be as easy as just adding OverviewTemplate to this [query](https://github.com/newrelic/developer-website/blob/37b3b39200566f03d44ded1d7b275f376ac5222a/plugins/gatsby-plugin-embed-pages/gatsby-node.js#L8)

**Comment by zstix** [comment]
@jpvajda / @alexronquillo Out of curiosity, _why_ would we want to embed these pages? It looks like their purpose is to aid users in navigating around the developer site. I'm not sure I see the value of embedding these.

**Comment by zstix** [comment]
Ah I see, we're using the `overviewTemplate` for the A/B test page. For the most part, we use that as a landing page template - it looks like we're using it here as a work-around to get a single page layout.

**Comment by jpvajda** [comment]
@zstix bingo.. perhaps we need a new template then and not take this approach?

**Comment by jpvajda** [comment]
@zstix I wonder if the correct way to approach this is build a single page template, vs trying to support /embed on the overviewTemplate, though a quick work around could  be to enable that on the overviewTemplate, it seems really straight forward.

**Comment by jpvajda** [comment]
The solution is to convert this page to a guide template instead of using an overview template, since this page is functioning as guide and less so an overview I'll check in with @alexronquillo if this will work instead of trying to add embed to the overview template.

**Comment by alexronquillo** [comment]
This is fine. Thanks. Honestly, I probably copied the OverviewTemplate from another index page. I'm still learning what templates are even used for. We're actually not embedding this page anyway, I just noticed that it couldn't be embedded even if we wanted to, which seemed like a bug.
