### ISSUE TITLE
Related Resources is only displaying 4 URLS on Dev Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1241]
### Bug

Related Resources is only displaying 4 URLS on Dev Site

<img width="362" alt="Screen Shot 2021-04-09 at 12 10 15 PM" src="https://user-images.githubusercontent.com/1395158/114224604-855de280-992e-11eb-904d-fca66063fa11.png">

### Steps to Reproduce

1. go to a [page like](https://developer.newrelic.com/automate-workflows/kubernetes-helm-deployment) this.
2. look at resources in the right rail, see only 4 links,
3. view the [front matter of the page](https://github.com/newrelic/developer-website/edit/develop/src/markdown-pages/automate-workflows/get-started-kubernetes.mdx)
4. Notice that 4 URLS are set to be static resources.
5. This means 1 resources should be populating in the right rail. 
6. Notice that the label of a resource does appear but the link doesn't 🤔 

### Expected

[related resources documentation](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#relatedresources)

1. up to 5 resources should appear in the right rail. 
2. If static URLS are set in the front matter, they'd take priority. 
3. Then we should be backfiling the remaining URLs with [those populated by swiftype](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#related-pages)

**Comment by jpvajda** [comment]
It looks like this may be only occurring on links to the developer site that are related resources.

**Comment by aswanson-nr** [comment]
Here's another great example https://developer.newrelic.com/build-apps/add-nerdgraphquery-guide
The tags show up for all 5 links, but the links themselves are missing.

**Comment by nr-kkenney** [comment]
been doing some very simple local testing & verification.

for develop & main, with and without a production build, i see the following when running locally for the two pages mentioned above:

![Screen Shot 2021-04-09 at 4 09 37 PM](https://user-images.githubusercontent.com/70179215/114249957-fa421400-9950-11eb-91a0-d84ed71540e0.png)
![Screen Shot 2021-04-09 at 4 09 28 PM](https://user-images.githubusercontent.com/70179215/114249962-fc0bd780-9950-11eb-95e0-f4b36557bbb0.png)

**Comment by jpvajda** [comment]
@nr-kkenney to confirm locally this is working for you?

**Comment by nr-kkenney** [comment]
my intent was not to say thats its working, just providing what i saw when running locally.

**Comment by LizBaker** [comment]
i just ran it locally on develop both with gatsby develop and gatsby serve, no issues. ran it on main (after a cache clean) and reproduced the issue locally, so i'm starting to dig in

**Comment by jerelmiller** [comment]
FYI, local and prod might have slightly different data depending on whether `main` has been merged into `develop`. Running locally, you're subject to whatever is in `related-pages.json`. The nightly job that refetches all the of data [commits directly to `main`](https://github.com/newrelic/developer-website/blob/develop/.github/workflows/fetch-related-content.yml#L18-L19). 

Just wanted you to be aware of this in case you're wondering why the data is different 😄

**Comment by LizBaker** [comment]
swiftype results are coming back with an empty `title` whenever the page is from a `/embed` url. the embed layout doesn't include seo and has no title set. we don't want these pages indexed in the first place so i'm going to adjust the indexing rules by adding `/embed` to the block list (where we also exclude urls that include `/404`)

**Comment by LizBaker** [comment]
a little trial and error but the `/embed` pages are now excluded from being indexed and there are no longer title-less related resources for developer 🎊
