### ISSUE TITLE
Feedback: Publish your New Relic One application

### ISSUE THREAD

**Issue by shahramk** [newrelic/developer-website#1243]
### Tell us more about your feedback

We're glad to hear this doc was helpful! We've recorded your feedback. Help us 
improve other content by telling us what worked and what didn't:

* What worked well in this doc? steps were mostly smooth with enough details to carry on.
* How could we make this doc even better? I had to make several attempts to get the size of the screenshot right. it'd help if there is some instructions or mention of a tool to easily resize the screenshot.

### Doc information (don't delete this section)

* https://developer.newrelic.com/build-apps/ab-test/publish
* **OS**: OSX Big Sur
* **Browser**: Brave
* **Device**: Mac

**Comment by alexronquillo** [comment]
Thanks @shahramk — I updated the guide to include a link to a 1600 width image by default, so that the user shouldn't need to resize the screenshot at all.
