### ISSUE TITLE
Related resources is getting results from the blog

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#1264]
### Description

For related resources we currently filter out swiftype results that come from the new relic blog and forum. The blog is going through a migration and it appears it no longer has a type of `blog` for swiftype to include, so we're getting results for it despite our attempt to filter. We should probably filter to include developer/opensource/docs instead of filter to exclude blog/forum. 
These filters can be changed in the gatsby-config, and should be changed on all sites

### Steps to reproduce

Check out https://developer.newrelic.com/build-apps/add-nerdgraphquery-guide and notice the newrelic.com labeled links which are for newrelic.com/blog

### Expected behavior

- [x] We should let the marketing site team know this type is missing in #help-website.
- [ ] Given we add meta tags on all our pages for swiftype that include a “type” and rely on that for filtering results we need a way to filter these out by `type:blog` 
- [ ] We can also take the approach to `include` content vs `exclude` so we don't have to be dependent on the type value on the blog.
- [ ] Once corrected - No newrelic.com/blog results in related resources

**Comment by jpvajda** [comment]
The action here is for me to follow up with the marketing team, probably David Hwang to make them aware of this issue and see if they can help us out

**Comment by jpvajda** [comment]
Internal Ticket for this change: https://newrelic.atlassian.net/browse/WT-4734

**Comment by LizBaker** [comment]
just for clarity: we can also change this on our end right now, it's just that the blog should add that type for the best use of swiftype and for our search results. right now in the related resources config for the developer site we filter page types via exclusion `type: ['!blog', '!forum'],` but we could change it to inclusion `['docs', 'developer', 'opensource']` which would ignore results with no type, like the current blog results

**Comment by jpvajda** [comment]
Waiting on the marketing team to make this change.
