### ISSUE TITLE
Migrate Dev Site to Gatsby Cloud

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1270]
Once we've decided to move our Docs  Site to Gatsby Cloud we'll want to move this site to Cloud.

### Acceptance Criteria 

- [ ] ~~move the DNS entry over to Gatsby Cloud~~ (Handled in this ticket https://github.com/newrelic/developer-website/issues/1338)
- [x] setup webhook on repo 
- [x] Test build & deploy workflow 
- [x] Update architecture documentation
- [x] Update troubleshooting guide(s)
- [ ] ~~Disconnect Amplify from the repository~~ (Handled in this ticket https://github.com/newrelic/developer-website/issues/1338)

**Comment by aswanson-nr** [comment]
Waiting to merge https://github.com/newrelic/developer-website/pull/1346, until https://github.com/newrelic/developer-website/issues/1338 closes.
Closing this issue.
