### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ithinker143** [newrelic/developer-website#1284]
### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://developer.newrelic.com/podcasts
* **OS**: iOS 14.4
* **Browser**: Mobile Safari 14.0.3
* **Device**: [mobile] Apple iPhone

**Comment by jpvajda** [comment]
This doesn't report an actually issue, so closing.
