### ISSUE TITLE
Use the `<Intro>` component consistently on the Dev Site 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1288]
Through the site we are using the [<intro>](https://github.com/newrelic/developer-website/blob/29a067249fd29a8fff799ded968f464542e9d4be/src/components/Intro.js#L6) component slightly different, let's ensure we use this consistently where needed.

### Example issues

    Whole Intro - https://developer.newrelic.com/build-apps/map-pageviews-by-region
    Part Intro - https://developer.newrelic.com/collect-data/custom-attributes
    None - https://developer.newrelic.com/automate-workflows/diagnose-problems

### Acceptance Criteria'

- [ ] Before doing this work, align on the use <intro> on the dev site.
- [ ] do a check of all guides and where an <intro> is needed use it consistently.

**Comment by alexronquillo** [comment]
In some of these cases, the differences are intentional. I'd like to think about this a little bit more and have a larger discussion about the styling of introductory sections before committing to this work.

**Comment by jpvajda** [comment]
@alexronquillo  Totally agree! 👍

**Comment by rudouglas** [comment]
@alexronquillo great that sounds like a plan

**Comment by jpvajda** [comment]
closing as won't do for now as we look to migrate content to dev site to docs site, this can be considered as the guides are moved.
