### ISSUE TITLE
Only 15 pages indexed in Swiftype

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1296]
## Description

Only 15 pages on the developer site are indexed in Swiftype. I believe there should be... 100+ pages indexed? 

## Screenshots
<img width="605" alt="Screen Shot 2021-05-03 at 16 04 01" src="https://user-images.githubusercontent.com/2952843/116944053-95b16680-ac29-11eb-8960-82e2c3eeb572.png">

**Comment by roadlittledawn** [comment]
not sure if this is related to https://github.com/newrelic/docs-website/issues/2103 but maybe, since swiftype does use sitemaps and right now wouldn't know where to find it because it's not set correctly now in swiftype UI and the URI in the sitemap `<link>` in the `<head>` is wrong

**Comment by jpvajda** [comment]
🤔 oh yeah.. @roadlittledawn great point....

**Comment by roadlittledawn** [comment]
also, last time i looked at opensource doing something similar, i noticed the sitemap URLs did not have trailing slashes and when you request a page without a trailing slash, the network call looks like it 302s, which swiftype considers no good and discards the record i believe. though i'm surprised it doesn't index the new page with the trailing slash. need to look closer to verify that

**Comment by roadlittledawn** [comment]
at quick glance, the pages that are indexed in swiftype have a trailing slash in swiftype AND the sitemap. example: https://developer.newrelic.com/emea-nerd-days/
