### ISSUE TITLE
Table_Minich

### ISSUE THREAD

**Issue by hm-sminich** [newrelic/developer-website#1298]
### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://developer.newrelic.com/build-apps/map-pageviews-by-region
* **OS**: Windows 10
* **Browser**: Firefox 88.0
* **Device**: Unknown

**Comment by jpvajda** [comment]
There is no issue reported here so closing.
