### ISSUE TITLE
Images and code snippets are stretched out of <Step> blocks

### ISSUE THREAD

**Issue by theletterf** [newrelic/developer-website#131]
### Description
I’ve a couple tips / blocks after closing <Steps>. They show with full width, and with overstretched code blocks. Screenshots outside of Intro or Step sections are full width.

You can see how it looks like here: https://github.com/newrelic/developer-website/blob/ea6d0eda0d8a62f37a8fe5a12e4acf6250ad3abf/src/markdown-pages/get-started-nerdgraph-api-explorer.mdx

### Steps to reproduce
1. Create an .mdx guide.
2. Add an image and a code block outside of a <Step> block.
3. See the stretched layout.

### Expected behavior
I would expect a max. width (proportional) to be in place. 

### Screenshots
![Image](https://lh5.googleusercontent.com/kAvzUE5I5hrZIO8GwVgGbmH8KNBbJYDqy-lMNsv6NeMJnWKY8SjdknvN9W9C4u9uaSXF33ml8xJATxBwjfCDoyNX9eYwGmvjO4N2VZfAbWyzRCfSvvTcgFfWxq-Gwfmpq3gnLKVa)

![Code block](https://lh6.googleusercontent.com/BCO5vqkN9ijKZgX4B_-6NznDOx9mRh9C8eJkoCHB_IDBHt8ATdNqtGgMDDNOtFpJpJfIXuetOjXOHX-UxC-BXbXlV8lYESyDyFtuJBwM-nE2JS1JXZxqxmotvVJQwNdOy-feWTmV)

**Comment by jerelmiller** [comment]
This issue is fixed
