### ISSUE TITLE
Capitalization error PlatformState  should be platformState in  code samples

### ISSUE THREAD

**Issue by wrekone** [newrelic/developer-website#1324]
### Tell us what you need

Step 3 of 5:
In the example code

`{(platformState) => { `

should be  

`{(PlatformState) => {`

**Comment by alexronquillo** [comment]
Hi @wrekone I'm not sure which guide you're referring to for this suggestion. However, in the examples I looked at, `platformState` was correct as is. Does this produce an error for you? If so, could you pinpoint which document has the error? Thanks!

**Comment by jpvajda** [comment]
closing as we never heard back on where this was found

**Comment by jpvajda** [comment]
Actually I did a quick search in the code and found these locations where this is occuring.

https://github.com/newrelic/developer-website/blob/7c421d0b5a85d6ab7b1acbe1d3761d6cb578e26b/src/markdown-pages/build-apps/add-time-picker-guide.mdx

https://github.com/newrelic/developer-website/blob/096d48649a06130b683061e3ccebbfa2d27e6ad4/src/markdown-pages/build-apps/create-an-ab-test-application/navigation.mdx

https://github.com/newrelic/developer-website/blob/096d48649a06130b683061e3ccebbfa2d27e6ad4/src/markdown-pages/build-apps/create-an-ab-test-application/platform-state-context.mdx

**Comment by jpvajda** [comment]
Looking into this a bit further.. according to our [SDK component docs](https://developer.newrelic.com/components/platform-state-context/) it's specified as the following: So I'm wondering if the correct syntax is actually:

{(platformState) => {

`and NOT`

{(PlatformState) => {

```
<PlatformStateContext.Consumer>
  {(platformState) => <pre>{JSON.stringify(platformState, null, 4)}</pre>}
</PlatformStateContext.Consumer>;
```

**Comment by jpvajda** [comment]
Our internal One Core docs specify this the way I expected, so I'll check our example to sure we have this consistently presented in our code samples.

<img width="901" alt="Screen Shot 2021-06-21 at 5 14 04 PM" src="https://user-images.githubusercontent.com/1395158/122838940-49db7f00-d2b4-11eb-95e7-db4f7e9e7872.png">
