### ISSUE TITLE
[UI: Pages] Create template to view details about single pack

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1330]
## Summary

Create a template that is used to render page data for each pack. Mobile layout work was split out into a different ticket.

We also want to try and cover some SEO / swiftype stuff including: adding some swiftype meta tags for query filtering, ensuring these pages are in sitemap.xml.

This template gets attached to each page via the `component` option in the action hook [`createPage()`](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createPage).

For now, only display one image.

### API Design questions - @kidk 
- where will the pack details data come from? strictly from Github repo? 
- the design shows markdown styling, but it looks like we are just getting plain text from the repo.
- we need to discuss ratings / install count and understand where that is coming from 
- contributor data, how will that be fetched? we decide to punt on it for now
- what does an empty state look like on an overview page for a pack with limited data?

### Components

Components we'll likely need for this:
- [Tabs (new)](https://github.com/newrelic/developer-website/issues/1329)
- [Install button link (theme?)](https://github.com/newrelic/developer-website/issues/1336)

## Acceptance criteria
- [x] Page displays all relevant data for a given pack
- [x] Page displays author data in the right section (_though this is not in the design_)
- [x] Page only displays tabs for things a pack contains (no need to gray out items)
- [x] Page has swiftype meta tags to apply query filters for content
- [x] Pages are listed in the sitemap.xml

## Helpful links
https://github.com/newrelic/developer-website/issues/1352

## Screenshots
Mock

![2021-05-26_12-59-23](https://user-images.githubusercontent.com/2952843/119723415-44f4ee00-be22-11eb-9ef4-5d8bf7250bc8.png)

**Comment by roadlittledawn** [comment]
Let's break out:
- Mobile layout: 5pt

**Comment by nr-kkenney** [comment]
i believe this is now done with @LizBaker PR merge and all AC checked off. moving to done.
