### ISSUE TITLE
[Fake API data] Load data into Gatsby graphql

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1332]
## Summary

Once we [have some sample JSON data](https://github.com/newrelic/developer-website/issues/1331), we want to load that data into graphql.

We want the data in GraphQL so we can query for a specific pack and get all the data we need for the [landing page](https://github.com/newrelic/developer-website/issues/1328) or a [single pack template page](https://github.com/newrelic/developer-website/issues/1330).

## Acceptance criteria
- [ ] confirm with @kidk when we'll have actual data in GraphQL
- [ ] All our sample JSON is loaded into graphql
- [ ] The data is in a form that's easily queryable for a given page path

## Helpful links
- in the other sites we use [gatsby-transformer-json](https://www.gatsbyjs.com/plugins/gatsby-transformer-json/)
- https://github.com/newrelic/developer-website/issues/1331
- opensource links various graphql types generated by JSON files [by the slug field](https://github.com/newrelic/opensource-website/blob/develop/type-defs.gql)

**Comment by zstix** [comment]
This has been resolved in #1357
