### ISSUE TITLE
[Nav] Finalize nav / IA approach

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1339]
## Summary

Work with Developer Advocacy to finalize new nav / information architecture approach. 

## Acceptance criteria

- [x] Discuss with @polfliet the long term plans for the dev site
- [x] confirm execution plan and timeline for improvement with @alexronquillo 
- [x] decide on what changes to make

**Comment by jpvajda** [comment]
@jaesius and @alexronquillo were going to provide some input on this.

**Comment by jpvajda** [comment]
This is move to Epic 5, Gatsby Sites. So I'll backlog it for now.

**Comment by jpvajda** [comment]
Depending on @alexronquillo availability we may be able to tackle this in Sprint 7 as he was going to help out with some ideas for the IA improvements.

**Comment by jpvajda** [comment]
@alexronquillo was going to take a 1st pass at designing a better IA for the developer site.

**Comment by jpvajda** [comment]
@alexronquillo do you feel you'll have this done by the end of our current sprint on July 6th? If not let me know when it may be completed and I'll prioritize it accordingly.

**Comment by alexronquillo** [comment]
We have a meeting on Thursday to talk this through. I can give a more accurate answer then, if that's cool.

**Comment by jpvajda** [comment]
I'll move it to sprint 8, it's not super urgent but I'm excited to see the new approach.

**Comment by jpvajda** [comment]
There will be no major changes to the dev site IA as part of olly packs and that work will be part of an entirely different project we are planning for Q3. where some of the dev site content will move to the docs site. 

Related issue: https://github.com/newrelic/developer-website/issues/1476
