### ISSUE TITLE
[UI: Components] Create image gallery

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1341]
## Summary

Create an image gallery that is scrollable to left and right.

### API Design Decisions to confirm with @kidk 

1. What is the size of images in the gallery?
2. What are the image limits we are enforcing?
3. Dashboards may need a larger image size to better showcase a dashboard's use

```
Max 6
.png format
Aspect ratio: 3:2
800 px (width)
1600 px (height)
```
2.  Where do we store images?

## Acceptance criteria
- [x] Gallery is responsive on smaller screens
- [x] we need to account for no image for a pack as images will be optional when making a pack.
- [x] display 2.5 images at a time as user scrolls through the gallery. 
- [x]  link to original image so it can be viewed in full resolution, on click open image in a new tab.

## Screenshots
Mock

![2021-05-26_12-59-23](https://user-images.githubusercontent.com/2952843/119723415-44f4ee00-be22-11eb-9ef4-5d8bf7250bc8.png)

**Comment by nr-kkenney** [comment]
moving this to done since @LizBaker's PR addressed the outstanding concerns.
