### ISSUE TITLE
[Analytics] Track key interactions / data

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1342]
## Summary

Track key interactions using Tessen via the theme and NR Browser agent.

Interactions include:

- [x] - Track refer link, where user came from (should automatically be captured by both)
- [x] - Track click on install pack button
- [x] - Track click on UI Tabs - Per Pack : / Dependencies / Dashboards / etc.
- [x] - Track clicks on Grid view / List View into a pack so we can know which view gets more clicks
- [x] - Track Sort by selections
- [x] - Track searches for packs via the pack search bar 
- [x]  - Track Filter by selections
- [x] - Track link clicks to individual packs
- [x] - Document this instrumentation like the (Docs Site)
- [x] - Validate data with NRQL queries or setup a quick dashboard

## Acceptance criteria
- [x] When user performs each interaction listed above, we verified data is reported to relevant destinations (typically segment and New Relic staging acct)

**Comment by rudouglas** [comment]
Updated Wiki for [Dev site](https://github.com/newrelic/developer-website/wiki/Editing-Event-Data-and-Instrumentation) and [Docs Site](https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation) to include examples of instrumentation and how to test locally

Most of the components are successfully instrumented, just had a couple of issues with the clicks to individual packs but working on it. Also, for point 1 @roadlittledawn is that expected to happen automatically as all `PageViews` are already currently tracked in both.

Here is the WIP Dashboard for the data https://staging.one.nr/0GbRmv7WBjy

**Comment by rudouglas** [comment]
Here are the 2 PR's with Previews, the first is for thee majority of the Instrumentation: https://github.com/newrelic/developer-website/pull/1399

The second implements the new `InstallButton` on the Pack Details page and instruments it as I noticed it hadn't been put in place yet
https://github.com/newrelic/developer-website/pull/1400

**Comment by rudouglas** [comment]
Gatsby Preview doesn't set the `GATSBY_NEWRELIC_ENV` environment variable, so instrumentation will not work with previews currently, will look into this:
<img width="507" alt="Screenshot 2021-06-11 at 17 14 49" src="https://user-images.githubusercontent.com/17122543/121716941-8e0e9880-cad8-11eb-8d37-87c4daaee7dd.png">
