### ISSUE TITLE
[UI: Pages] Add mobile layout for search/landing page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1349]
## Summary

We want to add a mobile / responsive layout for the pack search / landing page.

We don't have design specs yet for this, but we can make some reasonable assumptions. We'll likely want to stack all the elements, with search input / filters at the top and a list / condensed view of the packs.

Since left nav is TBD for this page, we may want to stack at either 1240px (when main and right sidebar stack) or 760px (when nav is hidden and accessible via hamburger menu in header).

## Acceptance criteria
- [x] On our mobile breakpoint, page elements stack with search input and filters at the top
- [x] The list of packs is more condensed so a user can scroll and quickly see all results

## Helpful links
- https://github.com/newrelic/developer-website/issues/1328
- [docs data dictionary page](https://github.com/newrelic/docs-website/blob/develop/src/pages/attribute-dictionary.js)
- [Theme Layout component](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/Layout/Layout.js) has some responsive-ness built-in

**Comment by zstix** [comment]
I'm closing this since it looks like the related PR got merged in. Lookin' good!
