### ISSUE TITLE
[IUI: Pages] Add searching, filtering, sorting to packs landing page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1350]
## Summary

This adds the searching, filtering, and sorting functionality to the packs landing page.

## Acceptance criteria
- [x] As a user I can quickly find a pack by name
- [x] As a user I can quickly see a list of packs by main category (ex, dashboards, visualizations, alerts, etc)
- [x] As a user I can quickly see the highest rated / most installed packs for a given main category

## Helpful links
- https://github.com/newrelic/developer-website/issues/1328
-  Sites with similar elements/interactivity: 
  - [Opensource: Explore projects page](https://opensource.com/explore-projects)
  - opensource uses [js-search](https://www.npmjs.com/package/js-search) to search its JSON
  - [docs: attribute-dictionary.js](https://github.com/newrelic/docs-website/blob/develop/src/pages/attribute-dictionary.js)

**Comment by rudouglas** [comment]
Search Functionality implemented on your `landing-page` branch @roadlittledawn 
https://github.com/newrelic/developer-website/pull/1363

**Comment by rudouglas** [comment]
And added filtering and sorting
More details in #1363 
https://user-images.githubusercontent.com/17122543/120709457-c8fb4580-c4b4-11eb-9467-47fa7665bd2f.mov
