### ISSUE TITLE
[UI: Pages] Add a grid / list view to packs landing page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1351]
## Summary

This adds a list view and a way to toggle between the grid / list views of packs on the landing page.

We don't have a design spec for what data should be displayed, but we can make some reasonable assumptions like: name, link to pack page, description. Anything that fits in rows with fixed, relatively short heights.

This list view can also be de-prioritized if needed in deference to the grid view.

## Acceptance criteria
- [x] A user can switch between a grid view that has an image and couple more pieces of data than the list view, which would have brief info
- [x] List view does not require lots of scrolling on small screen

## Helpful links
https://github.com/newrelic/developer-website/issues/1328

**Comment by rudouglas** [comment]
Added alternate List view for all packs which is responsive to view size #1371 

Changed the name of a couple of components to keep them in line with functionality:

`PackList` -> `PackGrid` (the list view uses `PackList` and vice-versa
`PackTile` -> `PackGridTile` (to differentiate from `PackListTile`

**Comment by rudouglas** [comment]
<img width="1112" alt="Screenshot 2021-06-04 at 15 05 10" src="https://user-images.githubusercontent.com/17122543/120814048-62bf0300-c546-11eb-9112-192d14a7168c.png">
<img width="569" alt="Screenshot 2021-06-04 at 15 05 37" src="https://user-images.githubusercontent.com/17122543/120814054-65215d00-c546-11eb-866b-8788f1ada091.png">

**Comment by rudouglas** [comment]
Sizing may need to be tweaked, also noticed this weird dot, so will have to investigate, looks like a list dot coming from somewhere:
<img width="115" alt="Screenshot 2021-06-04 at 15 07 19" src="https://user-images.githubusercontent.com/17122543/120814241-969a2880-c546-11eb-8e96-5cc44edc6dcd.png">

**Comment by rudouglas** [comment]
should be fixed with the latest commit
