### ISSUE TITLE
Github action to fetch and check-in observability packs

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1356]
## Description
Observability pack endpoints are now stitched into NerdGraph!

Since there are security concerns with making the observability pack API (the thing stitched into NerdGraph) public, and we don't want to check an API key into this repository, we have decided that the best path forward (at the moment) is to create an action that uses an API key stored in the workflow environment to query NerdGraph and pull down all the observability packs. To reduce impact on our other workflows, we should run this on an interval (rather than on all builds).

## Acceptance Criteria
- [x] Add API key to Github actions environment
- [x] Query NerdGraph to get _all_ observability packs
- [x] Save all packs as a JSON file
- [x] Check the JSON file into `main` (which should trigger a deploy)
- [x] Run the action on regular intervals
- [x] Write documentation for workflow
- [x] Write tests for the workflow

**Comment by nr-kkenney** [comment]
a comment, which is kind of an ask, but just a thought:
the data that currently lives in the repository is somewhat awkward. in particular, we should make sure that "empty" fields are represented consistently. as an example:
```json
}
      "dashboards": [],
      "name": "Consul",
},
```
vs
```json
{
     "name": "Varnish",
}
```

the consul pack has no dashboards, but its data is represented as empty array. the varnish pack also doesn't have any dashboards, but its data is represented as not even having the field. its fairly reasonable to workaround in the code, but i think having the data be consistent up front will save potential headaches down the line.

**Comment by jpvajda** [comment]
We decided to merge this in now, update our graphQL query on pages  to not use the fake alert data, then when alerts is available, add back the functionality for alerts
