### ISSUE TITLE
Persist the filtering and searching as query parameters

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1364]
Let's persist the filers and searches as query params so a user can easily link to a specific set of filtered packs easily via a shared URL. 

![Screen Shot 2021-06-03 at 3 41 02 PM](https://user-images.githubusercontent.com/1395158/120715777-55404500-c482-11eb-9214-86e970218948.png)

### Acceptance Criteria

- [x] a user can obtain a URL with the parameter used for filtered results.
- [x] a user can obtain a URL with the parameters used for search results.

**Comment by rudouglas** [comment]
Added Query Parameter functionality
<img width="820" alt="Screenshot 2021-06-04 at 12 31 27" src="https://user-images.githubusercontent.com/17122543/120795186-11f0df80-c531-11eb-83d9-a3fd8036325e.png">

**Comment by jpvajda** [comment]
👍 👍 👍
