### ISSUE TITLE
Change Application to Nerdpack in Pack Details Tabs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1366]
In the tabs section for an individual Pack details page, let's use the term Nerdpack not Applications as that is the name we are trying to use more consistently across our sites.

### Acceptance Criteria

The tab name `Applications` is changed to `Nerdpacks`

**Comment by aswanson-nr** [comment]
This is done and can be seen in this preview https://observabilitypacks.gatsbyjs.io/observability-packs/apache/QXBhY2hl/

**Comment by jpvajda** [comment]
I love it.
