### ISSUE TITLE
Standardized intro text for each Olly pack tab

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1367]
Each Tab should have a default intro section that introduces what each Tab is for. 

- Dependencies
- Dashboards
- Alerts
- Synthetics checks
- Visualizations
- Nerdpacks

In order to complete this we'll work with Toby Minton on the language but we can setup the intro sections of the tabs and put in some place holder text for him to review and provide feedback.

### Acceptance Criteria

- [x] Add an intro component to each tab above the screenshots
- [x] the component is always visible and is static content.
- [x] populate intro for each tab with standardized intro text (use latin placeholder for now)

**Comment by jpvajda** [comment]
Moving this AC to a new ticket: - [ ] Work with a content person to provide the text or pull from the docs site.  `Cayla Budhdev`

**Comment by nr-kkenney** [comment]
moving this to done since a new ticket was created to capture including final copy.
