### ISSUE TITLE
Dev Site SDK Component Docs updates

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1374]
## Issues

These problems were report by `Jeremias Menichelli` In Slack, `#gpe-news`

### 1
Ignore render in components methods. We had the same issue in One Core docs. The rule of thumb is to ignore methods starting with _ as they are private and methods starting with render including render itself too as it's the method React needs, but it's not public nor should be used

<img width="1112" alt="Screen Shot 2021-06-04 at 11 15 23 AM" src="https://user-images.githubusercontent.com/1395158/120844827-3480f980-c52d-11eb-9e63-346b5112bffc.png">

### 2

Ignore empty methods definition. A function that doesn't specify any parameters and returns undefined doesn't add up to anything to the user, even when the function just doesn't take any. In this case, for the children there are plenty of examples above where the user can infer how the children prop is used

<img width="1104" alt="Screen Shot 2021-06-04 at 11 17 05 AM" src="https://user-images.githubusercontent.com/1395158/120844863-3fd42500-c52d-11eb-9905-a73ed2b366c3.png">

### 3 

If you upgrade your docs bundle you will notice we improved the typedefs parsing, so instead of {Object you will actually get a type definition from the docs

<img width="752" alt="Screen Shot 2021-06-04 at 11 18 39 AM" src="https://user-images.githubusercontent.com/1395158/120857007-e3c5cc80-c53d-11eb-8998-eed2064c7630.png">

> The comment from above relates to another improvement, once you have that typedef, you will need to:

### 4

List that typedef below so the user knows the interface of the parameter (we do that in our docs, every time we encounter a typedef in a prop we add them in a typedef map we later render at the end, check for example these type definitions at the bottom https://one-core.datanerd.us/components/nerdgraphquery/?tab=code)
The other option is to just read the typedefs structure and print it in place.

### 5 
We recently fixed the returns / return tag parsing, but you need to correctly consume it in your docs code, I am seeing a lot of undefined in the function templates. Once you got that corrected, you will get richer function definitions like this one, for example

<img width="694" alt="Screen Shot 2021-06-04 at 11 24 32 AM" src="https://user-images.githubusercontent.com/1395158/120857066-f809c980-c53d-11eb-8f85-d126c5bb47f2.png">

### Acceptance Criteria

- [x] Get all the new components pulling in
- [x] Get the Typedefs populating correctly
- [x] Ignore render in components methods
- [x] Consume return tag parsing correctly
- [x] Ignore empty methods definition
- [x] Update Jest Tests

`From pointers from` @jerelmiller 

If there is a repeatable pattern, then its best to just add that handling in the file that extracts the definition for each type of thing (prop type, function, etc) Actually, I think most of those things in that list would be resolved by updated both of those files.

- Here is the custom plugin that we use to generate all data that is used for the one core components: https://github.com/newrelic/developer-website/tree/develop/plugins/gatsby-source-newrelic-sdk
- Here is the whitelist of documented components/apis, which means if there are new components that should show up in the site, this will need to be updated: https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/constants.js
- And here is the manually generated navigation API this is currently missing from the API: https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/navigationApi.js
- here is how prop type functions are extracted: https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/getPropTypes.js#L123-L128
- And again, similarly, any methods on a component will need to be updated here: https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/getMethods.js

**Comment by jpvajda** [comment]
@rudouglas this may be a really good issue for you to explore as it exposes a lot of how to we do things with the nr1 core sdk bundle and documentation rendering. interested? cc @zstix

**Comment by jpvajda** [comment]
I've pushed a PR to better explain this process https://github.com/newrelic/developer-website/pull/1376

**Comment by rudouglas** [comment]
@jpvajda sure i'll take a look at this one :)

**Comment by jpvajda** [comment]
🥇 @rudouglas

**Comment by rudouglas** [comment]
Attempting to update the SDK and I ran into a few issues. It looks like they recently changed the signature of the SDK release from `wanda--wanda-ec-ui--nr1-docs-${release}.js` to `doc-app-${release}-dev.js` so I made some changes to [loadSdk.js](https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/loadSdk.js) and [constants.js](https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/constants.js) and I'm not pulling the SDK successfully. 

I then ran into another issue during the `create pages` step. The `yoga-layout-prebuilt` module is throwing the following error:

```js
/Users/rdouglas/Documents/GitHub/dev-enablement/developer-website/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

ReferenceError: Blob is not defined
    at doc-app-release-2751-dev.js:37545:813500
    at Array.forEach (<anonymous>)
    at InsightsCollector._logFlush (doc-app-release-2751-dev.js:37545:813453)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
error Command failed with exit code 7.
```

I found the reference to `InsightsCollector` and `__logFlush` [here](https://source.datanerd.us/wanda/wanda-ec-ui/blob/499d06ad3aa0f6faff42d9eafabc66ea56c92d22/src/platform/core/instrumentation/insights/InsightsCollector.js#L80) which is the only use of `Blob` in the project. 

I reached out to the Platform UI team who suggested Polyfilling using https://www.npmjs.com/package/blob-polyfill so looking into this now

**Comment by rudouglas** [comment]
Made the updates as requests, we now have much richer data for TypeDefs:
<img width="627" alt="Screenshot 2021-06-17 at 16 33 44" src="https://user-images.githubusercontent.com/17122543/122428497-d969f080-cf89-11eb-896f-0589ba222fef.png">

And return tag parsing:
<img width="891" alt="Screenshot 2021-06-17 at 16 33 13" src="https://user-images.githubusercontent.com/17122543/122428485-d5d66980-cf89-11eb-9f9c-e227bf583643.png">

I am seeing a few errors, but having trouble pinpointing their origin. Strangely, they disappear when you `Back` then `Forward` in the browser

 - An error being rendered on the [Steps page](https://developerwebsitedevelop-ruairiupgradesdk.gtsb.io/components/steps/)
 - An error being rendered on the [List page](https://developerwebsitedevelop-ruairiupgradesdk.gtsb.io/components/list/)
https://user-images.githubusercontent.com/17122543/122431927-c6a4eb00-cf8c-11eb-8f6a-16736eee28e0.mp4

Also:
 - An issue with [Example 1 on the Radio page](https://developerwebsitedevelop-ruairiupgradesdk.gtsb.io/components/radio/)

Will need to look into these

Other potential action items that:

- [ ] Update Icon gallery
- [ ] Follow up ticket to upgrade again in 1/2 months to keep components up to date

**Comment by jpvajda** [comment]
I'm stoked for more accuracy in these docs. 💯

**Comment by rudouglas** [comment]
Opened up a new ticket for the SDK errors #1411, but I think the steps in the documentation are sufficient for the core flow
