### ISSUE TITLE
add a Arrow button to move through the gallery so it's clear this is gallery component

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1388]
### Issue

The image gallery scrolls which is cool but it only shows it's scroll-able by showing the browser scroll bar. This works for people that have this enabled in a browser, but not for those that disable this browser feature.

### References

- Definitely look at the many gallery components that exist to get some ideas of this should work.. 

1. https://react-bootstrap.github.io/components/carousel/
2. https://reactjsexample.com/responsive-and-flexible-carousel-component-with-thumbnail-support/

If we need  design decision we can ask @danielgolden for a pattern we've used before.

### Acceptance Criteria

- [x]    add a Arrow button to move through the gallery so it's clear this is gallery component.
- [x]     On click, stop the gallery in the middle of an image
- [x]     As the images slide, keep the gradient fading on the right side of the image Related to: newrelic/developer-website#1385

**Comment by zstix** [comment]
This has been completed in PR #1417
