### ISSUE TITLE
Release workflow for developer site failed

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/developer-website#1403]
### Background
latest run of the `release` workflow failed. the failure can be seen here: https://github.com/newrelic/developer-website/actions/runs/929497851.

it looks like we forgot to remove [another dependency](https://github.com/newrelic/developer-website/blob/985c4b391599b3b5d24c6b7b358db41b61d41c82/.github/workflows/release.yml#L124) on the job we removed. should be simple to fix.

### Acceptance Criteria
- [ ] workflow works once again

**Comment by rudouglas** [comment]
Removed dependency on checkout-and-build and checked for any other references to make sure nothing else is dependent on it
