### ISSUE TITLE
Communicate Pack support levels somewhere in the public catalog.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1408]
Currently we document [OSS project types](https://opensource.newrelic.com/oss-category/) on the OSS Site, and provide default repo image files you can reference within an repo. However this is different. We need to document this concept in the Public Catalog perhaps as a dedicated page so we can link to it, and reference it in many places.

We have 3 categories of Olly packs to define and we'll need to decide to where to put this information in the Dev Site.

Built by New Relic | Verified | Community
-- | -- | --

### Acceptance Criteria

- [x] obtain official copy from `Cayla Budhev`  `UIWRITE-1255`
- [x] Work with `Kike Alonzo` on an approach
- [x] Support level is shown in the right rail area of the How to use section
- [x] content can be markdown .
- [x] we'll need to define the standard content blocks for each support type and work with @caylabudhdev on that.

**MOCK UP** 👨‍🍳 

![#1432](https://user-images.githubusercontent.com/8354661/124613211-4844b600-de73-11eb-9622-d238586cb6f6.jpg)

**Comment by jpvajda** [comment]
We need to confirm with Calya what the default content is for each support type

**Comment by roadlittledawn** [comment]
@jpvajda should we support markdown for this content or just plain text? i'm guessing markdown would be nice for links and such.

**Comment by jpvajda** [comment]
@roadlittledawn i added AC to support markdown.. 💯

**Comment by jpvajda** [comment]
@roadlittledawn can you put an estimate on this issue?
