### ISSUE TITLE
Issue rendering some Examples from SDK

### ISSUE THREAD

**Issue by rudouglas** [newrelic/developer-website#1411]
### Description

Afteer upgrading the SDK version to pull in new components we noticed that some of the examples are throwing errors and not rendering a expected in the UI. The same issue/error is occurring for our Internal doc site so I think the issue lies in the SDK itself. I've pinged the team in Slack [here](https://newrelic.slack.com/archives/C01A76P3DPU/p1624036420252900)
### Steps to reproduce

See the issue on the following pages:

 - https://developerwebsitedevelop-ruairiupgradesdk.gtsb.io/components/list/
 - https://developerwebsitedevelop-ruairiupgradesdk.gtsb.io/components/steps/

Reproduction here:
https://github.com/newrelic/developer-website/issues/1374#issuecomment-863360800

AC:

- [ ] Follow up with the platform UI team for status: `ONE-Core 506` (likely won't be resolved anytime soon)
- [ ] obtain a status of when this will be done.

**Comment by jpvajda** [comment]
@rudouglas Thanks! Are we concluding that it's not a site issue and actually a problem with the SDK itself? It looks like they have a JIRA issue for this `ONECORE-506`

**Comment by rudouglas** [comment]
Yes that's correct @jpvajda, what we could do is remove the components for the moment until this is resolved as users will see issues, but it's only affecting 2 examples so not sure if that's necessary or not?
