### ISSUE TITLE
Update SDK version ~ July 31st

### ISSUE THREAD

**Issue by rudouglas** [newrelic/developer-website#1413]
This is a reminder to update the SDK version to keep it in line with new component and API releases. This should be done regularly but the date is arbitrary.

Follow the steps in the Contributing guide:

https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#updating-the-sdk-documentation-bundle

### Acceptance Criteria

- [x] the [developer site SDK component library docs](https://developer.newrelic.com/explore-docs/intro-to-sdk/l) references the latest version of the one core SDK.
- [x] consider how we'd automate the update of the SDK and provide recommendations .

**Comment by zstix** [comment]
When we update the SDK to the latest version, we will want to ignore two component properties. For more details see [this slack thread](https://newrelic.slack.com/archives/C01R2TB8BUZ/p1627492957079200).

This, most likely, will require making an adjustment to the [`IGNORED_PROPERTIES `](https://github.com/newrelic/developer-website/blob/develop/plugins/gatsby-source-newrelic-sdk/src/getPropTypes.js#L15) constant.

**Comment by elaguerta** [comment]
Some tentative ideas  for automation:

**[step 1: pulling the sdk version from the one-core site](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#step-1-update-the-release-number-in-gatsby-config)**
1. use a script like [this gitwatch example](https://github.com/gitwatch/gitwatch) to keep tabs on changes to the `gatsby-config.js` file in one-core. 
2. Use a github action to run the script at the end of every month or whatever cadence. 

**[step 2: including new components and apis](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#step-2-add-any-new-apis-or-components-to-our-constants-list)**
This is trickier and seems like we need a human to do it, but maybe there is a way to help the human doing it. 
1. Getting notifications for new posts to the [change-log](https://www.notion.so/Changelog-705d1c884a554774b468107731cf0e3f) might be helpful.
2. Like step 1, you could do a [gitwatch type thing](https://github.com/gitwatch/gitwatch) on the `nav.yml` file in one-core. 

**[step 3: updating the nav bar with new components](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#step-3-add-any-new-apis-or-components-to-the-navigation)**
The sdk file structure, or the inheritance and import structure of the source code, might provide enough for gatsby to autogenerate the nav bar.
