### ISSUE TITLE
Default (varies by browser) select styling for tab items for mobile is displaying poorly

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1421]
the drop down selector style for the tab items varies by browser, we should ensure we are consistently presenting this text in a format that is readable. 

### Acceptance Criteria 

- [x] ensure we display the text in the drop down consistently on both light and dark modes in all browers for both mobile and desktop.
- [x] this may require some testing of chrome, firefox, and safari on desktop and mobile devices to check our consistency.

**I-phone Firefox** 

![IMG_8D7008DEA995-1](https://user-images.githubusercontent.com/2952843/122475817-0dd5b080-cf7a-11eb-9be1-cab7e5281a04.jpeg)

**Comment by jpvajda** [comment]
we could use our dropdown component for this need, but we'll want to check the accessibility of that component and ensure that is accessible to all types of users.

**Comment by zstix** [comment]
This seems to be an iOS issue: you can set the foreground color of the `<select>` element, but not the background color. If I recall correctly, all browsers on iOS use the same rendering engine as safari (webkit). We can just unset the colors on that browser / rendering engine.
