### ISSUE TITLE
[Public Catalog] Update Observability Pack filter queries to return results

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1426]
### Dependency 

`Jira` `VIRTUOSO-1070`

 it seems we have placeholder filters for synthetics, applications and alerts, visualizations, but we aren't yet querying graphql  for that metadata given that’s  was was currently being returned from the Graphql API when we implmented the filter.

We've also de-scoped surfacing synthetics, visualizations and nerdpacks from olly packs so the only filter available to us will be alerts

### Acceptance Criteria

- [x] wait till the alert data field is added before updating the query, will need to confirm with @jbeveland27 
- [x] update [query found here](https://github.com/newrelic/developer-website/blob/83194769e215c2ae1d432ed58d6b5af5d9f91d5d/src/pages/observability-packs.js#L131) to return results in the UI.
- [x] also update the [fetch olly pack workflow script](https://github.com/newrelic/developer-website/blob/feature/o11y-packs/scripts/actions/fetch-observability-packs.js)
- [x] manually update the dummy data

**Comment by jbeveland27** [comment]
Adding Alerts to the schema will be done in [VIRTUOSO-1070](https://newrelic.atlassian.net/browse/VIRTUOSO-1070). We haven't spec'ed out the work to add synthetics/nerdpacks/visualizations to the OpenInstallation API yet.

**Comment by jpvajda** [comment]
@jbeveland27 nerdpacks / applications is definitely out of scope for our MVP, so you could opt to not add that for Sept. as for viz and synthetics, I'll add an agenda item for next to confirm if this is in / out.

**Comment by aswanson-nr** [comment]
Should we also remove the placeholder tabs in the detail view for synthetics/visualizations? @jpvajda

**Comment by jpvajda** [comment]
@aswanson-nr yes, new 🎫 for this as we just learned these are officially out-a-scope for the public catalog  >> https://github.com/newrelic/developer-website/issues/1482
