### ISSUE TITLE
Display a count in the filter drop-downs on the pack grid view so it's clear how many items exist for each filter type.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1429]
an accurate count is shown for dashboards, visualizations, applications, etc in the filter packs containing drop down to specify how many of each pack component. is available in the catalog. 

### Acceptance Criteria

- [x] Return count of each pack component in the filter 
- [x] Count should accurately reflect how many components are available. 

### Mock Up 

<img width="466" alt="Screen Shot 2021-06-24 at 5 37 06 PM" src="https://user-images.githubusercontent.com/1395158/123345357-1d716e00-d513-11eb-9eb5-e519f016bdfb.png">

**Comment by rudouglas** [comment]
Should look like this now
<img width="358" alt="Screenshot 2021-07-01 at 16 57 22" src="https://user-images.githubusercontent.com/17122543/124154661-9a5d9400-da8d-11eb-8d09-580868a4b56f.png">
