### ISSUE TITLE
General Search 🎖️ bar(s) Improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1430]
These are UX feedback improvements to our search bar and filter bars on our sites. 

### Acceptance Criteria

- [x] The Contrast for the placeholder text in the search fields is too low, increase text tone so it's more visible
- [ ] Align the search in the filter search in the sidebar with the catalog search bar 

### mock up

<img width="1696" alt="Screen Shot 2021-06-24 at 6 18 10 PM" src="https://user-images.githubusercontent.com/1395158/123351030-8360f400-d519-11eb-82e4-fd35175e14bf.png">

**Comment by rudouglas** [comment]
Not sure if this is contrasted enough:
<img width="554" alt="Screenshot 2021-07-02 at 16 15 17" src="https://user-images.githubusercontent.com/17122543/124295487-cdb52700-db50-11eb-9288-222de108d73d.png">
<img width="547" alt="Screenshot 2021-07-02 at 16 15 23" src="https://user-images.githubusercontent.com/17122543/124295495-cf7eea80-db50-11eb-8a06-836d81fc683a.png">

**Comment by rudouglas** [comment]
After the updates to the nav styling, the search input plane may need to be reassessed, it will need to be pushed up but that may be too close to the top nav?
![Screenshot 02-07-2021 16-18-39](https://user-images.githubusercontent.com/17122543/124295959-5a5fe500-db51-11eb-936b-a43a9e93c15d.png)

**Comment by rudouglas** [comment]
PR for the theme update https://github.com/newrelic/gatsby-theme-newrelic/pull/423

**Comment by jpvajda** [comment]
This looks good to me. If we have to address that pack search  alignment we can iterate on that improvement.

**Comment by jpvajda** [comment]
filed https://github.com/newrelic/developer-website/issues/1459 for a follow up ticket to move the olly pack search bar
