### ISSUE TITLE
Install button improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1431]
Here are few minor improvements to make for the  Install button. 

### Acceptance Criteria   
 

- [x] Center the  dropdown for the install button as it's currently off to the right of the button.
- [x] Install buttons should not use the pack name as they an be very long, instead use _"Install Pack_"
- [x] Horizontally center that carrot 🥕 

<img width="367" alt="Screen Shot 2021-06-25 at 11 24 43 AM" src="https://user-images.githubusercontent.com/1395158/123463121-5e679200-d5a8-11eb-96c6-941a49d77b09.png">

**Comment by rudouglas** [comment]
This requires changes to both the Theme and the Install button in the developer website:

https://github.com/newrelic/gatsby-theme-newrelic/pull/419
https://github.com/newrelic/developer-website/pull/1436

Result
<img width="205" alt="Screenshot 2021-06-28 at 15 39 56" src="https://user-images.githubusercontent.com/17122543/123655711-2326c680-d827-11eb-899a-3d4bf494ad95.png">

**Comment by rudouglas** [comment]
Dependent on this develop to feature branch merge:
https://github.com/newrelic/developer-website/pull/1442
