### ISSUE TITLE
Enable empty tabs to be clickable to promote contributions

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1432]
This will require design and copy but the idea is, if a tab has no component, we'd allow the user to click on the tab and they could see a  CTA of  how they can contribute to the pack in the case if a pack lacks a dashboard, synthetic, alert, nerdpack. 

### Acceptance Criteria

- [x] Work with `Kike Alonzo` on our design approach to encourage contributions on these tabs
- [x] Work with @caylabudhdev on copy for this page - @jpvajda 
- [x] Content can be found in `Google Drive`>   `UIWRITE-1255: [Observability packs] Review & update copy for pack details `
- [x] Default empty state content is show on each tab 
- [x] view repo link would work the same as #1447

![#1432](https://user-images.githubusercontent.com/8354661/124613211-4844b600-de73-11eb-9622-d238586cb6f6.jpg)

**Comment by kukukaka** [comment]
Hi!
I need some help with the copy, but here there is an early proposal for the empty case. I'd prefer to have a nice illustration there, but I added an icon as it would require more time to do it. Let me know what you think @jpvajda.

![#1432](https://user-images.githubusercontent.com/8354661/124613211-4844b600-de73-11eb-9622-d238586cb6f6.jpg)

**Comment by jpvajda** [comment]
view repo link would the same as #1447

**Comment by jpvajda** [comment]
I'm confirming with Cayla what content we can use for empty state. I believe there is a draft of it in the this doc: Content can
`Google Drive`> `UIWRITE-1212: [Observability packs] Write tab intros for the pack details pages`
