### ISSUE TITLE
Align Tabs and pack title with filter navigation and site logo 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1433]
Alignment of the tabs / title align title with filter navigation so there is a clean line for the eye. 

### Acceptance Criteria

- [ ] The tabs and title and filter navigation should all be on the same plane, so it more a straight line across the top of the page.
- [ ] Tighten up the spacing between elements in the navigation, (similar to the The Docs site) so the dev site logo is more aligned with the page heading

<img width="1801" alt="Screen Shot 2021-06-25 at 11 40 09 AM" src="https://user-images.githubusercontent.com/1395158/123464705-67f1f980-d5aa-11eb-83c8-2d207844abf7.png">

<img width="1619" alt="Screen Shot 2021-06-30 at 10 26 36 AM" src="https://user-images.githubusercontent.com/1395158/124019240-0cf34480-d9a6-11eb-8055-05e855b221b0.png">

**Comment by rudouglas** [comment]
This misalignment is occurring across the entire site rather than just the Observaility pack details page so I think this is a wider conversation we need to have
![Screenshot 30-06-2021 16-12-55](https://user-images.githubusercontent.com/17122543/123986230-0a044e00-d9be-11eb-8a62-6a96b6dd7c96.png)

**Comment by jpvajda** [comment]
@rudouglas now it can't be unseen. 🤣

**Comment by jpvajda** [comment]
I've added an approach we discussed in standup to the AC, if you make this change I can review the PR.

**Comment by jpvajda** [comment]
also if you can estimate this, that be cool.
