### ISSUE TITLE
Add a link to the pack's repo directory on the packs details page

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1447]
We'll want to highlight where a user can find the actually pack code on github so adding a clear CTA where the user can find the code would be nice.

### Acceptance Criteria

- [x] Work with `Kike Alonzo` on  design approach
- [x] leverage this pattern the  [OSS site pattern](https://opensource.newrelic.com/projects/newrelic/go-agent).
- [x] use the icon path to send the user to the correct pack directory.
- [x] IF no icon exists, send user to the [packs directory](https://github.com/newrelic/newrelic-observability-packs/tree/main/packs) OR send user to the correct pack directory.
- [x] Make the recommendation to add this field to pack to @jbeveland27 for a future release.

### Mock Up 

![#1447](https://user-images.githubusercontent.com/8354661/124607025-bc7c5b00-de6d-11eb-9d3c-9ec153a060f8.jpg)

**Comment by kukukaka** [comment]
@jpvajda I think that's a great idea. I did a quick test trying to align that pattern to this use case. I don't have the GitHub icon on the library so I'm sharing it with the placeholder, but you can get the idea. Also, I'm not sure if we want to promote these pages to be editable so I didn't add that action, but let me know if we should add it.

![#1447](https://user-images.githubusercontent.com/8354661/124607025-bc7c5b00-de6d-11eb-9d3c-9ec153a060f8.jpg)

**Comment by jpvajda** [comment]
We need to clarify where this button sends the users as the repo has packs in a directory... it's a slightly different flow then sending a user to  a dedicated  repository..
