### ISSUE TITLE
Resolve snyk `gatsby-source-swiftype` error

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1456]
When running snyk checks on the dev site, this package is failing so Snyk is returning an error in our PR checks

<img width="1507" alt="Screen Shot 2021-07-01 at 12 12 57 PM" src="https://user-images.githubusercontent.com/1395158/124171767-370c3b80-da66-11eb-8a7a-da0153d978f0.png">

<img width="984" alt="Screen Shot 2021-07-01 at 12 49 51 PM" src="https://user-images.githubusercontent.com/1395158/124175431-da5f4f80-da6a-11eb-97a8-453844f6fdf1.png">

### Acceptance Criteria

- [x] Fix this error so snyk checks pass in PRs

**Comment by rudouglas** [comment]
I don't actually have access to see issues in Snyk, @jpvajda could you sort a fella out?

**Comment by jpvajda** [comment]
@rudouglas I have made the request and added you the synk-external channel in slack.

**Comment by rudouglas** [comment]
Looks like the check that was failing was running against a `package.json` from a plugin that is not in the repo anymore

I deactivate that [project on Snyk](https://app.snyk.io/org/github-newrelic/project/b987af5c-b210-47da-ae12-7023382c1a2e/settings) and did a test PR which seems to be passing OK now:
https://github.com/newrelic/developer-website/pull/1461

**Comment by jpvajda** [comment]
Test PR passes all checks, this is done!
