### ISSUE TITLE
Move the search bar for olly packs into the results filter.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1459]
The search bar for olly packs is huge and there are 3 search bars on the dev site which is a bit confusing, Let's move this particular search bar into the filter results area of the olly pack index page.

### Acceptance Criteria

- [x] Obtain design from `Kike Alonzo`
- [x] Display a magnifying glass icon in the filter bar
- [x] Open a search input when icon is clicked
- [x] Filter observability pack results when text is entered
- [x] Instrument search entry (debounced)
- [x] Instrument clicking on the search icon
- [x] Clicking an "x" icon will clear and collapse the search input
- [x] Animate the expand / collapse action

### Mock Up 

<img width="1438" alt="#1459-1" src="https://user-images.githubusercontent.com/8354661/124603897-b042ce80-de6a-11eb-827b-caa53d0efc0d.png">

<img width="1438" alt="#1459-2" src="https://user-images.githubusercontent.com/8354661/124603908-b2a52880-de6a-11eb-8af6-738f8e66ac62.png">

**Comment by kukukaka** [comment]
@jpvajda I guess that using any of the current bars to provide o11y packs search results is not feasible, right?

I gave it a try but I think there are many items on that bar to include also a search. I suggest getting rid of the grid/list view controller. Usually, list views are to have more information density but I think in this case it was not working that way.

I also think making it a search icon and then expanding would simplify a bit the complexity of the packs bar, and make it easier to understand. What do you think?

<img width="1438" alt="#1459-1" src="https://user-images.githubusercontent.com/8354661/124603897-b042ce80-de6a-11eb-827b-caa53d0efc0d.png">
<img width="1438" alt="#1459-2" src="https://user-images.githubusercontent.com/8354661/124603908-b2a52880-de6a-11eb-8af6-738f8e66ac62.png">

**Comment by zstix** [comment]
I'm closing this issue since the work is complete and all the acceptance criteria have now been met.

**Comment by jpvajda** [comment]
I have a couple nits I'll put into another issue to improve this. I needs some fine tuning IMHO

**Comment by jpvajda** [comment]
https://github.com/newrelic/developer-website/issues/1473
