### ISSUE TITLE
Support markdown pack content on the public catalog

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1462]
Packs can contain markdown for descriptions we should render that correctly with the public catalog. This functionality is currently supported in the API, as confirmed by @jbeveland27 

### Acceptance Criteria

- [x] Only show a sub-set of markdown (headings, lists, links)
- [x] check for raw HTML in a pack , as we don't support that
- [x] check for markdown images in a pack , as we don't support that
- [x] when used, `description` markdown should be rendered correctly on a packs detail page.
- [ ] a url that is pointing to an external site should use the [external-link icon](https://github.com/newrelic/developer-website/blob/48a6adaafb0c62463ea95c156ad9203e9df51066/src/components/FeatherIcon.js#L70) 

<img width="289" alt="Screen Shot 2021-07-06 at 2 38 27 PM" src="https://user-images.githubusercontent.com/1395158/124663835-da46c180-de67-11eb-94dd-d01ebce68648.png">

### current functionality 

<img width="352" alt="Screen Shot 2021-07-06 at 2 37 29 PM" src="https://user-images.githubusercontent.com/1395158/124663785-c9964b80-de67-11eb-8f0f-d8cf6763f7a5.png">

<img width="1071" alt="Screen Shot 2021-07-06 at 2 37 21 PM" src="https://user-images.githubusercontent.com/1395158/124663791-cac77880-de67-11eb-9628-e1b7215d5041.png">

**Comment by jpvajda** [comment]
@zstix let me know if you'd like to add to this, but I felt we can work on this in sprint 8, and it just needs an estimate from the team

**Comment by zstix** [comment]
* This work should only be for the Observability Pack details page (details)
* Only show a sub-set of markdown (headings, lists, links)
* In a future ticket, we should swap out the description for a yet-to-be-implemented summary for the index page (grid / tile)

**Comment by jpvajda** [comment]
related ticket: https://github.com/newrelic/developer-website/issues/1467
