### ISSUE TITLE
Observability pack search bar nits

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1473]
Relates to https://github.com/newrelic/developer-website/issues/1459

[PR Build ](https://build-68533144-4f58-4908-a514-779dd6b6554c.gtsb.io/observability-packs/?filter=All&sort=Alphabetical)

### Issue 

There are several improvements we can make to the search bar in the olly pack results section of the pack catalog. 

### Acceptance Criteria

- [x] increase the size of the search icon as it looks really small at the current scale. 
- [x] increase the size of the search bar so it fills the gap between the results value.
- [x] when the search bar is expanded , bottom align the search bar instead of to align
- [x] there is no way to close the search bar when open, I think we need a way for a user to close it.
- [x] on mobile the search bar should be the same size as the sort by and filter drop downs.
- [x] showing `XX`results should update based on search results.

### Crude mock ups

<img width="423" alt="Screen Shot 2021-07-08 at 2 37 51 PM" src="https://user-images.githubusercontent.com/1395158/124987873-8d472480-dffa-11eb-9b4d-daab3bcfcfd7.png">

<img width="1401" alt="Screen Shot 2021-07-08 at 2 26 38 PM" src="https://user-images.githubusercontent.com/1395158/124987876-8ddfbb00-dffa-11eb-917c-b6734ebef751.png">

**Comment by rudouglas** [comment]
<img width="327" alt="Screenshot 2021-07-12 at 14 53 48" src="https://user-images.githubusercontent.com/17122543/125300891-5b97cb80-e322-11eb-9f6c-b87a318d2283.png">
<img width="1387" alt="Screenshot 2021-07-12 at 15 00 14" src="https://user-images.githubusercontent.com/17122543/125300895-5cc8f880-e322-11eb-9496-6a59314d8439.png">
<img width="1273" alt="Screenshot 2021-07-12 at 15 03 20" src="https://user-images.githubusercontent.com/17122543/125300898-5d618f00-e322-11eb-833a-0604d6708c3c.png">

 - Search bar now renders automatically on mobile as I think that's a better XP

**Comment by jpvajda** [comment]
perfect... 💯

**Comment by kukukaka** [comment]
Hi @jpvajda,

Can we work a bit on the vertical alignment of the items on that bar? The input boxes and the text on the right should be h-aligned. 

I think that without removing the dropdown labels and the view switch, it would be difficult. But of course open to other suggestions if you have better ideas.
On my original proposal, I removed the labels of the dropdown UI (we can keep the title on the code for a11y) as the first options on the dropdowns were self-explanatory (it said Everything instead of All if I remember it correctly). Also, the list view is not providing much until we have hundreds of items there, so I was proposing to remove it to simplify that bar a bit as it has many items.

**Comment by jpvajda** [comment]
@kukukaka 

1. I don't think we should remove the list view, as this is being designed to scale as the pack library grows. I'd rather plan for scale instead of removing a feature that is already in the UI.

2. For the vertical alignment, can you you contribute you[r CSS change for this functionality?](https://github.com/newrelic/developer-website/blob/2de4458ab1d1cf357f206cf0b2bee87f1c1e4d90/src/pages/observability-packs.js#L206) It's a lot of easier if our product designers can work along with us in code, if you are willing and interested to get these fine details aligned. If you can't contribute the project directly in the past we had our designers pair with an engineer and do some final tightening of CSS, which I'm happy to arrange.
