### ISSUE TITLE
Surface how to `build your own Pack` in the public catalog

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1481]
It be cool to allow a  user to see a clear call to action regarding how they can build their own o11y packs, and guide them to our contributor guide.  We have a similar pattern we use within the product to encourage a user to build a nerdpack. 

### Crude Mock Up 👩‍🍳 

<img width="1379" alt="Screen Shot 2021-07-12 at 4 25 33 PM" src="https://user-images.githubusercontent.com/1395158/125364045-044c2800-e32f-11eb-957c-741f4860853f.png">

### Acceptance Criteria

- ~Obtain a final design from `kike alonzo`~
- [x] A Build your own pack tile is always the first tile visible 
- [x] On click, the user is taking to the Pack Repo.

**Comment by zstix** [comment]
@jpvajda Are you cool if we mark this as complete (or push it to a later sprint)? We have completed the engineering work.

**Comment by jpvajda** [comment]
@zstix sure, I filed this as a follow up 🎫 

https://github.com/newrelic/developer-website/issues/1485
