### ISSUE TITLE
Remove visualization and synthetic tabs from public catalog

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1482]
We've de-scoped surfacing synthetics, visualizations and nerdpacks from olly packs so we don't need these tabs in the Ui.

`note`: Custom visualizations will be supported via dashboards only. The dashboard UI will show a message to help the user subscribe to a custom visualization. 

### Acceptance Criteria 

- [x] Remove the visualizations tab from the public catalog
- [ ] Remove the synthetics tab from the public catalog

**Comment by elaguerta** [comment]
I'll start on this one
