### ISSUE TITLE
Redirect dev site urls to docs site urls

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#1496]
To prepare for some content migration work planned by the Dev Advocacy team, we need to have a mechanism for redirecting dev site urls to docs site urls. The original dev site docs will be removed in the migration. Because some of the dev site docs have redirects in their frontmatter, this inter-site redirects will also need to account for those once the dev site docs are removed.

## Acceptance Criteria

- [ ] Provide a mechanism for redirecting dev site urls to docs site
- [ ]  When complete confirm with @jaesius and @alexronquillo so they can start their content migration work.

**Comment by jpvajda** [comment]
Once we confirm if this isn't possible as the docs site is designed today we can consider this effort.

**Comment by alexronquillo** [comment]
After some conversations with DevEn and Docs, this doesn't seem to be possible... or at least, no one knows how to do it if it is.

**Comment by roadlittledawn** [comment]
the docs site supports external redirects (sites with different domain name) a la [this data file](https://github.com/newrelic/docs-website/blob/develop/src/data/external-redirects.json) and some code that reads it and creates the redirects on build. 

so we could something similar on developer site side of things.

**Comment by alexronquillo** [comment]
@roadlittledawn This seems like a good short-term solution, but one option under consideration is removing the dev site altogether after the migration (this hasn't been officially decided yet). So we may still need a long term solution. However, because this is only for the content migration scope and not the dev site deprecation scope, this seems sufficient to me.

**Comment by jpvajda** [comment]
🤖 🚫
