### ISSUE TITLE
Update the SDK `OCT`

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#1502]
This is a reminder to update the SDK version to keep it in line with new component and API releases. This should be done regularly but the date is arbitrary.

## 🚨 This update requires special attention
There is a prop we want ignored from the docs as it won't work externally. This is currently in the ignored props array but we'll need to confirm it's working and being excluded when we update to a version of 2917 or greater. If we still haven't reached that version by this ticket please include this message in the next one :)
Prop name: `unsafeExperimentalNamespaces`
Components: NerdGraphQuery, NerdGraphMutation

Follow the steps in the Contributing guide:

https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#updating-the-sdk-documentation-bundle

### Acceptance Criteria

- [ ] the [developer site SDK component library docs](https://developer.newrelic.com/explore-docs/intro-to-sdk/l) references the latest version of the one core SDK.
- [ ] consider how we'd automate the update of the SDK and provide recommendations .

**Comment by jpvajda** [comment]
since we are so busy with I/O will bump the next SDK update to Sept 30
