### ISSUE TITLE
[Public Catalog] Update the “Install” button to be “View installation docs” for integration packs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1513]
## Description
On the [ObservabilityPackDetails](https://github.com/newrelic/developer-website/blob/feature/o11y-packs/src/templates/ObservabilityPackDetails.js) template, the **Install** button on the **_integration packs_** should now read `View installation docs` and link to the documentation `url` referenced in the pack.

**!NOTE! The view repo button is not in this design, but it should be on this view.** 🤷 

<img width="1665" alt="integration_pack" src="https://user-images.githubusercontent.com/1395158/128577041-0e74776c-f8fa-405d-b56d-f7ca3939eb8d.png">

`note:` an "integration" pack is not defined by type, so to decide which button to use, we'd need to look if the pack has install-able components (dashboards, alerts, etc) IF NONE, show view installation docs button

`note:` the pack migration will need to occur first. 

## Acceptance Criteria 

- [x] Ensure the CTA button on this details view is named `View installation docs`. 
- [x] On click the user should be directed to the correct documentation `url` that is referenced in the pack

**Comment by rudouglas** [comment]
This is dependent on the `documentation` data being present in NerdGraph, will update when we have more information from the Virtuoso team
