### ISSUE TITLE
[Public Catalog] Use I/O Logo on  quickstarts landing page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1535]
## Summary

On the quickstarts landing and details pages, we want to display a TBD new logo instead of Developers logo above left sidebar menu.

## Acceptance criteria
- [x] When viewing the quickstarts landing page or a quickstart details page, the new logo is displayed instead of Developers site logo
- [x] on click of the I/O logo take user back to the catalog I/O landing page.

## Helpful links
Relates to #1414

**Comment by LizBaker** [comment]
Looks like we decided not to have the logo on the details page in favor of no left nav + breadcrumbs
