### ISSUE TITLE
[Swiftype] Add meta tags to details pages

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1539]
## Summary

Add the following `<meta>` tags to the `<head>` of all quick start detail pages so we can use that in swiftype search queries.

The theme's [SEO component](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/SEO.js) does this automatically by looking at the domain of a given site's `siteUrl` (set in `gatsby-config.js`). We will need to include a way to pass the `type` for quick starts (because they live on developer subdomain) as a prop to override this default behavior. 

```
<meta class="swiftype" name="type" data-type="enum" content="io">
```

Add a `<meta>` tag for each keyword associated with a quick start:

```
<meta class="swiftype" name="tags" data-type="string" content="TAG_NAME_1">
<meta class="swiftype" name="tags" data-type="string" content="TAG_NAME_2">
```

Add a `<meta>` tag for the quick start name:

```
<meta class="swiftype" name="quick_start_name" data-type="string" content="QUICK_START_NAME">
```
the content should populate with `quickstart.title` field.

## Notes

In order to see those meta tags in development, I _think_ you may have to run a build.

## Acceptance criteria
- [ ] On each quick start details page, the above meta tags are in the `<head>` element
- [ ] On each quick start page, the only `type` field is `quick_starts` (and not `developer`)

## Relavant link
[Theme's SEO component](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/SEO.js)

**Comment by LizBaker** [comment]
@roadlittledawn i see the site type here as both "io" and "quick_starts" and somehow my change ended up being "quickstarts" 😂 which one of these would you prefer?

**Comment by roadlittledawn** [comment]
my bad. didn't get a chance to update all the tickets to use same value. i believe we said we'll go with `quickstarts`
