### ISSUE TITLE
obtain and add approved text for Data Source Tab Intro Section

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1542]
The Data source tab will have generic intro text, set for all integration packs. This is static content and should be generalized so each integration pack is introduce to the user.

<img width="1572" alt="Screen Shot 2021-08-24 at 3 53 38 PM" src="https://user-images.githubusercontent.com/70179303/130700477-040ef814-e236-4c84-91d6-b6893b973dd6.png">

### Acceptance Criteria

[name] observability quickstart contains [x] data source. A data source is the location where data that is being used originates from.

- [x] obtain approved content from `Toby Minton`  `UIWRITE-1296`
- [x] Add content to external site
- [ ] confirm with @bradleycamacho for PR review
- [ ] Add content to in product exp.

**Comment by jpvajda** [comment]
I've reached out to Toby to get some direction on this.

**Comment by jpvajda** [comment]
I followed up on a ETA for this. will move to sprint 12

**Comment by caylabudhdev** [comment]
Hey there! Couple of options for you: 

1: “[x] quickstart contains [y] data sources. This is how you’ll get your data into New Relic.”

2: “[x] quickstart contains [y] data sources. This will tell you how to get your [name] data into New Relic.”

Let me know if you have any questions or concerns!

**Comment by jpvajda** [comment]
I followed up in the status of this as I had feedback on the propose content.
