### ISSUE TITLE
[Public Catalog] handle many dashboards with many images better

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1546]
Relates to #1541

On the external site when a quick start has many dashboard images of different name types, we currently show :one:  [them like this.](https://observabilitypacks.gatsbyjs.io/observability-packs/browser-examples/QnJvd3NlciBleGFtcGxlcw==/)  Whereas when we have many dashboards images of the same name type we show :two: [them like this](https://observabilitypacks.gatsbyjs.io/observability-packs/apache/QXBhY2hl).  

So  quick start can have N dashboards with N Images.

### Acceptance Criteria

- [x] stack carousels per dashboard name type 
- [x] add a line between each carousel 
- [x] Be careful of is making sure the height of none of those carousels gets too tall

### Bug
- [x] ensure we fix the bug where a carousel control dot is appearing next to a[ screen shot.](https://observabilitypacks.gatsbyjs.io/observability-packs/browser-examples/QnJvd3NlciBleGFtcGxlcw==/))

<img width="595" alt="Screen Shot 2021-08-25 at 5 13 07 PM" src="https://user-images.githubusercontent.com/1395158/130876395-c1485609-5bd9-44f1-a24b-e5ab225f72cd.png">

**Comment by zstix** [comment]
This work has been completed 🎉
