### ISSUE TITLE
[Swiftype] Exclude quick starts landing page from Swiftype

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1554]
### Exclude page from swiftype entirely

We _may_ want to disallow swiftype from indexing the quick starts landing page. Only the docs site does supports that currently. The [SEO component](https://github.com/newrelic/docs-website/blob/af9c43f33ba4bd8cedc95276a4d0bb783c35a01c/src/components/SEO.js#L22) accepts a prop to optionally add a `meta` tag to tell Swiftype "Get out of here!"

```
<meta name="st:robots" content="noindex" />
```

### Only include base page in swiftype

For similar pages, people have requested / expected this kind of page in some search results. For example, if a user searches `observability` or `quickstart` it's reasonable to surface our public catalog in those results. But we want to ensure swiftype only has 1 record in its index and not many (for each query param combo) that would introduce noise.

So we can create a crawl rule to exclude all pages with trailing slash and query params, so the only page that gets included is the base page.

## Notes
We want to do this because it would introduce noise in search results. It will match search terms on all the pack names on the page, AND it will create a record for every URL path with different query params.

If we wanted just one result, we could possibly create an exclusion rule for any URLs with other query params than the default in the Swiftype admin UI. And an inclusion rule for the default page we want.

## Acceptance criteria
- [x] Swiftype indexes only the base landing page without any query params or trailing slash
- [x] Swiftype still indexes all individual quick start pages

**Comment by jpvajda** [comment]
Determining if we need to consider this, it was lingering in the backlog. (cue Cranberries)

**Comment by roadlittledawn** [comment]
i'm wiffle-waffling on this one a little bit. i have a feeling we'll want the public catalog page to surface in _some_ search results (same happened with What's New page). but we'll only want swiftype to index _one_ record for the page and not a record per query param combo.

so for now i added the following swiftype crawl rule for developer to exclude pages that match this regex:

```
\/instant-observability\/[^\n\r]?
```

that should exclude pages like this:
* `/instant-observability/`
* `/instant-observability/?search=apache`

which should mean the only page indexed should be:
* `/instant-observability`

**Comment by jpvajda** [comment]
@roadlittledawn that sounds good to me.. but we do have an upcoming epic on improving search so if we find it's not yielding the expected results we can always modify our approach.
