### ISSUE TITLE
[Public Catalog] Setup Navigation for mobile views

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1557]
We need to decide on our  mobile nav approach for the I/O pages and get some design feedback on that approach.

### Pack Details

> How do we handle the tabs in mobile?

**Current**

<img width="430" alt="Screen Shot 2021-08-27 at 3 39 29 PM" src="https://user-images.githubusercontent.com/1395158/131191663-c3748bb7-aaa6-49a0-98e1-be37e82c1f62.png">

A: TBD

>  How do we handle the new filter navigation in mobile. 

A: we won't show navigation on the pack details so this should not be an issue. 

### Catalog View

>  How do we handle filter navigation? 

**Current**
<img width="401" alt="Screen Shot 2021-08-27 at 3 40 49 PM" src="https://user-images.githubusercontent.com/1395158/131191647-02e8a854-8506-4612-b25a-ca742ab04dd0.png">

A: TBD

**Comment by roadlittledawn** [comment]
Closing this as it's included as tasks in:
* https://github.com/newrelic/developer-website/issues/1534
* https://github.com/newrelic/developer-website/issues/1536
