### ISSUE TITLE
[Public Catalog] Pack Details page navigation

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1558]
The pack details page doesn't need to the filter navigation as you'd see on the catalog landing page, as there is nothing to filter by on this view. 

we'll also want to add the breadcrumb navigation that you see in the product now

### Mock up 

<img width="442" alt="Screen Shot 2021-08-27 at 12 38 15 PM" src="https://user-images.githubusercontent.com/1395158/131173918-6a8bd9bf-ca2c-40fd-a9e4-7a557f4e24b2.png">

### Acceptance Criteria

- [ ] 
Add breadcrumb navigation per the design

**Comment by roadlittledawn** [comment]
Closing since this work is already captured in this ticket https://github.com/newrelic/developer-website/issues/1559
