### ISSUE TITLE
[Public Catalog] Search bar improvements 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1560]
The search bar needs to be more aligned to this design. 🧑‍🎨 

<img width="1220" alt="Screen Shot 2021-08-27 at 3 56 03 PM" src="https://user-images.githubusercontent.com/1395158/131193103-afcd8c76-42a1-4ff9-b364-9d92f318ff17.png">

### Acceptance Criteria

- [ ] Make the seach bar more like the design above

**Comment by roadlittledawn** [comment]
Theme component looks pretty similar to this and is in the working branch now. Any adjustments can be handled via other layout/form control ticket
