### ISSUE TITLE
[Public Catalog] ImageSlider refactor

### ISSUE THREAD

**Issue by rudouglas** [newrelic/developer-website#1564]
### Description

In the mobile view, the section headings and images are separated by variable blocks of whitespace, which looks a bit awkward.

![](https://user-images.githubusercontent.com/70179215/131198987-4616fb4d-265c-451b-95fb-8759cd408790.png)

We use [pure-react-carousel](https://github.com/express-labs/pure-react-carousel) in-product so it might be worth mirroring that in the public catalog to keep them aligned, and so we don't have to maintain a custom created one as we scale

### Acceptance Criteria

 - [ ] Implement pure-react-carousel in the details page to replace our custom solution

**Comment by jpvajda** [comment]
deprioritizing as sustaining. deemed not critical for the mvp in todays' backlog refinement
