### ISSUE TITLE
Instrument the new Tessen library version that manages the Amplitude session on the Developer site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1572]
Related[ Trello Issue](https://trello.com/c/IS1fFZz2/53-developernewreliccom-instrument-the-new-tessen-library-version-that-manages-the-amplitude-session-on-the-developers-pages)

# Problem

At the moment we don't see what anonymous or identified users for that matter do on the developer.newrelic.pages

It also seems that events are not being sent through Segment due to some cookies policies.

For each page a user visits we want to see an Amplitude event registered. 

**To be defined**
- Event name (Page Visited, Page Loaded or we go with the Tessen defaults STFR_Page_viewPage ? )
- Event properties: application (docs, newrelic, nrone, opensource...)

# Solution

1. We need to upgrade to the latest Tessen library and make sure the the basic page navigation events are being fired and that they get to Amplitude

2. We need to send a new Page Loaded event for every page user visits.

3. In order to run this set of tests we'd need to complete the upgrade on 2 different sites. OSS / DEV

# Acceptance criteria

- [ ] Update tessen version
- [ ] Once completed we can ask `Luka Eterovic` to help us validate this change is working
- [ ] A new ticket is created for any follow up work

**Comment by nr-kkenney** [comment]
labeling this as `blocked` since this will require the theme to be updated in order to get this work done. at the moment, we are currently holding off on updating the theme, so this is blocked until we are ready to go.
