### ISSUE TITLE
[Public Catalog] Tiles on the overview tab use `cursor: default`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1589]
Tiles on the overview what's included section aren't  clickable at the moment so we want to make it clear to the user that these can't be clicked on.

@danielgolden suggested we use [cursor:default](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) so on roll over we show the The platform-dependent default cursor. Typically an arrow.

<img width="488" alt="Screen Shot 2021-09-07 at 11 32 48 AM" src="https://user-images.githubusercontent.com/1395158/132387200-42ea87d5-8de5-4dad-a923-7cf97dd06dae.png">

**Comment by jpvajda** [comment]
If approved by design we'd also do this in the product.

**Comment by jpvajda** [comment]
I spoke to @danielgolden and he wanted to take a different approach so we'll see what he thinks.

**Comment by rudouglas** [comment]
I think this is already the case @jpvajda the cursor is the default arrow on mouse-over

**Comment by jpvajda** [comment]
@rudouglas Yeah it seems to be working (kind of) but do me a [favor go here](https://observabilitypacks.gatsbyjs.io/instant-observability/apache/QXBhY2hl) and roll over the overview tiles with your mouse, the docs tiles actually show a cursor, not an arrow for me on both FF and Chrome. 

It's subtle but a bit confusing, happy to show you as well as it's hard to screenshot.

**Comment by jpvajda** [comment]
nevermind, it seems to do this on the text in each tile. this is Ok. 🍭
