### ISSUE TITLE
Quickstarts slack channel and hero rotation

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1604]
## Description
As we head to launch, we need to get some support stuff setup. This includes a help channel and hero rotation.

## Acceptance criteria
- [x] Create the slack channel
- [ ] Define a hero rotation that can span multiple teams

**Comment by jpvajda** [comment]
dup of this https://github.com/newrelic/newrelic-observability-packs/issues/212 so closing
