### ISSUE TITLE
End to end system test

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1605]
## Description
We will be coordinating with other teams to conduct a gameday/system test before launch. We will be responsible for a portion of the tests in a different portion of the product than the part we worked on.

The test plan is located in G-Drive at `Developer Enablement > Engineering > Observability Pack Initiative`

**Note**: we should probably time box this
### Acceptance criteria
- [ ] Conduct the end to end testing
- [ ] Create tickets for any issues found during the tests

**Comment by jpvajda** [comment]
duplicate of https://github.com/newrelic/newrelic-observability-packs/issues/215
