### ISSUE TITLE
[Public Catalog] Align QS CTA buttons on details page with In product expeirence.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1609]
Relates to https://github.com/newrelic/newrelic-observability-packs/issues/211

We've moved some buttons around in product and want to align the external catalog with the internal catalog. 

### Acceptance Criteria

- [x] Obtain design from @danielgolden 
- [x] Update button placement to match the mock up
- [x] Remove padding from top of right rail

### Mock Up 🎨 
**NOTE**: do not adjust the top bar to touch the global header
<img width="1782" alt="Captura de Pantalla 2021-09-10 a la(s) 1 04 57 p  m" src="https://user-images.githubusercontent.com/1395158/132892233-cc28f6b7-db91-4f4e-8a3b-52996a7e81ab.png">

**Comment by rudouglas** [comment]
<img width="379" alt="Screenshot 2021-09-13 at 14 11 20" src="https://user-images.githubusercontent.com/17122543/133089893-ea5c9359-7988-41ba-90ed-df597c365680.png">
<img width="1380" alt="Screenshot 2021-09-13 at 14 12 35" src="https://user-images.githubusercontent.com/17122543/133089901-65dec188-d25b-4a5c-9eff-b61129ff16a4.png">

**Comment by jpvajda** [comment]
looks great 👍
