### ISSUE TITLE
Replace placeholder video in the banner with a link to docs

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#1616]
This is a reminder that we'll need to add the IO video to the banner's `learn more` button once it's ready. 

AC
- [x] video is provided by marketing on Sept 27th but won't be live until 10/13
- [x] So replace the button link with a link to docs: `https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-quickstarts-overview/` 
- [x] this link will be live on 9/29

**Comment by jpvajda** [comment]
I follwed up up with the marketing to confirm the ETA for this video.

**Comment by jpvajda** [comment]
Video is here : https://www.youtube.com/watch?v=sFt1Tx5qPRU
