### ISSUE TITLE
[Public Catalog] Empty state tabs are not rendering the contributor message

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1627]
### Issue

On tabs with empty states we shouldn't show the count of 0 items in the text. we used to show a nice contributor CTA, so not sure what happened to that. 

### Steps to Reproduce 

[go to a QS](https://observabilitypacks.gatsbyjs.io/instant-observability/gatsby-build/d234c09c-3338-4713-8340-ca75766445d6) that doesn't have an alert or data source and view the content area. 

<img width="1279" alt="Screen Shot 2021-09-14 at 6 16 39 PM" src="https://user-images.githubusercontent.com/1395158/133350433-6b3fb487-8a57-4762-8dc0-5e1cf448f262.png">

<img width="1211" alt="Screen Shot 2021-09-14 at 6 16 35 PM" src="https://user-images.githubusercontent.com/1395158/133350436-93511c6c-c313-43ce-abff-45e1491176ed.png">

### Expected

Show the cool CTA to contribute when tabs are === 0

**Comment by LizBaker** [comment]
This will be fixed by https://github.com/newrelic/developer-website/pull/1620
