### ISSUE TITLE
Generate a list of URLS for the US links to quickstart install paths in NR1: `due by Sept 24`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1637]
### ISSUE

The EMEA GTM team would rather keep the experience in language and send EU users to the EU DC (Since I understand that there isn't a re-direct from one DC to the other). So the idea is to keep utilizing the current integrations page and add a link to the install there. This would be until we have the global I/O experience in Q4

Example sheet:  `G-drive` > `New Relic I/O URLs`

<img width="1417" alt="Screen Shot 2021-09-15 at 4 28 53 PM" src="https://user-images.githubusercontent.com/1395158/133518615-c66efd9e-de17-4216-96f8-ec1077825026.png">

### Acceptance Criteria

- [ ] ~~Generate all EU URLS that will be used for a quickstart after click of `install quickstart` on the external catalog~~
- [x] Confirm that the platform redirects based on region/account
- [x] Generate all US URLS that will be used for a quickstart after click of `install quickstart` on the external catalog
- [x] Add the script to `/utils` if we need to run this again. (see @jmiraNR comment below as to why)
- [ ] Provide this list to @jmiraNR 
- [ ] indicate the top 25 to focus on for localization efforts for marketing landing pages - @jpvajda 
- [ ] all else can be sorted alphabetically  @jpvajda

**Comment by jmiraNR** [comment]
@jpvajda Since we'll be adding dedicated packs as we progress, it would be great to have a process I could run where i could get an updated list weekly(?) and get the other sites up to speed. So this: If valuable add the script to /utils if we need to run this again. would be VERY beneficial.

**Comment by jpvajda** [comment]
@jmiraNR 💯  I feel we'll need these links pretty often.

**Comment by rudouglas** [comment]
@jpvajda it looks like i don't have access to that document/can't find it
