### ISSUE TITLE
[Public catalog] Grid/List view swapper does not work on mobile

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1641]
### Description
The Grid/List toggle does not work on mobile browsers. 

### Steps to reproduce
1. Open the public catalog, either imitate a mobile browser or use a real phone
2. Attempt to click/touch 
<img width="200" alt="Screen Shot 2021-09-15 at 4 36 34 PM" src="https://user-images.githubusercontent.com/70179303/133526862-1aedc969-6544-41ee-8fb8-aa92d4d56f4e.png">
3. Notice that nothing happens

### Expected behavior
After clicking the toggle, the catalog swaps between grid/list views 

### Additional info
- iOS 14.8 Safari
- Desktop Chrome 93, impersonating a mobile browser

**Comment by jpvajda** [comment]
design question to ponder: do we even want grid view on mobile, I feel like we'd just default to list view on that screen size

**Comment by LizBaker** [comment]
grid view is a single column with logos but list view has no logos. i kinda like the grid because of that, but i agree having both is excessive.
just a note: i'm unable to recreate this, the buttons work for me on mobile (ios14.8) and chrome (93) mobile impersonation

**Comment by aswanson-nr** [comment]
@LizBaker Thanks for checking this out. It looks like this is something I introduced on my branch for adding categories, since the feature branch is working fine. Could have sworn I tested it on both, but I guess not! @jpvajda  Gonna close this ticket
