### ISSUE TITLE
[Public Catalog] Set the correct Install links for quickstart InstallPaths

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1644]
Related  `VIRTUOSO-1309`

The pack details CTA button  should show `Install Quickstart` when there are `installPlan`s present in the Quickstart config. Currently, I believe it only changes when there are "installable components" (i.e. dashboards/alerts). So there just needs to be some additional logic to handle the installPlans use case (

`note` Virtuoso is handling this in Product for us. 😄 

### Acceptance Criteria

- [ ] The pack details CTA button  should only show `Install Quickstart` when there are `installPlan`s present in the Quickstart config

### A nice diagram 🧑‍🎨 

<img width="1170" alt="I:O InstallPlan-flow" src="https://user-images.githubusercontent.com/1395158/133692296-d0dc5bb5-896b-4a05-b53c-41f180a9a0db.png">
m

**Comment by jpvajda** [comment]
@jbeveland27 said @mbazhlekova had some bandwidth to take this ticket for us. 🥳

**Comment by jpvajda** [comment]
the 2nd AC above would be cool to also do in conjunction with this ticket, but let me know if aren't able to also take that @mbazhlekova, and thanks for helping out! We appreciate it

**Comment by jbeveland27** [comment]
@jpvajda One point of clarification:

> So there just needs to be some additional logic to handle the installPlans use case

I think the way we want to specify this is: _only show `Install Quickstart` when `installPlans` are present_. The main difference being that the presence of dashboards/alerts is irrelevant to determining the state of the button, because we only want to funnel you into the in-product install UI if we are capable of showing the install flow (which is driven by `installPlans`). Make sense?

**Comment by jpvajda** [comment]
@jbeveland27 doesn't AC 1 cover this?

**Comment by jpvajda** [comment]
I've followed up with @mbazhlekova & @jbeveland27 to see if they are still able to take this on

**Comment by jpvajda** [comment]
Maria is jumping on it soon.. 🥳

**Comment by polfliet** [comment]
@mbazhlekova do you think we can get this in on Monday Sept 20, would be awesome to also start end-to-end testing the installPlans from the public site, as well as deliver an awesome demo to Bill on Tuesday. Thanks for your help on this!!

**Comment by mbazhlekova** [comment]
@polfliet I started working on it Friday afternoon and hoping to have a PR up this afternoon.
