### ISSUE TITLE
IO banner styling issues on Firefox

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1649]
## Description
The IO banner styling is not working on Firefox.

### Steps to reproduce
1. Open Firefox
2. Go to [Instant Observability](https://observabilitypacks.gatsbyjs.io/)
3. Notice the broken styling
<img width="1791" alt="Screen Shot 2021-09-16 at 4 43 32 PM" src="https://user-images.githubusercontent.com/70179303/133702605-5f39c4ec-122a-4e0f-81cf-bf9faa718dc7.png">

### Expected behavior
It should look more like this:
<img width="1754" alt="Screen Shot 2021-09-16 at 4 45 27 PM" src="https://user-images.githubusercontent.com/70179303/133702632-6ad6d860-e689-4d6d-90f7-87d2b0722dd0.png">

**Comment by jpvajda** [comment]
I can't reproduce this.. what version are you on?

**Comment by aswanson-nr** [comment]
I have been unable to reproduce this either. I recommend we close it unless it's seen again

**Comment by jpvajda** [comment]
👍
