### ISSUE TITLE
[Public Catalog] set a fall back state for quickstarts that have no summary

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1654]
This came up for quickstarts that don't have a summary defined. Browser Examples is one. @jerelmiller was going to put some logic in place in the in product catalog to show a default message is summary isn't present as this is also something that occurs with Nerdpacks.

As a note, we put logic in place to make summary required, so this is just an issue on older packs, but may not hurt to have fallback approach if this happens to occur. I've also fixed the Browser Example pack 😉 

**In Product**
<img width="275" alt="Screen Shot 2021-09-17 at 1 53 49 PM" src="https://user-images.githubusercontent.com/1395158/133857845-077fff5e-7e30-44f7-9090-bef34cfd6201.png">

### Acceptance Criteria

- [x] IF a summary is not available for a quick start, show the text  "_No summary provided_"

**Comment by rudouglas** [comment]
<img width="1052" alt="Screenshot 2021-09-21 at 11 37 00" src="https://user-images.githubusercontent.com/17122543/134156458-11a6b9d8-8eb1-4e3b-a0e1-40de45dbec46.png">

**Comment by rudouglas** [comment]
@jpvajda  I assume we don't want to do the same in the actual details page of the quickstarts? IMHO it doesn't look great but wanted to get your thoughts

<img width="1284" alt="Screenshot 2021-09-21 at 11 41 43" src="https://user-images.githubusercontent.com/17122543/134157152-d8401c31-d97d-4dd6-b3ee-f5199d41167b.png">
