### ISSUE TITLE
Embedded pages fail to load

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1675]
## Description
Embedded pages are failing to load on learn.newrelic.com.
This is most likely due to a X-Frame header.

**Comment by mcaronnewrelic** [comment]
I believe that https://lc.sj-cdn.net/ is the referrer and is the Skilljar CDN where they serve this content from. Please include *.skilljar.com and *.sj-cdn.net on the list.

**Comment by aswanson-nr** [comment]
Adding the `*.skilljar.com` and `*.js-cdn.net` to the list of allowed domains for iframes did the trick!
