### ISSUE TITLE
[Public Catalog] update dashboard queries

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1681]
After we merge the feature branch for the I/O site we'll want to ensure our dashboard queries are working correctly

### Acceptance Criteria

- [x] Go to the `[DevEn] External I/O & Quickstarts Ecosystem` dashboard on staging
- [x] Check all widgets are reporting data
- [x] IF not, fix queries as needed.

**Comment by roadlittledawn** [comment]
Updated all widgets for latest tessen event naming. Removed the sort chart since we removed sort option awhile back.
