### ISSUE TITLE
[Public Catalog & Details Nerdlet] Should `View Repo` be `View repo`

### ISSUE THREAD

**Issue by rudouglas** [newrelic/developer-website#1737]
### Description

Got a message in the help channel that the convention normally used is `View repo` with a small-case `r`. We currently use `View Repo` in both the Public Catalog and in-product

<img width="636" alt="Screenshot 2021-10-01 at 14 32 54" src="https://user-images.githubusercontent.com/17122543/135628941-e965d24d-adc1-4824-aefe-c36a023c4013.png">

**Comment by jpvajda** [comment]
sentence case is the way.. 👉

**Comment by rudouglas** [comment]
Yasss sentence
Done in both prod and public

**Comment by jpvajda** [comment]
blocking until I confirm if the code freeze is over
