### ISSUE TITLE
Deeply nest the developer site navigation similar to the docs site

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1740]
### Description

The navigation sidebar is not nesting certain nav trees beyond level 2 of the navigation

### Steps to reproduce

1. Go to https://developer.newrelic.com/explore-docs/nr1-cli/
2. Notice the navigation isn't nested `New Relic One CLI`

### Expected behavior

Nav items under `New Relic One CLI` are indented to denote their place in the nav tree.

### Screenshots

<img width="324" alt="Screen Shot 2021-10-01 at 1 45 20 PM" src="https://user-images.githubusercontent.com/70179303/135684545-d7f5674d-8879-4632-a692-a5140bf204eb.png">

**Comment by jpvajda** [comment]
The docs site handles multiple level of nested nav elements, so we could do this, but I'm fairly certain we didn't establish this pattern until after we launched docs, so this is a feature request.
