### ISSUE TITLE
[Dashboards] Visualize quickstart installs leading to new user signups

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1756]
Relates to #1789 

### Issue

Ensure that pack installs can be tied to new user signups so we can measure sign up conversions from I/O external with the goal to be able to know if a new user signed up on the I/O site, did they Install a quickstart or not.

### Queries 

_there  was an attempt_

```

// page_action events DevEn currently has

FROM PageAction
SELECT
funnel(session,
  WHERE actionName = 'TDEV_QuickstartClick_instantObservability' as 'View details',
  WHERE actionName = 'TDEV_QuickstartInstall_instantObservability' as 'Click install',
)
SINCE 1 week ago
LIMIT MAX


// signup_events query from PLG  

FROM TessenAction SELECT filter(uniqueCount(anonymousId), WHERE eventName = 'TLMK_SignUp_signup'), filter(uniqueCount(anonymousId), WHERE eventName = 'TLMK_SignUp_signupThankYou') TIMESERIES AUTO SINCE 1 month ago

```

### Acceptance Criteria 

`Note` there is a `Tableau Dashboard` where this is being tracked which we can use to validate our queries. - @jpvajda has access.

- [x] update `wip` dashboards to track this data here `[DevEn] External I/O & Quickstarts Ecosystem`
- [ ] Share with @JuliaNocera as she was also interested in this data.

**Comment by rudouglas** [comment]
@jpvajda slack me a link to the query you are using, I think because they are 2 different events we'll need to do some trickery

**Comment by jpvajda** [comment]
I'm going to give a custom viz a whirl.

**Comment by jpvajda** [comment]
We decided the exploration of the anonymousID assumption should be a seperate ticket... which relates to this ticket as well....

**Comment by zstix** [comment]
This is _almost_ ready to be worked on, but was blocked on a few things:
* [x] [This issue](https://github.com/newrelic/gatsby-theme-newrelic/issues/563) (which was closed by [this PR](https://github.com/newrelic/gatsby-theme-newrelic/pull/568))
* [x] [This release of the theme](https://github.com/newrelic/gatsby-theme-newrelic/releases/tag/v3.5.0) (`v3.5.0`)
* [ ] Deploy a version of the developer site with the new version of the theme that includes anonymous IDs

**Comment by zstix** [comment]
Now that we have an `anonymousId` for all our events, I _think_ this is the query that we need to achieve the desired funnel. I'm going to add this to the _**[DevEn] External I/O & Quickstarts Ecosystem**_ dashboard.

```sql
FROM TessenAction
SELECT funnel(anonymousId as 'Unique users',
  WHERE eventName = 'TDEV_QuickstartClick_instantObservability' AS 'View details',
  WHERE eventName = 'TDEV_QuickstartInstall_instantObservability' as 'Click install',
  WHERE eventName = 'TLMK_SignUp_signup' AS 'Signup form',
  WHERE eventName = 'TLMK_SignUp_signupThankYou' AS 'Signup success'
)
SINCE 1 week
AGO LIMIT MAX
```
