### ISSUE TITLE
Update K8s operator documentation to reflect appropriate level of support

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/developer-website#1766]
## Summary

A request came in:
> the NR1 developer docs site says K8s operator is official. We have a customer taking this to assume supported. When they log a support ticket (because its not working) they are told it is not supported and open source. Can we get the docs site updated to remove the official statement as it causes customer pain.

Page is: https://developer.newrelic.com/automate-workflows/get-started-kubernetes/

## Acceptance Criteria
- [ ] update documentation to reflect that K8s operator is provided as-is

**Comment by jpvajda** [comment]
closing as i didn't see any references to this being officially supported, so perhaps it was changed alrewady.
