### ISSUE TITLE
[Dashboards] Setup funnel dashboard to show the external to internal funnel for the `see data` button

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1789]
Relates: https://github.com/newrelic/developer-website/issues/1756

### Issue 

We are trying to understand the install funnel from the public site to when a user clicks on the see data button in Virtuoso experience. 

This funnel can be nicely visualized with the in-product Tessen events, but not yet with the public Tessen events. It seems we have pageActions for the funnel events externally and we need to probably setup tessen events for these so we can make a single funnel query as such

### Example Funnel 🔽 

<img width="594" alt="Screen Shot 2021-10-22 at 8 22 43 AM" src="https://user-images.githubusercontent.com/1395158/138471501-f39667e1-c745-4916-8ddf-fa9c43df55ab.png">

### Funnel steps

**External Site**

1. User clicks install button on a quickstart 
2. User is taken to the guided install 

**Internal**
3. user goes through all the steps to install 
4. user clicks on see data

### Funnel that works for in the product cases. 
```
FROM TessenAction
SELECT
funnel(email as 'user',
  WHERE eventName = 'DEVEX_New Relic IO_initialLoad' as 'Visit New Relic I/O', 
  WHERE eventName = 'DEVEX_New Relic IO_listingClicked' as 'View details', 
  WHERE eventName = 'DEVEN_Quickstart Details_clickInstall' as 'Click install', 
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewQuickstartInstallationUI' as 'Load install',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewInstallStep' as 'View install step',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_deployQuickstartComponents' as 'Deploy components',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_clickSeeYourData' as 'See data'
)
WHERE email NOT LIKE '%@newrelic.com' LIMIT MAX
```

### Current funnel for the external site cases

```
FROM PageAction
SELECT
funnel(session,
  WHERE actionName = 'TDEV_QuickstartClick_instantObservability' as 'View details',
  WHERE actionName = 'TDEV_QuickstartInstall_instantObservability' as 'Click install'
)
SINCE 1 week ago
LIMIT MAX
```

### Acceptance Criteria

`note`: timebox to 3 points for research.

- [x] Determine how we connect these "funnels" so we can track the user install from the external site to the end of the guided install flow. 
- [x] consider how the internal funnel is using email as an identifer for a user and how the external site doesn't have that identifier
- [x] update the funnel component in the existing chart component on this dashboard  
- [x] Share approach with DevEx as @JuliaNocera also was interested in this data.

**Comment by zstix** [comment]
This is blocked for the same reason that the other funnel ticket is blocked (https://github.com/newrelic/developer-website/issues/1756): we need the developer site to have the latest version of the theme which includes the extra `anonymousId` field. More details in [this comment](https://github.com/newrelic/developer-website/issues/1756#issuecomment-947944624).

**Comment by zstix** [comment]
We were able to correlate _some_ information, but it's only from existing users. This is because we have a `customer_user_id` attribute that we can correlate across all events:

```sql
FROM TessenAction
SELECT
funnel(customer_user_id as 'user',
  WHERE eventName = 'TDEV_QuickstartInstall_instantObservability' as 'Public catalog install click',
  WHERE eventName = 'DEVEX_New Relic IO_initialLoad' as 'Visit New Relic I/O', 
  WHERE eventName = 'DEVEX_New Relic IO_listingClicked' as 'View details', 
  WHERE eventName = 'DEVEN_Quickstart Details_clickInstall' as 'Click install', 
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewQuickstartInstallationUI' as 'Load install',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewInstallStep' as 'View install step',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_deployQuickstartComponents' as 'Deploy components',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_clickSeeYourData' as 'See data'
)
WHERE email NOT LIKE '%@newrelic.com' SINCE 1 week AGO LIMIT MAX
```
^ We've added this chart to the bottom of our _**[DevEn] External I/O & Quickstarts Ecosystem**_

If the events in the product had an `anonymousId` or the events in the public catalog had a `sessionId` then we could get the data for _all_ users. At the moment, we don't have a unique unifying identifier to follow a user through all of these separate events.

**Comment by jpvajda** [comment]
@JuliaNocera I thought I'd share our findings in making this funnel.

**Comment by jpvajda** [comment]
we'll do a follow up issue on the the non existing user case.
