### ISSUE TITLE
[SEO] Research how to leverage our content for `Google` featured snippets

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#1799]
Google is very blunt about there being nothing you can do to get a featured snippet to show up in their search results, but is there _nothing_? We want to take some time to research how we can optimize and have the best chances of snippets appearing for specific quickstart searches

### Implementation Ideas

build this into our pack details pages as a gatsby plugin and just return the results of a pack as a featured snippet to google.  Ideally we could run a few tests so we can see if we try to get some pages to render as a featured snippet.

Possibly setup test for the follow:

- Dotnet
- Apache
- Fastly
- Java
- Lacework
- Cribl-logstream
- nodejs

### Acceptance Criteria 

- [ ] Timebox research effort
- [ ] Take a crack at getting a featured snippet by searching for quickstart details (longer strings are more likely to achieve this)
- [ ] Research if there are any ways to increase chances
- [ ] Create a ticket to implement any results found

**Comment by jpvajda** [comment]
depriortized for other I/O work

**Comment by jpvajda** [comment]
closing for now as this doesn't seem like it worth exploring.
