### ISSUE TITLE
[Details Nerdlet] Move quickstart logo and CTAs, make header sticky

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#1801]
We want the CTA buttons for quickstarts to remain visible to users even after they scroll. 

### AC
- [ ] (logo + name + main CTA) are in a sticky header and as the user scrolls down, they can access the main actions at any given time.
- [ ] Logo moves to the left
- [ ] CTA buttons move to the right 
- [ ] Measure before and after for data analysis so we understand the impact of this change + / -

### Design
![SKX929djFq0XEe7b0dVskeQPsHqVb0YEe4lwOHLZJAGOzTa63g-fIPBQrCoANf4vBYLyL4kDOs-Si2sSlsTeYLaoKA3UvP5pumOTojAGrakilADT3kNvFVl3KBGZaw61oHN-vyFZ=s0](https://user-images.githubusercontent.com/39655074/138000123-f33a9045-ffe0-4d73-8024-322e746b7cf2.png)

**Comment by zstix** [comment]
Looks like we got a couple small requests for adjusting the design. Once those are done and merged in this should be good to goooo!
