### ISSUE TITLE
[Public Catalog] Improve sticky header animation

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1842]
Relates to https://github.com/newrelic/developer-website/issues/1800

### Design Questions

- [ ] Is the design finalized?
- [ ] Will the In Product Details page also have a similar treatment?

We have a future concept with an improved animation for the sticky header that @legnaleama  previewed in a FIGMA design. When ready we'd implement this change on the Public Catalog 

### Acceptance Criteria

- [ ] TBD

**Comment by jpvajda** [comment]
@legnaleama  👋

**Comment by legnaleama** [comment]
At this point I would rather rethink the entire detail view as a whole. The current experience feels confusing at times (some elements appear interactive but aren't) and the layout makes the content feel overwhelming.

@jpvajda

**Comment by jpvajda** [comment]
closing as won't do
