### ISSUE TITLE
Use a better icon for the Elixir quickstart

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/developer-website#1873]
I happened to notice the [Elixir quickstart](https://developer.newrelic.com/instant-observability/elixir/fe51eb6d-a18e-40b5-a208-f61228bf79d5/) on the external site, but it the icon looks pretty bad both in the tile and in dark mode.

On the tile, you can see the image is not centered. My guess is that the Elixir drop is not centered in the bounds of the image file itself. What's curious though is that the icon on the tile _does_ have a transparent background, even though the details page does not.

<img width="351" alt="Screen Shot 2021-11-08 at 12 50 10 PM" src="https://user-images.githubusercontent.com/565661/140816187-c696c6bd-1719-42c2-98d8-02c41f9b0c6e.png">

Here you can see the icon on the details page. The non-transparent background really shows up in dark mode, where you can clearly tell the drop is not centered in the image bounds.

<img width="1752" alt="Screen Shot 2021-11-08 at 12 49 28 PM" src="https://user-images.githubusercontent.com/565661/140816285-12194bf1-f057-44d6-8f40-dce49fe5fea5.png">

Would be great to get a better image here if possible!

### Doc information (don't delete this section)

* https://developer.newrelic.com/instant-observability/elixir/fe51eb6d-a18e-40b5-a208-f61228bf79d5/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 93.0.4577.82
* **Device**: Unknown

**Comment by jpvajda** [comment]
https://github.com/newrelic/newrelic-quickstarts/pull/651
