### ISSUE TITLE
Span distributed tracing data were reported to UI but the Dashboard.

### ISSUE THREAD

**Issue by lucas2804** [newrelic/developer-website#1878]
- I've tested on my personal account, and I can create chart in dashboard with the query 
```sql
SELECT percentile(duration, 95) FROM Span FACET http.url  TIMESERIES
```
But in my company account, I can not create this chart, I even can not find `Span` table.

My company account context:
1) newrelic_rpm (8.1.0)

![Screen Shot 2021-11-10 at 14 06 23](https://user-images.githubusercontent.com/8488039/141066010-49f75815-3a01-42c6-9582-bd75de771a8c.png)
)

**Comment by jpvajda** [comment]
@lucas2804  thanks for reporting this, but this repository supports this website https://developer.newrelic.com. if you are having an issue with the New Relic product, you can reach out to New Relic Support or seek help from our community https://discuss.newrelic.com/
