### ISSUE TITLE
[Dev Site] Remove duplicate install cookie

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1889]
Relates to #1847 

We added a second install cookie that will eventually be removed. 

### Acceptance Criteria

- [ ] confirm with @devfreddy when this can be removed
- [ ] remove extra cookie [found here](https://github.com/newrelic/developer-website/blob/6a25339a6c6d61890cdfb91bc1de808e4cb36017/src/components/InstallButton.js#L157)

**Comment by jpvajda** [comment]
@devfreddy do you happen to know when it be safe to remove this second cookie? we've tagged it as sustaining so we don't forget, but I wanted to checkin with you on it. 🤔

**Comment by devfreddy** [comment]
@jpvajda It requires updates in 2 other repositories, ours (Guided Install) and catalog-pack-details. Both are in flight (or almost), I'll circle back in ~2 weeks to remove this extra cookie, post-Thanksgiving and post FTO.

**Comment by jpvajda** [comment]
@devfreddy thank you!

**Comment by jpvajda** [comment]
closing as this should be removed when we remove all the i/o site code
