### ISSUE TITLE
[Dev Site] Document new super tile component

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1890]
Relates to https://github.com/newrelic/developer-website/issues/1870

as a follow up to the addition of the [supertiles](https://github.com/newrelic/developer-website/tree/develop/src/experiments/super_tiles/components) component we want to ensure that is added to the dev site component documentation[ found here. ](https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md)

**Comment by jpvajda** [comment]
@abrunner94 👋

**Comment by abrunner94** [comment]
@jpvajda 👋 PR mentioned above
