### ISSUE TITLE
Can we deprecate the events page?

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/developer-website#1891]
I see the [events page](https://developer.newrelic.com/developer-events/) is woefully out-of-date. We've already had Nerd Days 2.0, but looks like this page never got updated.

Is there value in keeping this page around? If so, could we update it or do something to make it look not-so-abandoned?

### Doc information (don't delete this section)

* https://developer.newrelic.com/developer-events/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by alexronquillo** [comment]
I'm not sure if the DevRel advocates are going to start using this more in the future. @jaesius?
