### ISSUE TITLE
Fix errors in console on IO page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#1898]
## Summary

There are several warnings in the console on https:/developer.newrelic.com/instant-observablity when running it locally:
```
react.development.js:220 Warning: Failed prop type: The prop `variant` is marked as required in `Button`, but its value is `undefined`
react.development.js:220 Warning: Failed prop type: The prop `name` is marked as required in `PackTile`, but its value is `undefined`.
Warning: Failed prop type: The prop `fields` is marked as required in `PackTile`, but its value is `undefined`
```

Additionally, there seems to be a spike in this error which has triggered pager duty pages. Seems to be related to SDK, though it mostly happens on /instant-observability page, esp when requesting the page initially with query params already set

```
Error: Cannot read properties of undefined(reading 'Component')
```

## Acceptance criteria
- [ ] 

## Helpful links

**Comment by jpvajda** [comment]
closing as this page no longer exists.
