### ISSUE TITLE
[Dashboards] funnel dashboards should track new user data, not just existing users `part 1`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1913]
Relates to https://github.com/newrelic/developer-website/issues/1789

In our work to build the `BIG FUNNEL` ™️   We were able to correlate _some_ information, but it's only from existing users. This is because we have a `customer_user_id` attribute that we can correlate across all events:

```sql
FROM TessenAction
SELECT
funnel(customer_user_id as 'user',
  WHERE eventName = 'TDEV_QuickstartInstall_instantObservability' as 'Public catalog install click',
  WHERE eventName = 'DEVEX_New Relic IO_initialLoad' as 'Visit New Relic I/O', 
  WHERE eventName = 'DEVEX_New Relic IO_listingClicked' as 'View details', 
  WHERE eventName = 'DEVEN_Quickstart Details_clickInstall' as 'Click install', 
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewQuickstartInstallationUI' as 'Load install',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewInstallStep' as 'View install step',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_deployQuickstartComponents' as 'Deploy components',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_clickSeeYourData' as 'See data'
)
WHERE email NOT LIKE '%@newrelic.com' SINCE 1 week AGO LIMIT MAX
```
### Issue 

If the events in the product had an `anonymousId` or the events in the public catalog had a `sessionId` then we could get the data for _all_ users. At the moment, we don't have a unique unifying identifier to follow a user through all of these separate events.

### Acceptance Criteria

- [x] determine how we can identify a unique unifying identifier to follow a user through all of these separate events.
- [x] this may require discussing the problem with PLG or someone fromt the analytics team
- [x] define an approach and technical solution if this is something our team can even fix 
- [ ] file a follow up ticket to do this work or hand this off to the correct team at New Relic.

**Comment by rudouglas** [comment]
Links to where this code is implemented:

## DevEx
 - [DEVEX_New Relic IO_initialLoad](https://source.datanerd.us/nr1-dev-experience/marketplace/blob/5e48dc412723828dd8aa8f397522cecec825e2b7/common/components/Marketplace/Marketplace.tsx#L150)
 - [DEVEX_New Relic IO_listingClicked](https://source.datanerd.us/nr1-dev-experience/marketplace/blob/5e48dc412723828dd8aa8f397522cecec825e2b7/common/components/Marketplace/Marketplace.tsx#L191)

## DevEn
 - [DEVEN_Quickstart Details_clickInstall](https://source.datanerd.us/developer-enablement/catalog-pack-details/blob/7aa6e59246ef374ec90bbe67e18b9fb950807f67/src/components/install-button.js#L50)

## Virtuoso
 - [INSTALL_QuickstartInstallationPlan_viewQuickstartInstallationUI](https://source.datanerd.us/open-source/nr1-install-newrelic/blob/01fccd9067c41269cd68829a0164f67c6971f554/nerdlets/quickstart-installation-plan/App.js#L37)
 - [INSTALL_QuickstartInstallationPlan_viewInstallStep](https://source.datanerd.us/open-source/nr1-install-newrelic/blob/01fccd9067c41269cd68829a0164f67c6971f554/nerdlets/quickstart-installation-plan/components/InstallationSteps/Steps/LinkInstall/index.js#L67)
 -  [INSTALL_QuickstartInstallationPlan_deployQuickstartComponents](https://source.datanerd.us/open-source/nr1-install-newrelic/blob/01fccd9067c41269cd68829a0164f67c6971f554/nerdlets/quickstart-installation-plan/components/InstallationSteps/Steps/DeployQuickstart/index.js#L37)
 - [INSTALL_QuickstartInstallationPlan_clickSeeYourData](https://source.datanerd.us/open-source/nr1-install-newrelic/blob/01fccd9067c41269cd68829a0164f67c6971f554/nerdlets/quickstart-installation-plan/components/SeeYourData/index.js#L49)

We currently do this in the Theme by using the `js-cookie` package to pull the cookie value from Segment, but in product we have a `getCookie` function that we can utilize i think:

https://source.datanerd.us/developer-enablement/catalog-pack-details/pull/76

Virtuoso also have this function - https://source.datanerd.us/open-source/nr1-install-newrelic/blob/01fccd9067c41269cd68829a0164f67c6971f554/common/shared/cookies.js

But DevEx currently do not

**Comment by rudouglas** [comment]
PR with work completed: 
 - https://source.datanerd.us/developer-enablement/catalog-pack-details/pull/76

**Comment by rudouglas** [comment]
It looks like Virtuoso will do this work themselves and they also suggested some steps that may be missing from the flow, or that will require separate funnel flows to capture all the data:

```
Looking at your ticket, it looks like you're only hitting INSTALL_QuickstartInstallationPlan_* for Virtuoso Tessen Events, but there are at least 2 additional flows that don't land on the Quickstart Install Plan nerdlet:
 - A handful of flows land on the installation-plan nerdlet and would generate `INSTALL_InstallationPlan_*` events
 - The codestream install nerdlet is also its own thing, and I'm not sure what Tessen Events it generates
```

As part of this ticket i'll investigate those 2 points

**Comment by jpvajda** [comment]
@rudouglas Curious have they documented this anywhere?

**Comment by rudouglas** [comment]
@jpvajda i didn't get a chance to investigate this, as we are creating a follow-up ticket and the work on our side is done, we could add this to the follow-up (sorry not at my computer would you mind creating it 🥺):

 - Review the PR that includes changes to the Quickstart Details Nerdlet owned by DevEn
 - DevEx and Virtuoso are going to do the work on their nerdlets so follow up to see if they have created tickets we can track
 - Investigate the other flows mentioned above that we may not be capturing with the current funnel. Either include the missing steps in the current funnel or create a new funnel if needed
     - `INSTALL_InstallationPlan_*` events
     - Codestream install nerdlet events

**Comment by jpvajda** [comment]
marking as done, and the work is accounting for in the linked follow up ticket.
