### ISSUE TITLE
[Dashboards] Correctly set NRQL to generate sign up data

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1914]
Relates to #1756 

Now that we have the ability to track new user signups, let's improve our dashboarding so we can see the following data:

### Total Signups from install

<details>
<img width="359" alt="Screen Shot 2021-11-23 at 3 41 46 PM" src="https://user-images.githubusercontent.com/1395158/143140508-aab6ecc9-1513-4007-bb09-0bbeb7aa0e06.png">

a 😞 attempt
```sql

SELECT count(*) as 'Sign Ups', filter(uniqueCount(anonymousId), WHERE eventName = 'TDEV_QuickstartClick_instantObservability'AND eventName = 'TDEV_QuickstartInstall_instantObservability' AND eventName = 'TLMK_SignUp_signup' AND eventName = 'TLMK_SignUp_signupThankYou' )
```

</details>

### Signup from the install funnel 

<details>
<img width="583" alt="Screen Shot 2021-11-23 at 3 41 54 PM" src="https://user-images.githubusercontent.com/1395158/143140518-9b2842af-e873-49b9-814c-085a891f9dda.png">

a 😞 attempt

```sql 

FROM TessenAction SELECT filter(uniqueCount(anonymousId), WHERE eventName = 'TDEV_QuickstartClick_instantObservability'AND eventName = 'TDEV_QuickstartInstall_instantObservability' AND eventName = 'TLMK_SignUp_signup'AND eventName = 'TLMK_SignUp_signupThankYou') TIMESERIES AUTO SINCE 1 month ago
```

</details>

### Acceptance Criteria

[Dashboards are found here](https://staging.onenr.io/0Y8wpNN8xjO)

- [x] Update NRQL queries for these dashboard components with the correct queries so they generate data.

**Comment by jpvajda** [comment]
@rudouglas if you are bored during 🦃 , I'd be curious to learn why my queries are not working...

**Comment by rudouglas** [comment]
I've changed the queries a little bit so they are showing data but i'm not 100% sure if that's what you're looking for @jpvajda lets huddle on this

**Comment by jpvajda** [comment]
@rudouglas you nailed it. Perfect!

**Comment by jpvajda** [comment]
After looking at these queries and thinking about the problem we are trying to solve by presenting this data in a dashboard, I'm going close this out we can obtain our signup count from our funnel chart for a period of time, so that should be enough for us to use for now to measure signups from I/O, there is also a tableau report that provides the data we are trying to show via NRQL, so for now we have enough to work with. 

It's a little confusing as to why we are seeing different counts of sign ups depending on how we look at the data, but it's sort of a 🐰 🕳️  and it's not really our team's primary focus to figure out NRQL magic to report on this data.

**Comment by rudouglas** [comment]
Ye I was using a `Facet cases` for the newer charts so I think that just performs differently than the `funnel`
