### ISSUE TITLE
[Public Catalog] after implementing SSR, Disable PR previews for forks

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1918]
After we implement SSR we should disable PR previews for forks on the developer site as a malicious person could utilize SSR functions to exfiltrate environment variables

We should disable previews on forks, until there’s an “approve to run” ability for Gatsby SSR. 

### Acceptance Criteria

- [x] Disable previews on forks on the developer site repo
- [x] Update [contributor documentation](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md) to clearly state this is disabled
- [x] Request a new feature to allow the disabling previews on forks for sites hosted on Gatsby Cloud 
> we made this a [while ago](https://portal.gatsbyjs.com/gatsby-cloud/p/approvals-for-pr-previews-from-public-forks)

**Comment by aswanson-nr** [comment]
Gatsby support has confirmed that fork PR previews are disabled for the developer site.

**Comment by jpvajda** [comment]
@aswanson-nr great! Our contributor guide states that PR previews are not available on Forks, so I'd consider this done.
