### ISSUE TITLE
[Dashboards] Create a custom viz to return the data for the last step in the sign up funnel

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1919]
`Episode 4: Return of the Custom Viz...`

Relates to: https://github.com/newrelic/developer-website/issues/1914

### Issue

After trying to make NRQL return the data we are looking for... we found that we can't actually return data for a step in a funnel and we confirmed in #wizards-dashboards that functionality isn't available in NRQL.  We have this[ query](https://staging.onenr.io/0Z2R518M1Rb) which provides a nice funnel of 4 different steps (4 WHERE clauses that all have a similar attribute).

### 📈 
[Link to dashboard](https://staging.onenr.io/04ERP3GBDwW) see the charts with _WIP_
<img width="1278" alt="Screen Shot 2021-11-29 at 4 14 02 PM" src="https://user-images.githubusercontent.com/1395158/143957559-df882d2c-9ad5-45a8-9a61-1e11dc3afc02.png">

### Acceptance Criteria 

- [ ] Setup a custom viz to get the count of the last step.  so we can see the total `Sign Ups` for a given time frame.
- [ ] BONUS: show this same data it in a TIMESERIES chart.

**Comment by zstix** [comment]
I'm going to plug away at this as an innovation project.

**Comment by zstix** [comment]
I've created a [custom visualization](https://github.com/zstix/nr1-funnel-aggregate/) to achieve the desired effect:

![Screen Shot 2021-12-01 at 16 51 06](https://user-images.githubusercontent.com/1946433/144339551-0c51a37e-8d6c-46db-96bb-9b13d2de60fd.png)

Before marking this as done, I'd like to do the following:
* [ ] Review the code with the team
* [ ] Transfer repository over to New Relic Experimental organization
* [ ] Publish details to the Catalog (including a link back to the repository and screenshots)
