### ISSUE TITLE
[Public Catalog] Crazy egg running multiple userscripts

### ISSUE THREAD

**Issue by tabathadelane** [newrelic/developer-website#1927]
We are seeing an error when loading the crazy egg script on production. We should look into this and resolve it.

```
Uncaught Error: CE: multiple userscripts installed
    <anonymous> https://script.crazyegg.com/pages/scripts/0045/9836.js:1
```

### Additional context

- This script is set in the[ DevSiteSEO.js](https://github.com/newrelic/developer-website/blob/e48402439de8bb3c0c9f94f0ce3d07dd2cf7fc9e/src/components/DevSiteSeo.js#L27) component.

- This issue was originally a part of [this ticket](https://github.com/newrelic/developer-website/issues/1896#issuecomment-982162882).

- According to the Crazygg docs, they suppress multiple scripts from running, so it will not interfere with our data collection. 

### Acceptance Criteria

- [ ] Determine the cause and remove the error.

**Comment by jpvajda** [comment]
smells like sustaining to me. so I added it our upcoming sustainment epic. 🧀
