### ISSUE TITLE
create a vanity URL aka mask aka URL

### ISSUE THREAD

**Issue by legnaleama** [newrelic/developer-website#1932]
### Create vanity URL for public I/O

Given the high cost of migrating the current public I/O experience outside of developer.newrelic I've been discussing with the Growth team if it would be possible to create a vanity URL aka mask aka URL alias for `developer.newrelic.com/instant-observability` to make it accessible from `newrelic.com/instant-observability `as a first step towards that migration.

### Describe why this important to you
The main benefit of that is that it would allow us to work in growth initiatives like backlink generation to generate traffic and stronger paid campaigns while we plan the real migration in parallel. 

### Conclusions
This is just a proposal to try and find middle ground between each team's requirements to achieve objectives. Happy to discuss alternatives.

@jpvajda @polfliet

**Comment by jpvajda** [comment]
@legnaleama thanks for reporting this, we are actually discussing do the full site migration in Q4 now, and this sounds like an alternative approach we could take, I've asked Andy Ramirez his thoughts on this. However it does seems like we are just going to prioritize the migration of the site to the newrelic.com domain in Q4, and we'll have that decision very soon.

**Comment by jpvajda** [comment]
I spoke to Andy and he said: 

We want to mask the current site so it lives at  `newrelic.com/instant-observability/, but stays on thh current tech stack, design, etc. But to Google and users it effectively has moved, so the old site/pages need to be 301 redirected to their respective locations at the new domain. T

At the end of the day the URLs for the site have to be `newrelic.com/instant-observability/foo`.. and any request for it at developers. would be redirected accordingly.
