### ISSUE TITLE
[Dashboards] funnel dashboards should track new user data, not just existing users `part 2`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1937]
Relates to https://github.com/newrelic/developer-website/issues/1913

In our work to build the `BIG FUNNEL` ™️   We were able to correlate _some_ information, but it's only from existing users. This is because we have a `customer_user_id` attribute that we can correlate across all events:

```sql
FROM TessenAction
SELECT
funnel(customer_user_id as 'user',
  WHERE eventName = 'TDEV_QuickstartInstall_instantObservability' as 'Public catalog install click',
  WHERE eventName = 'DEVEX_New Relic IO_initialLoad' as 'Visit New Relic I/O', 
  WHERE eventName = 'DEVEX_New Relic IO_listingClicked' as 'View details', 
  WHERE eventName = 'DEVEN_Quickstart Details_clickInstall' as 'Click install', 
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewQuickstartInstallationUI' as 'Load install',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_viewInstallStep' as 'View install step',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_deployQuickstartComponents' as 'Deploy components',
  WHERE eventName = 'INSTALL_QuickstartInstallationPlan_clickSeeYourData' as 'See data'
)
WHERE email NOT LIKE '%@newrelic.com' SINCE 1 week AGO LIMIT MAX
```
### Issue 

If the events in the product had an `anonymousId` or the events in the public catalog had a `sessionId` then we could get the data for _all_ users. At the moment, we don't have a unique unifying identifier to follow a user through all of these separate events

### Acceptance Criteria 

- [x] Review the PR that includes changes to the Quickstart Details Nerdlet owned by `DevEn`
    - https://source.datanerd.us/developer-enablement/catalog-pack-details/pull/76
- [x] Submit a PR to the [marketplace repo](https://source.datanerd.us/nr1-dev-experience/marketplace) the change to add the `anonymousID` to the follow events `DEVEX_New Relic IO_initialLoad` & `DEVEX_New Relic IO_listingClicked`. 
       - https://source.datanerd.us/nr1-dev-experience/marketplace/pull/140
- [x] Submit a PR to Virtuoso's open install service to add anonymousId to all events
    - https://source.datanerd.us/open-source/nr1-install-newrelic/pull/584

**Comment by jpvajda** [comment]
Why is this blocked still @rudouglas ?

**Comment by rudouglas** [comment]
I just hadn't closed it and opened `The return of the Dashboards`/ `The Good the Bad and the NRQL`/ `Die Hard with a Funnel`
