### ISSUE TITLE
Research Gatsby Cloud environment variables

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1955]
### AC

- [x] Report this issue to Gatsby.

_My team is trying out gatsby 4 and the getServerData function with the new ssr stuff. we found that unless we prepend our env vars in gatsby cloud with 'gatsby' they don't work. we weren't expecting this because we figured it was only the ssr side that needed the env var, not the browser. 2 questions:_

-  [x] Confirm questions 
1: is this expected?
> Gastby doesn't yet support this

2: is it secure to have an api key in a gatsby prepended env var? when i read that the browser has access to it it worries me a little
> No it's not

- [x] Determine when this feature will be available

> I've got confirmation from the Gatsby framework team that this is scheduled for January and should be complete before Feb 1.

### Impacts
 
- Without this feature we'd be exposing our API Key in the public, which we don't want to do. So this will prevent us from completing our epic to integrate with the catalog service for sort functionality. 

- This is also blocking our I/O Home page design work, as we now have to consider if we should do those changes seperate from our SSR branch of code, and essentially have to duplicate our changes as we'd have do that design work in both branch of our code.

**Comment by jpvajda** [comment]
Relates to  https://support.gatsbyjs.com/hc/en-us/requests/21296

**Comment by jpvajda** [comment]
We decided to close this out as it's in Gatsby's hands to resolve, the above issue is linked to track it.

**Comment by jpvajda** [comment]
Keeping open until we get a confirmation of when this will be resolved.

**Comment by jpvajda** [comment]
We got our answers, ETA is Feb 1st according to Gatsby.
