### ISSUE TITLE
[Public Catalog] New quickstarts are not appearing on the i/o site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1956]
Relates to PR https://github.com/newrelic/newrelic-quickstarts/pull/642

A hero request to add new notification quickstarts has shown that we aren't updating the quickstarts on the developer site but they are being updated perfectly fine on staging and production for the internal I/O Catalog

### Acceptance Criteria

- [x] Determine why the site is not being updated
- [x] Update site so all new quickstarts appear

**Comment by rudouglas** [comment]
Ok i've figured out the issue here, some of the Quickstarts are failing the build. Slack is the first one. The code is looking for a documentation or install plan entry  when trying to create the install button, i'll try to fix that now

**Comment by rudouglas** [comment]
@jpvajda  Ok so the last consideration here is that without a documentation entry there will be no `See documentation`  button on the quickstart in the public catalog and in Product, so the user will have to click the link in the description to get there, which may not be ideal? It looks like this in the catalog

<img width="1183" alt="Screenshot 2021-12-17 at 13 12 54" src="https://user-images.githubusercontent.com/17122543/146552309-3aa5a898-0ae0-4605-994f-7940aa0a423f.png">
