### ISSUE TITLE
[Public Catalog] I/O Mobile changes

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1964]
`NOTE:` Please branch off `feature/io-redesign`

<details>
<summary>Mockup</summary>
<img width="359" alt="Screen Shot 2021-12-17 at 11 42 15 AM" src="https://user-images.githubusercontent.com/1395158/146592645-c697d96b-1ae7-4282-b71e-c826b6d9dee7.png">
</details>

### Acceptance Criteria

- [x] Only show list view tiles  
- [x] Make CSS changes to display tiles based on design

**Filter by Category**
<details>
<summary>Mockup</summary>
<img width="305" alt="Screen Shot 2021-12-17 at 11 44 48 AM" src="https://user-images.githubusercontent.com/1395158/146593379-fb8b12f7-281d-45e1-a4da-bccbab68718d.png">
</details>

- [x] display `Filter by` Category 
- [x] on click of`Filter by` Category allow a uses to select a category for filtering quickstarts.
- [x] when selecting a category the category filter is applied and the model closes. 
- [x] Show the count on the categories
- [x] Cancel button closes menu and does not update filter state

**Sort by**

🛑 
> can't be done until we finish the sort improvements epic and integrate with the catalog service, so this should be broken out into another ticket for a future enhancement. 

<details>
<summary>Mockup</summary>
<img width="336" alt="Screen Shot 2021-12-17 at 11 47 33 AM" src="https://user-images.githubusercontent.com/1395158/146593414-fc31ee65-9053-4a9c-828c-014999730d20.png">
</details>

- [ ] display `Sort by` selector
- [ ] on click of`sort by` allow a user to select a sort filter  for filtering quickstarts.
- [ ] when selecting a sort by value the sort filter is applied and the model closes. 
- [ ] Cancel button closes menu and does not update filter state (it's say okay, but that's not the label to use)

### Useful Links:

[UI-Writing content](https://newrelic.atlassian.net/browse/UIWRITE-1468)
[figma](https://www.figma.com/file/QmQCsuejNht62ymzQuvpYe/the-new-I%2FO-(public)?node-id=556%3A16022)

**Comment by jpvajda** [comment]
@legnaleama  can you confirm all the acceptance criteria meets the design need?

**Comment by zstix** [comment]
It's worth noting that we don't have access to sorting by relevance and popularity _until_ we sort out SSR.

**Comment by jpvajda** [comment]
I spoke to @legnaleama about our questions on the results button on the category model, he agreed with our approach defined in the AC and update the FIGMA design.

**Comment by legnaleama** [comment]
The only thing I'd change (if technically possible) is adding back the count on the categories given we are moving to a single click action. @jpvajda
