### ISSUE TITLE
quickstart installation issue

### ISSUE THREAD

**Issue by pullatechie582** [newrelic/developer-website#1986]
### Error

_55fb519cee5b8150ebdc4fa4ab081c844df3NRAL Installing the New Relic ECS integration... Detected EC2 launch type (default). Checking required tools. Downloading task definition file task_definition_file from: https://download.newrelic.com/infrastructure_agent/integrations/ecs/newrelic-infra-ecs-ec2-latest.json Checking if license key parameter exists in the AWS parameter store. License key parameter not found. Creating... An error occurred (ValidationException) when calling the PutParameter operation: Parameter name must be a fully qualified name. Error: couldn't create license key parameter_

**Comment by pullatechie582** [comment]
How can i resolve this issue ?

**Comment by jpvajda** [comment]
@pullatechie582 this opensource repository doesn't support the installation process of each quickstart, but I can pass this issue onto a team that can look into this.
