### ISSUE TITLE
[Public Catalog] I/O Category selection auto-scrolls on search input & category select

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/developer-website#1988]
### Description:

The current behavior of the site is to jump to the top of the page when a new query parameter (`search` or `category`) is added to the URL. In other words, once a category or search input is added to filter down the Quickstarts, it scrolls back to the top of the page. With the new addition of the I/O Banner, the UX appears abrupt, cutting off the results of the quickstarts.

### Steps to reproduce:

- Go to a p[review build ](https://build-7e4f3953-985f-4165-a445-558a43f05be5.gtsb.io/instant-observability/)
- Navigate to I/O page
- scroll down the list of quickstarts
- select a category to filter down the results
- page will jump to the  top of page, above the I/O Banner which is very bad UX.

### Expected behavior (possible solutions)

1) When a new query parameter is added, allow the page to have a smooth behavior when scrolling to the top of the page
2) Have the page scroll to the bottom of the I/O banner to reduce abrupt change

> We will go with this temporary approach so we can go live with the new home page
3) leave the user where they are on the page and don't scroll. 

### Acceptance Criteria 

- [ ] leave the user where they are on the page and don't scroll. 

blocked by https://github.com/newrelic/developer-website/issues/1961

**Comment by jpvajda** [comment]
I've reached out to @@legnaleama in slack...

**Comment by jpvajda** [comment]
In order to unblock this release we opted to go with option 3️⃣ 

> leave the user where they are on the page and don't scroll. 

@josephgregoryii back to you for implementation. 👋

**Comment by jpvajda** [comment]
@josephgregoryii also if you can put an estimate on this, that be great.

**Comment by legnaleama** [comment]
👋 hello! The ideal behaviour would be:

**WHERE**
Top of the page
OR
Half way through the scroll (passed the above the fold)

**WHEN**
User clicks on a category…

**DO**
Smooth scroll to the top of the results section AKA after the jumbo banner (img. attached) and load new content.
[Example of a similar navigation](https://asana.com/es/apps?category=marketing-y-dise%C3%B1o)

![image](https://user-images.githubusercontent.com/3636549/148754396-472e30c8-359a-4b09-9f1e-44d87715c5e7.png)
