### ISSUE TITLE
[New I/O Site] Create github repository with default gatsby site

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#2000]
## Description
This should include branch protection for `main` (this repo will not use a `develop` branch), adding the team as contributors, an initial readme, and the default site created by the gatsby cli.

## Helpful information
* Reach out to @jbeveland27 or @melissaklein24 to create the repository and add the gatsby cloud integration (@jpvajda as backup)
* [New relic community categories](https://opensource.newrelic.com/oss-category/), we'll want to make this a Community project

## AC
- [x] A new repository exists under the `newrelic` org, called `instant-observability-website`
- [x] The repo includes gatsby cloud integration (added by @jbeveland27 or @melissaklein24)
- [x] The `main` branch requires at least 1 approval to merge
- [x] The repository contains the default site created by `gatsby create` 
- [x] The repository contains a README with instructions on how to develop and deploy the site
- [x] Make the repository public

**Comment by jpvajda** [comment]
@aswanson-nr will add some details with steps to how we create a repo in the newrelic org.

**Comment by tabathadelane** [comment]
New repo is alive! 🥳 [Instant-Observabilty-Website](https://github.com/newrelic/instant-observability-website)

**Comment by jpvajda** [comment]
🥳

**Comment by tabathadelane** [comment]
PR's mentioned above merged into I/O Repo. 🎉
