### ISSUE TITLE
[New I/O Site] Setup analytics

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#2005]
## Description
Since this is an entirely new site, we will need to configure our various analytic systems. These include Tessen, Segment, and Google Analytics.

### Tessen fields
- Product: `IO`
- Subproduct: `TIO`
- segmentWriteKey: use existing devsite key

## AC
- [x] Tessen is configured (segment comes for free) with a new `product` value 
- [x] Tessen is configured with a new `subproduct` value of `TIO` (following our convention of "T"-"site name")
- [x] Tessen is configured with the existing devsite `segmentWriteKey` 
- [x] Crazy Egg 🥚scripts on I/O home and catalog details pages continue to work
- [x] New Relic dashboard queries are updated to include the new `product` and `subproduct` fields
  - [x] [I/O program dashboard](https://staging.onenr.io/0VKQXV7qLRa)
  - [x] [DevEn external I/O dashboard](https://staging.onenr.io/0mMRNy5Lqwn)
- [ ] Zoe is notified to go update the GA filters

**Comment by jpvajda** [comment]
Needs an event wiki AC. @aswanson-nr

**Comment by jpvajda** [comment]
Include more details that we want to include data from both the old and new application @aswanson-nr

**Comment by josephgregoryii** [comment]
Update:
All tasks are done except for changing the subproduct for [DevEn external I/O dashboard](https://staging.onenr.io/0mMRNy5Lqwn) and notifying Zoe
