### ISSUE TITLE
[New I/O Site] Setup alerting/monitoring

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#2006]
## Description
Since this is a new site, we will need to setup the standard alerting and monitoring we use on the other sites. This includes alerting on Javascript errors, alerting on synthetic failures, troubleshooting dashboards, and an emergency runbook.

## AC
- [x] The `newrelic` section of the `gatsby-config.js` file has been updated with a new `applicationID`
- [x] The site reports into NR1 and is viewable as a Browser application
- [x] There is a synthetic check making sure the catalog is up and running
- [x] There is a synthetic check making sure the detail view is up and running
- [x] There are alert policies setup to trigger when the synthetic checks fail
- [x] There are alert policies setup to trigger on a high volume of Javascript errors (see the alerting for docs/dev)
- [x] All alerts send PagerDuty notifications (make a follow-up ticket)
- [x] There is a dashboard that tracks Javascript errors, 404s, and synthetic checks
- [x] There is a runbook in the repository's wiki that contains information on how to rollback a release and links to:
  - The Browser application in NR1
  - All synthetic checks
  - All alert policies
  - The troubleshooting dashboard
  - A link to the site in Gatsby Cloud

**Comment by zstix** [comment]
This looks great!

I agree with you that, in the future, we should consider configuring this stuff with Terraform
