### ISSUE TITLE
[New I/O Site] Update theme header to point to `newrelic.com/instant-observability`

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#2009]
## Description
We now need to update the theme header to point to `newrelic.com/instant-observability` instead of `developer.newrelic.com/instant-observability`. We should also update any links in the Dev and Docs site.

## AC
- [ ] There is a published version of the theme where the header is updated to point the "Instant Observability" link to `newrelic.com/instant-observability`
- [ ] That version of the theme has been published on the Docs site
- [x] The Docs site has been scrubbed for `developer.newrelic.com/instant-observability` links - `@hero the #documentation`
- [ ] That version of the theme has been published on the Dev site  
- [x] The Dev site has been scrubbed for `developer.newrelic.com/instant-observability` links - `@alexronquillo`

**Comment by clarkmcadoo** [comment]
https://github.com/newrelic/docs-website/pull/6044
https://github.com/newrelic/gatsby-theme-newrelic/pull/634

**Comment by clarkmcadoo** [comment]
Waiting on the site migration/domain swap to get the theme published
