### ISSUE TITLE
[New I/O Site] Create new header components

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#2012]
## Description
To better align with the design of the marketing site (newrelic.com) we will need to implement a new header and footer for the site.
**Final design pending**
* This can be an "transitional" header and doesn’t need to be exactly the same as the marketing site.
* We can make the header and footer components configurable via a json or yaml file, so it’s easy for the website team to PR our repo and update the header if needed. 
* Angel will sync with Heather Rodriguez on our approach as she's the PM of the marketing web team.

### Figma

- [Prototype on the I/O page](https://www.figma.com/proto/QmQCsuejNht62ymzQuvpYe/the-new-I%2FO-(public)?pageid=556%3A16022&node-id=768%3A39148&viewport=466%2C48%2C0.59&scaling=min-zoom&starting-point-node-id=556%3A18876&hotspot-hints=0&hide-ui=1)

- [New version nav component](https://www.figma.com/file/0jsTPLtwz6Bljndkbr1COn/open-source-DS-%5BWIP%5D?node-id=38%3A307)

### Mock up 

![image](https://user-images.githubusercontent.com/1395158/149549165-4c621777-d1d7-4a49-a26d-d6ad9187c4cd.png)

### Acceptance Criteria 

`approach:` the new I/O nav is using the same Nav component, it’s just a theme variant with a few mods that could be extended to the default theme.

- [x] This new header would be stored in the I/O site repo overriding the one from the theme.
- [x] Moving the Dark mode icon to the far right of the nav.
- [x] The login button style has been changed from Outline to Link.
- [x] replace the I/O header search bar with an icon only.

**Comment by jpvajda** [comment]
I've asked @legnaleama if we could have design to look at by monday jan 17

**Comment by polfliet** [comment]
@jpvajda @aswanson-nr @tabathadelane Bill and Manav are asking if we can remove the search icon from the top menu to avoid any confusion and only have the I/O search bar on the page itself. Does that make sense?

**Comment by jpvajda** [comment]
@polfliet We can definitely make that change, but I wanted to share this feedback with @legnaleama as we worked from his final design.

**Comment by tabathadelane** [comment]
@jpvajda while i'm adding the nav links for this header, `Solutions` opens a dropdown on `newrelic.com`. There is no `/solutions` page. Can I get a recommended url for this?

**Comment by jpvajda** [comment]
@tabathadelane to move this along, let's link to `https://newrelic.com/devops` for now, and I'll mention this to @legnaleama
