### ISSUE TITLE
[Public Catalog] Minor `nits` for the latest I/O release

### ISSUE THREAD

**Issue by legnaleama** [newrelic/developer-website#2015]
### Description
I noticed a few discrepancies between the latest shipment of the public I/O and the original designs on Figma. These are just minor adjustments (mainly type sizes) but they affect key components of the page such as the main search input.

@jpvajda 

# Here's the full list of corrections:

## Header
- The font weight on the H1 is being forced to be `bold` when the original definition on the CSS and the one used on Figma is set to `600`. This is should be reversed to 600 because as it stands currently it's breaking consistency with the H1 element and is also breaking the first line of the title before _"integrations"_ which creates a boxy header that becomes harder to read.

![image](https://user-images.githubusercontent.com/3636549/149178014-641cfafc-a9f4-496f-b723-dc2c6eddd04d.png)

## Super Tile
1 - The size of the paragraph inside the super tile is too big, making the whole tile take up too much real state. The original size should be `14/20` instead of `16/24`.

2 - The CTA size is too big. We have 3 sizes for buttons, extra small, small and default, the one used on the design is "small" `12/12` but the one used on the site is "default" `14/14`.
![image](https://user-images.githubusercontent.com/3636549/149178793-9d668831-5566-4db8-93b4-74ebe6580789.png)

## Search box
1 - The helper/placeholder text is too large. It should be `14/14` instead of `18/18`. 

![image](https://user-images.githubusercontent.com/3636549/149177430-91a5d359-a45e-41a6-af3f-96940c1cf93f.png)

2 - The size of the layout icon is too big. The bounding box on Figma is 32 but the actual icon is 24px but the one used on the site is 32px.

![image](https://user-images.githubusercontent.com/3636549/149177657-ccae0738-9317-435f-96ea-20957b9bf0c0.png)

## Tiles
- The height of the paragraph area on the tiles is unnecessary large. This probably comes from the previous iteration but we could just disable the `title-row-height: 0.5fr` on the `paragraph` wrapper and add a `margin-bottom: 0.5em` to the `p` to let the tiles wrap around the content instead of having inconsistent amounts of white space underneath.

https://user-images.githubusercontent.com/3636549/149176203-a2125cae-6d89-435f-b6a7-783db2a3141d.mov

**Comment by zstix** [comment]
Since we're in the process of migrating the site to the .com domain, we're going to hold off on this work until that migration is complete. We'll do the work in the new repository and it should get released with the new site!!!

**Comment by rudouglas** [comment]
Here is the PR for the new I/O site: 
https://github.com/newrelic/instant-observability-website/pull/13

@legnaleama I made the changes to the developer site as well just so you could have a preview of them and sign off:

https://developerwebsitedevelop-runits1.gtsb.io/instant-observability/
