### ISSUE TITLE
Spellng error - should be receive

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/developer-website#2018]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)
_You may have to wait a minute or two for New Relic to **recieve** data from your demo services. Once it's ready, you'll see transaction data, such as performance, throughput, and an Apdex score:_

### Doc information (don't delete this section)

* https://developer.newrelic.com/build-apps/ab-test/demo-setup/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by shhudspethnr1** [comment]
It's just a spelling error (receive is spelled wrong).  I learned I can fix
myself-- so can do in a bit :) Thanks!

**Comment by jpvajda** [comment]
@shhudspethnr1 Got it, thanks for reporting this I took care of it in this PR https://github.com/newrelic/developer-website/pull/2064
