### ISSUE TITLE
[New I/O Site] Expanded footer

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#2020]
As we move the i/o site experience to newrelic.com we want the footer on the i/o catalog page to change to better align with newrelic.com look and feel. As a transitional step, we'll just expand the footer on i/o home.

### Acceptance Criteria

- [x] On i/o home extend the footer backgroundf to the edge of the screen
- [x] footer content is aligned to the rest of the page content.

### Crude mock up 🎨 

<img width="1762" alt="Screen Shot 2022-01-14 at 10 59 38 AM" src="https://user-images.githubusercontent.com/1395158/149564123-69a17457-0403-4ed1-b11f-563b03721871.png">

**Comment by jpvajda** [comment]
@legnaleama - Can you confirm  if this is a true statement: on i/o home extend the footer background to the edge of the screen? We came to this conclusion due to the design of the newrelic.com home page where the footer extends to the edge of the screen.

**Comment by tabathadelane** [comment]
@jpvajda / @legnaleama I have a couple questions about this design. 

We want the footer color to stretch to fill the page width like the header does and then restrict the footer content to align with the page contents, correct?

This is a local build preview.

<img width="1819" alt="Screen Shot 2022-02-01 at 3 24 39 PM" src="https://user-images.githubusercontent.com/47728020/152068445-00e7d8ba-e5e8-407c-9806-d0dc42e35e72.png">

This is the current I/O page on the developer site. Should I be using this I/O icon in that footer or leave it as the New Relic one that is in the theme by default. 

<img width="1495" alt="Screen Shot 2022-02-01 at 3 25 09 PM" src="https://user-images.githubusercontent.com/47728020/152068453-67d495e4-357f-4ebf-b7eb-1f656c972394.png">
