### ISSUE TITLE
Cant find either of the CLI's mentioned in these docs. 

### ISSUE THREAD

**Issue by StingyJack** [newrelic/developer-website#2021]
Where are the newrelic cli or the newrelic one cli?

### Doc information (don't delete this section)

* https://developer.newrelic.com/explore-docs/nr1-cli/
* **OS**: Windows 10
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by StingyJack** [comment]
Found one of them https://github.com/newrelic/newrelic-cli/releases/tag/v0.41.13

**Comment by LizBaker** [comment]
hi @StingyJack, you can download the new relic one cli based on the instructions here: https://developer.newrelic.com/explore-docs/nr1-cli/#installing-the-new-relic-one-cli

**Comment by StingyJack** [comment]
The directions on the page you linked...
![image](https://user-images.githubusercontent.com/15381181/150192999-edb8d74e-3e0b-4d95-9dc2-bebbb77e700e.png)

Following the directions there and clicking on Apps takes me to this screen
![image](https://user-images.githubusercontent.com/15381181/150192456-02d244fa-45ad-41e9-a306-80cf5be05dd8.png)

There is no newrelicone CLI to download there. There is a note at the bottom saying the contents of the catalog have moved to NewRelic Instant Observability. I clicked on the button to view the relocated content, but there is no newrelicone CLI to download there either. Searching for "build your own" returns three results. None of which match the instruction. 
![image](https://user-images.githubusercontent.com/15381181/150192936-bceef49d-383a-41f9-b667-dc8da4624d5a.png)

**Comment by LizBaker** [comment]
ah yep, sorry about that @StingyJack. in the instant observability view you can filter to apps on the left and it will show up as the first tile. i'll get the doc updated. it does actually link to the developer center from the doc (https://one.newrelic.com/launcher/developer-center.launcher) but it's worth updating regardless!
