### ISSUE TITLE
Video quality is too bad to see anything on screen

### ISSUE THREAD

**Issue by sumitkgaur** [newrelic/developer-website#2022]
Using Terragrunt to Manage Multiple Environments Video is useless as quality is too bad. 

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://developer.newrelic.com/terraform/terragrunt-configuration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jpvajda** [comment]
@mehreentahir16 @alexronquillo  I just wanted to point this content request out to you all. Thanks!

**Comment by alexronquillo** [comment]
@jpvajda @jaesius I think this might be a design question. The video is certainly useless if watched in the little video player. When full screen, I didn't find any issues with it. So I think we need to decide how best to use these videos in the content. The video doesn't scroll with the content, so it seems like it's intended to be watched full screen before the reader reads the guide.

**Comment by jpvajda** [comment]
@alexronquillo 👋  @roadlittledawn is now the PM of our Gatsby Sites. Our teams are actually splitting up in Q1, and he will be focused on supporting the developer site, docs site(s), gatsby theme, and the OSS site as part of Docs Engineering. So I just added him to this ticket for awareness.
