### ISSUE TITLE
Header link redirecting to wrong url

### ISSUE THREAD

**Issue by jcountsNR** [newrelic/developer-website#2029]
Just noting that the Instant Observability link navigates to the Developer page if I'm already browsing I/O catalog.
Steps:

1. Use header to navigate to Instant Observability
2. (optional) Open any quickstart
3. use the header to navigate back to the Instant Observability catalog

Expected: Land on [I/O catalog page](https://developer.newrelic.com/instant-observability/)

Actual: Land on [Developer page](https://developer.newrelic.com/)

### Doc information (don't delete this section)

* https://developer.newrelic.com/instant-observability/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by jpvajda** [comment]
@jcountsNR thanks for reporting this! We are point this  directly to https://newrelic.com/instant-observability/ now. that we moved the site.
