### ISSUE TITLE
NPM Instruqt lab is missing steps

### ISSUE THREAD

**Issue by nr-jbiggley** [newrelic/developer-website#2038]
## How can we make our docs better?

The 2nd outcome in the Instruqt module is missing 2 commands. This breaks the remainder of the lab.

```
docker swarm init
docker network create -d overlay --subnet=10.10.0.0/24 --attachable testnet

```

### Doc information (don't delete this section)

* https://developer.newrelic.com/collect-data/network-performance-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jpvajda** [comment]
@alexronquillo or @mehreentahir16 would this be something you could look at?

**Comment by ASchneider-GitHub** [comment]
Just as a general note, this is preventing the NPM Udemy Learning Track from functioning. Once this has been resolved, the learning track will be made available to GTS

**Comment by alexronquillo** [comment]
I'll look at this now.

**Comment by alexronquillo** [comment]
It looks like the lab has a bigger problem. The two lines you mention, @nr-jbiggley, are in the [packer setup for the lab](https://github.com/newrelic-experimental/network-performance-monitoring-instruqt-packer/blob/de5cd6cfcfb400d9dab83d475aa5aa740020b4c0/scripts/setup-docker.sh#L5). It seems like something's broken with the image.

**Comment by alexronquillo** [comment]
Ok, I fixed it and the fix worked for me. Would you mind trying? @nr-jbiggley
