### ISSUE TITLE
[I/O Site] Get splat redirects working for dev site IO

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#2056]
@jpvajda commented on [Thu Feb 10 2022](https://github.com/newrelic/instant-observability-website/issues/25)

## Summary
As part of the I/O site migration to newrelic.com, we needed to create redirects so any URLs pointing to `developer.newrelic.com/instant-observability/<rest of path>` would make it to their new spot at `newrelic.com/instant-observability/<rest of path>`. Currently, this is done by creating a redirect for the catalog itself and for each quickstart details page. While this approach does get us where we need to be, it requires the developer site to maintain references to the various quickstart names and ids for the creation of the redirects. We would prefer this not to be the case since the rest of the I/O related code has been migrated to the new site. 

### Possible solution
Splat/star/wildcard redirects, ex: `instant-observability/*` would match anything with the `instant-observability/` prefix. Gatsby has a [great article](https://support.gatsbyjs.com/hc/en-us/articles/1500003051241-Working-with-Redirects) on how to work with redirects, including "splat" patterns.

### Helpful information
- @nr-kkenney made an attempt at getting "splat" redirects working, but ran into issues. The starting point with this ticket is most likely restarting this conversation with Gatsby support.
- [Dev site redirect creation](https://github.com/newrelic/developer-website/blob/develop/gatsby-node.js#L33-L55)
  - The source for the data used to create those redirects is [quickstarts.json](https://github.com/newrelic/developer-website/blob/develop/src/data/quickstarts.json) and loaded in by these [gatsby plugins](https://github.com/newrelic/developer-website/blob/develop/gatsby-config.js#L170-L186)

**Comment by aswanson-nr** [comment]
Okay we got updates.
The splat redirects work perfectly when in a production deployment. We were seeing issues because we were looking at PR previews on the `gtsb.io` domain, which is different than the deployments on `gatsbyjs.io`. This is mainly do to `gtsb.io` being an older domain and not having some of the same features, this will eventually be resolved when Gatsby migrates away from using that infrastructure.

Next steps: 
1. Clean up my splat testing pr, #2062.
2. Merge to `develop`
3. Test that the redirects are working as intended
4. Merge to `main` and deploy

**Comment by nr-kkenney** [comment]
did they recently make changes for this? i originally tested this particular avenue by creating a new site in developer with my feature branch, and it did not work then either (at the time).

**Comment by aswanson-nr** [comment]
My understanding is that there have been no recent changes to this, but I didn't explicitly ask. 
If people wanna see it in action [https://developerwebsitetestsplatredir.gatsbyjs.io/instant-observability/dotnet/2dff13b6-0fac-43a6-abc6-57f0a3299639/](https://developerwebsitetestsplatredir.gatsbyjs.io/instant-observability/dotnet/2dff13b6-0fac-43a6-abc6-57f0a3299639/)
