### ISSUE TITLE
Terraform CLI link broken

### ISSUE THREAD

**Issue by rajumkc** [newrelic/developer-website#2057]
## How can we make our docs better?

CLI link in the page is broken . https://www.terraform.io/intro/getting-started/install.html

### Doc information (don't delete this section)

* https://developer.newrelic.com/automate-workflows/get-started-terraform/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jpvajda** [comment]
@rajumkc thanks for reporting this, I fixed it in the attached PR.
