### ISSUE TITLE
Method NewRelic.addCustomParameter not appear

### ISSUE THREAD

**Issue by Waguynho** [newrelic/developer-website#2059]
I am using newRelic IOS SDK 7.3.4 from https://github.com/newrelic/newrelic-ios-sdk.
But I did not find the method _NewRelic.addCustomParameter("userid", userId)_ listed in this documentation https://developer.newrelic.com/collect-data/custom-attributes/.

**Comment by jpvajda** [comment]
@Waguynho 👋 Are you seeing this on a particular page on our developer site? This project is specifically for https://developer.newrelic.com/ so I wanted to ask if you could provide my clarification

**Comment by Waguynho** [comment]
Hi @jpvajda , My question is about the documentation in link https://developer.newrelic.com/collect-data/custom-attributes/
The line code (NewRelic.addCustomParameter("userid", userId);) on version SDK there's is not there when a call post import NewRelic.
But now seems the commnd is other: 
NewRelic.setAttribute(attribute.name, value: attribute.value)

**Comment by jpvajda** [comment]
@Waguynho Thanks you for clarifying, This guide is actually written specifically about the Java Agent so it may be slightly different for our iOS agent, here is some additional documentation you can reference

https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/collect-custom-attributes/#collecting_mobile

https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/set-attribute
