### ISSUE TITLE
Please remove the reference to the Istio Adapter

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/developer-website#2108]
New Relic has archived the Istio Adapter repo (https://github.com/newrelic/newrelic-istio-adapter), so I think you should remove the link to this from this page on your site: https://github.com/newrelic/developer-website/blob/develop/src/markdown-pages/collect-data/collect-data-from-any-source.mdx

**Comment by lazyplatypus** [comment]
I agree- we should link instead to the [istio quickstart](https://newrelic.com/instant-observability/istio-service/cced731a-c027-4e19-ba77-474311bf43d2) ([blog](https://newrelic.com/blog/how-to-relic/monitoring-istio-service-mesh))
