### ISSUE TITLE
Custom Visualization - Platform State for Filters

### ISSUE THREAD

**Issue by mark-studer** [newrelic/developer-website#2119]
When building custom visualizations I want my visualizations to be able to be filtered at the dashboard level similar to the built in visualizations. So if you have a facet that has filtering capabilities or you use the filtering function at the top of the dashboard it should effect the custom visualization.

In the Platform API’s you have a PlatformStateContext ([https://developer.newrelic.com/components/platform-state-context 4](https://developer.newrelic.com/components/platform-state-context)). This provides the time range adjustments made to the dashboard, but doesn’t have any properties on it for filtering. How do you get the filtering information so your custom visualization can be updated similar to how we can update based on time changes?  I have to assume this doesn't exist and would like to request that the information be added to the PlatformStateContext so it can be used to filter custom widgets.

This question / Request was originally submitted here: https://discuss.newrelic.com/t/custom-visualization-platform-state-for-filters/177752 and was redirected by the NR Community Manager to post on Github.

**Comment by Kav91** [comment]
Hi @mark-studer both PlatformStateContext and Nerdlet State APIs work the same way for custom visualizations.
It is just difficult to test when locally serving a custom visualization as the time picker component is not exposed, which means you would have to deploy and add it to a dashboard first.

To shortcut you some effort, I'll share some snippets from the status widget visualization I've added to the public catalog.
Obviously you do not have to implement it exactly the way I have, so do what works for your use case.
https://github.com/newrelic/nr1-status-widgets/blob/main/visualizations/nrql-status-widget/index.js
https://github.com/newrelic/nr1-status-widgets/blob/main/visualizations/nrql-status-widget/status-widget.js#L36

**Comment by rudouglas** [comment]
Hi @mark-studer, to pick up the Dashboard Filters you will need to use the [NerdletStateContext](https://developer.newrelic.com/components/nerdlet-state-context) API to consume it.

Example code:
```
<NerdletStateContext.Consumer>
        {(nerdletState) => {
          const { filters } = nerdletState;

          const queryWithFilters = `${query}${
            filters ? ` WHERE ${filters}` :  ""
          }`;
...
```

You can also apply filters from the Custom Viz using the [nerdlet.setUrlState()](https://developer.newrelic.com/apis/nerdlet) function:

```
// Use nerdletState consumed from NerdletStateContext like above
nerdletState.filters = filters
      ? `${filters} AND ${attribute} = '${filterValue}'`
      : `${attribute} = '${filterValue}'`;

return nerdlet.setUrlState(nerdletState);
```

**Comment by mark-studer** [comment]
Excellent, thanks for the updates.  I haven't had a chance to test this out, but sounds like that should do the trick.
