### ISSUE TITLE
Change repo branch  from "master" to main

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#302]
### Description 

To coincide with the industry trend to remove the term master from technology we should rename our github master branch to main. 

**Likely steps:**
1. Communicate with devs and docs folks about the change to using the main branch and intended timing of the switch.
2. Merge latest from master into main (main branch was already created along and an corresponding amplify branch build)
3. Get all open PRs to point to main
4. Update amplify to point developer.newrelic.com to main.
<img width="1572" alt="Screen Shot 2020-07-01 at 10 54 18 AM" src="https://user-images.githubusercontent.com/3023056/86277360-6a826480-bb8b-11ea-93f3-89a795d99afe.png">
5. Delete the master branch from the repo
6. Communicate with devs and docs folks to confirm the change is in place.

**Comment by zstix** [comment]
Work done to complete this ticket:
* Updated GitHub settings
* Updated GitHub Actions (linked PR)
* Updated `amplify.yml` (linked PR)
* Added new `main` branch
* Notified internal stakeholders

We will need to further review settings in Amplify at a later date to ensure everything is working smoothly.
