### ISSUE TITLE
Set up dashboards / Review alerts dashboard

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#308]
### Description 
Once we have the agent installed, and have our SLIs defined, we should create some NR dashboards to help us monitor the success of the developer site. We will need one dashboard for troubleshooting (mapped to our alert policies) and another dashboard for the overall success (mapped to our SLIs).

As a reminder, here are the DevEx OKRs that are relevant to the developer site:
* 20% increase in usage in page views (6,300 page views currently)
* \>25% bounce rate (57% currently)
* Number of CLI downloads hits 200 for the year
* 2 other NR teams and 5 non-NR individuals contributing

### Acceptance Criteria: 
* Dev Site success dashboard created based on previously defined SLIs
* Review trouble shooting dashboard made in previous MMF
* Troubleshooting dashboard is linked in runbooks

**Comment by honeyd** [comment]
More comments are here: https://newrelic.atlassian.net/browse/DEVEX-1043
