### ISSUE TITLE
[Open source checklist] Add Explorers Hub support link to readme

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#309]
### Description

As called for in the open source checklist, we need to add a specific explorer's hub link to the repo's readme.

###  AC
1. create a topic on the explorer's hub for the Developer Site, similar to how the [OSS Site has done it](https://discuss.newrelic.com/t/opensource-newrelic-com/104943)
2. Add this link to the site readme under community, similar to how the [OSS Site has done it](https://github.com/newrelic/opensource-website#community)

**Comment by jpvajda** [comment]
I'll take this one to sort out a few things we need to do to be consistent with the OSS Site.
