### ISSUE TITLE
Create a Build your Environment getting started guide

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#313]
### Description 
Michelle was going to put something together such as: https://www.gatsbyjs.org/tutorial/part-zero/

To help a new developer get up and running with their dev environment. 

#### Env setup and getting started guide ideas
1. install Node.js
2. manage multiple versions of node.js with nvm 
3. install all React dependencies 
4. install CLI 
5. install any other New Relic dependencies
6. Accessing Repos

**Comment by mmfred** [comment]
I've started this page. I need to add steps 1-3 to it. I have that on my to-dos right now. https://developer.newrelic.com/build-apps/set-up-dev-env

**Comment by mmfred** [comment]
Hey @caylahamann and @jpvajda - this is the Setting up your development environment page that we discussed: https://developer.newrelic.com/build-apps/set-up-dev-env

**Comment by jpvajda** [comment]
@mmfred I have some suggestions... but I'll slack you my questions to clarify a few things. thank you!

**Comment by caylahamann** [comment]
@mmfred is this done? also can I make a minor suggestion! In the intro paragraph where it says: `The New Relic One command line interface (CLI)` can we link to the CLI download? I know we do it later in the doc, but my instinct was to click it right when I first read it in the intro to learn more :)

**Comment by mmfred** [comment]
This is now done. I linked to the CLI as Cayla requested, and added a section on forking the repo (and removed duplicate info about editing files) that John had requested.
