### ISSUE TITLE
[Site Walkthrough] Replace stock photos on the Developer champion page

### ISSUE THREAD

**Issue by LizBaker** [newrelic/developer-website#319]
Ask Haney if we have any stock photos we can use to replace the grainy photos on the developer champion page.

**Comment by djsauble** [comment]
Stock photos:

* https://www.dropbox.com/sh/bbjrt9p0so8o9rg/AAChGtX9vvmumIJrCf0TK6oTa?dl=0
* https://www.dropbox.com/sh/1gsmilthj4u7kbk/AACVc0o4QWIF6DV9o0W11jS2a?dl=0
* https://www.dropbox.com/sh/e6czbxmd0trksb1/AAD3jEz-xxgiPixTL3oin2Pja?dl=0

**Comment by djsauble** [comment]
https://github.com/newrelic/developer-website/pull/393
