### ISSUE TITLE
Simplify the number of options presented to the user when opening a bug/issue

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#325]
### Description 
Very meta! When the user clicks "Clear an issue" they are taken to a screen with four options. It's not clear which one to use. Let's simplify this to be something like...
* Open a bug 
* Request something new 

### Acceptance Criteria
The issue types should be 
* Bug Report 
* Enhancement Request
* Documentation Request

**Comment by jpvajda** [comment]
I'll take this one.

**Comment by jpvajda** [comment]
After closely reviewing the different issue types i'd like to continue to provide a way to allow a user to make a documentation request as that template ask them a really different set of questions that will aid us in creating the documentation.
