### ISSUE TITLE
[stretch] Make a component to standardize image sizes for guides

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#328]
### Description 
I think we should standardize on the image size and then build a component for that eventually.

**Comment by mmfred** [comment]
These are the screenshot guidelines from the docs style guide:

Screenshots
Follow the New Relic Security guidelines to capture screenshots or other images. In addition:

Always crop or mask sensitive information.
Avoid annotating screenshots with text boxes, arrows, circles, etc.
Save the width at approximately 1200 to 1400 pixels.
Consider adding a caption.

**Comment by caylahamann** [comment]
@mmfred We can set the width to be standardized and we could add an optional caption property to the component, but I don't think we can ensure (from our end) that we're always cropping or mask sensitive information or that they don't have text boxes or arrows. I assume that's more on the documentation side. 

@djsauble would we want to have a caption property on images? and do you have any opinions on what that would look like?

**Comment by djsauble** [comment]
@caylahamann I'd be happy to settle with using the `alt` attribute for properties for now, just so screen readers can deal with images.
