### ISSUE TITLE
[stretch] Research adding a feedback widget to the DevSite

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#329]
### User Story 
As a user I would like to submit to New Relic if a docs page met my needs by using a simple feedback form that is available on each page.

### Acceptance Criteria 
* We need to define where this form data goes 
* We need a design for it 
* Can we reuse the one used in NR1?

**Comment by jpvajda** [comment]
We discovered that the core service used for feedback collection in the Nr1 platform isn't available to use outside of the platform at this time. So Let's hold on this.  Perhaps we cross this bridge later when the Core Docs site migrates to Gatsby as they do have a feedback widget on the existing site, and may need something to replace that, which we can then leverage.

**Comment by jpvajda** [comment]
marking as done since this is a research spike not implementation work.
