### ISSUE TITLE
The sidenav does not stay expanded on page refresh

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/developer-website#340]
### Description
When navigating the site, the sidenav expands/collapses the sections as you expect when visiting pages within a section. However, if you visit a page, then refresh, you'll notice the sidebar expands every section and does not highlight the current page you are on. 

### Steps to reproduce
1. Navigate to any page except the home page
2. Notice the side nav is collapsed/expanded propertly
3. Refresh the page
4. Notice that all sections have been expanded again and the current page is not properly bolded.

### Expected behavior
Refreshing the page should not matter whether the sidenav is expanded or collapsed.

### Screenshots
**When navigating:**
<img width="1920" alt="Screen Shot 2020-06-29 at 3 15 50 PM" src="https://user-images.githubusercontent.com/565661/86061345-7c44fa00-ba1b-11ea-9cb4-7651a7a4bc42.png">

**After refreshing:**
<img width="1920" alt="Screen Shot 2020-06-29 at 3 15 57 PM" src="https://user-images.githubusercontent.com/565661/86061353-7fd88100-ba1b-11ea-929d-32c09b7a497e.png">

**Comment by LizBaker** [comment]
This has been _mostly_ resolved. Though I have noticed that upon refresh you see the expanded nav blink before showing the correct collapsed/expanded state
