### ISSUE TITLE
top padding tight for code and video on iOS when viewing guides

### ISSUE THREAD

**Issue by mmfred** [newrelic/developer-website#341]
### Description
When viewing videos and code blocks on guides on iOS, the top padding is tight. 
### Steps to reproduce
1. On iOS, go to https://master.dlyi50rq9kt6c.amplifyapp.com/build-apps/build-hello-world-app
2. See the video in the top third of the page, and see the code blocs in there too. In both cases, the padding is tight. Not bad for images though.

### Expected behavior
A little bit more space between text and video or code blocks.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jerelmiller** [comment]
From what I can tell, this seems to be fixed
