### ISSUE TITLE
Change the app icon in the side nav nad Build hello world app to a different logo 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#355]
**User Story**
We want to drive consistency with our design across the DevSite into the NR1 App Catalog by using the same logo for the app catalog view.

**Acceptance Criteria**
-  Obtain the icon image file from Design. 
 - Please change the Build app logo in the side nav to be consistent with the logo used in NR1 App Catalog. 
-  Please change the Build a Hello, World! app logo to be consistent with the logo used in NR1 App Catalog.

**Comment by djsauble** [comment]
https://github.com/newrelic/developer-website/pull/356
