### ISSUE TITLE
The nav menu doesn't open consistently on mobile devices

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#370]
### Description

This is an inconsistent issue where the mobile navigation hamburger menu does not open. Happens infrequently and is resolved with a page refresh.

### Steps to reproduce

1. Go to developer site on a mobile device
2. try to open the navigation using the hamburger menu
3. See results

### Expected behavior

When clicking on the hamburger menu, the navigation opens consistently.

**Comment by jerelmiller** [comment]
@jpvajda Is this still an issue? There have been several improvements to the mobile nav since this issue was opened and I wonder if this has been addressed because of it.

**Comment by jpvajda** [comment]
I tested in an iphone 8, quickly it worked fine. also tested it in Firefox Developer edition a different sizes and it all checked out. we can close it as it was a p4. if it comes up again we can file a new issue.
