### ISSUE TITLE
get started new relic cli / instrument application link goes to a 404 page

### ISSUE THREAD

**Issue by sheilakrishnan** [newrelic/developer-website#381]
### Description
Get 404 from the developer-website https://developer.newrelic.com/404

### Steps to reproduce

1. Go to https://developer.newrelic.com/automate-workflows/get-started-new-relic-cli
2. Click on instrumented application link
3. See error

### Screenshots
![image](https://user-images.githubusercontent.com/7537730/86200033-898fe080-bb10-11ea-8c2e-c325417c7ad1.png)
![image](https://user-images.githubusercontent.com/7537730/86200053-93b1df00-bb10-11ea-9661-ce8f77961de8.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jerelmiller** [comment]
Hey @sheilakrishnan thanks for submitting this! This does indeed look like a bug. It appears that maybe this is supposed to link to docs, but instead links to the dev site.

**Comment by jpvajda** [comment]
I've asked the docs team for insight into where this links needs to go. cc @mmfred

**Comment by mmfred** [comment]
fixed https://github.com/newrelic/developer-website/pull/389
