### ISSUE TITLE
Google Analytics isn't reporting data for the new Dev Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#394]
### Description

After launching the new site, it doesn't look like GA is reporting on site traffic.

### Steps to reproduce

1. Go to or instance of GA: (if you need to view GA,  JV can provide the dashboard link)
2. Look at the reports for site traffic
3. See no data being reported

### Expected behavior

Site traffic is reported correctly in GA.

### Screenshots

<img width="1643" alt="Screen Shot 2020-07-01 at 5 43 24 PM" src="https://user-images.githubusercontent.com/1395158/86301346-e77d0080-bbc2-11ea-834e-b1bc7a285494.png">

<img width="1609" alt="Screen Shot 2020-07-02 at 10 10 54 AM" src="https://user-images.githubusercontent.com/1395158/86384731-61a59780-bc4c-11ea-9f49-ae1db8139a8f.png">

**Comment by jpvajda** [comment]
from my research it seems we may have not configured this plugin 

https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

**Comment by zstix** [comment]
@jpvajda We (and the previous iteration of the site) are using _Google Tag Manager_. We have it configured [here](https://github.com/newrelic/developer-website/blob/master/gatsby-config.js#L56-L61) and it _does_ seem to be adding the tracking code. I'm going to continue to dig into why it's not reporting, but we may need to reach out to someone who has more experience with GTM.

**Comment by nbergseng** [comment]
The previous version also used Tessen, which actually triggers the page view events for GTM via Segment.  You'll need to copy over the Tessen setup from the marketing team.

**Comment by zstix** [comment]
According to the Tessen folks, we can't use Tessen outside of New Relic. I'm going to look into seeing how we can leverage NR Browser for this instead.

**Comment by jpvajda** [comment]
@zstix  are we sure we just didn't use GA site UA Tracking Ids, or site tags in the other dev site? Perhaps that sites code base could tell us what was setup.

**Comment by zstix** [comment]
After further conversation with the Tessen folks, we _can_ use the library, we just need to add the minified bundle to the site ([relevant thread](https://newrelic.slack.com/archives/C118BRVBM/p1593724577153200)). I'm struggling to find a solution for this, due to some constraints with Gatsby.

**Comment by jpvajda** [comment]
@zstix  My thoughts are: implement the GA tracking using the standard gatsby plugin. And then just implement the browser agent plugin that the OSS team built. it seems those 2 things will give us all the data we need. We can even do the browser agent plugin as a sustaining item if it's too much work in this release:

https://github.com/newrelic/gatsby-plugin-newrelic

https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

**Comment by zstix** [comment]
More details on what was set up on the old site (as far as I understand):
* Tessen was being used to track page views
* Google Tag Manager was picking up on the segment information from Tessen
* Google Analytics was reporting the information from Google Tag Manager

If we want to _just_ use Google Analytics, we will need to add the Gatsby plugin _and_ ensure that Google Analytics is configured to _not_ use Google Tag Manager.
