### ISSUE TITLE
We need a landing page for the component library

### ISSUE THREAD

**Issue by tangollama** [newrelic/developer-website#397]
Users need a way to "share" the library. Ideally, making developer.newrelic.com/components a viable landing page that highlights all the categories that are on the left-hand nav would be the right experience.

FTR, I'm happy to PR this. :)

**Comment by jerelmiller** [comment]
Hey @tangollama! We have some work planned this sprint to handle this. We've got another open issue #306 to handle this 🙂

**Comment by tangollama** [comment]
Thanks. Closing.
