### ISSUE TITLE
Formatting issues in build-apps

### ISSUE THREAD

**Issue by honeyd** [newrelic/developer-website#401]
### Description

1. https://developer.newrelic.com/build-apps/build-hello-world-app > the url in step 8 shouldn't have quotes
2. https://developer.newrelic.com/build-apps/add-time-picker-guide > step 4 is formatted like math but it's a path
and on 7 there's ** instead of bold and the pictures aren't correctly cropped
in 3/5 the indentation is wrong

Submitted by @mjesun in #developer-website-refresh

**Comment by jerelmiller** [comment]
2. above is also referenced in #222. Adding that reference here so we can cross-track any progress made on that bug.

**Comment by jerelmiller** [comment]
- [x] Remove quotes from the URL in the hello world guide (#405)
- [x] Fix indentation for code sample in the add time picker guide (#406)
- [ ] Fix path formatting in the add time picker guide
- [ ] Fix bold formatting in tip instead of rendering the literal `**` characters

**Comment by jerelmiller** [comment]
> pictures aren't correctly cropped

@mjesun Can you talk about this a bit more and what you expect to see? Is it that the image files themselves are incorrectly cropped and we need new screenshots, or that the image files are fine and our image rendering is cropping the file unnecessarily?
