### ISSUE TITLE
Integrate DevSite with Segment to allow for cross site metrics for user activity

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#412]
The marketing team's objectives with all DevEx Site properties w/o compromising our standards for the UX will require all DevEx Sites to use Segment to ensure that we have a unified user session experience across properties. To accomplish this, we'll want to integrate with Segment.

Given that Separate GA tags for every property are going to result in fractured data on how users are navigating the properties, we'll have to eventually do this integration.  The OSS team has done this for their site, so we can leverage what they've already done as a starting point.

**Comment by zstix** [comment]
There is a [Gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-segment-js/) for Segment that may help with this work.

**Comment by jpvajda** [comment]
Syncing with @tangollama might be useful as well as he did the implementation for this on the OSS Site

**Comment by jpvajda** [comment]
I found out that @tangollama decided not to use segment, so closing this as won't do.
