### ISSUE TITLE
Component Library Side Nav Item doesn't collaspe consistently and bumps a user to the top of the nav when clicking on a component

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#433]
### Description
When trying to engage with the component library navigation element to open and collapse the component library there are times where it doesn't work correctly.

### Steps to reproduce

1. Go to https://developer.newrelic.com/
2. Click on  the  component library nav element. 
3. you will see it opens correctly but now cannot be be collapsed as expected. 
4. If you click on another nav element outside of the component library nav element, it then collapses. 

**THEN**
1. When clicking on a component, we take the user back to the top of the navigation. which is confusing, 

### Expected behavior

When ever engaging with this nav element, is should open and collapse as you'd expect.  Also when clicking on a component in the navigation the user should not be bumped to the top of the navigation.

**Comment by jpvajda** [comment]
@jerelmiller i found this weirdness today perhaps we can take a look at it in the next MMF for the OSS Site Transfer as it's pretty bad UX.

**Comment by jerelmiller** [comment]
That sounds like a good idea!

**Comment by LizBaker** [comment]
PR #443 has been merged and adds the toggle/fixes a refresh issue in which the subnav became inaccessible. 

Getting bumped to the top of the nav is a more complex issue and will be addressed in a separate PR
