### ISSUE TITLE
Properly document the nerdlet.setUrlState method 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#450]
### Description

Not all API methods are documented in the developer documentation. For instance, `nerdlet.setUrlState` method is not mentioned in the [developer documentation under platform API / nerdlet](https://developer.newrelic.com/apis/nerdlet ) but it’s part of the how to understand url state guide defined on [Discuss](https://discuss.newrelic.com/t/how-to-understand-nerdlet-url-state/97596)

### Steps to reproduce

1. Go to https://developer.newrelic.com/apis/nerdlet
2. Try to find any information on nerdlet.setUrlState
3. Go to https://discuss.newrelic.com/t/how-to-understand-nerdlet-url-state/97596
4. Try to see all the information on nerdlet.setUrlState

### Expected behavior

We properly document this method in the Platform API / nerdlet section of the developer site.

 It would be really nice to cross-link between [NerdletStateContext](https://developer.newrelic.com/components/nerdlet-state-context) and the [Nerdlet API](https://developer.newrelic.com/apis/nerdlet) since they are both intertwined, perhaps use the new RIGHT RAIL to highlight the page association.

### Additional context

We looked into updating the NR1 Core documentation for Platform API / nerdlet  as it's also not explained there to ensure the SDK Bundler can auto generate this method's documentation in the future. However that cannot be done at this moment, so this will be a manual change on the developer site to ensure this functionality is clearly document. 

Given we will do this manually we should ensure an auto update from the SDK Bundler won't overwrite this manual entry.

**Comment by jpvajda** [comment]
I'm wondering if we just need to update this doc section: https://developer.newrelic.com/components/nerdlet-state-context

**Comment by jerelmiller** [comment]
We will want to also capture that `NerdletContext` uses the URL state to populate its context value. It would be very useful to link to the `nerdlet` documentation since the `nerdlet.setUrlState` method will not only update the URL state, but also effect the `NerdletContext` value.

**Comment by jpvajda** [comment]
Updated per our convos today on the platform documentation @jerelmiller
