### ISSUE TITLE
Errors for piechart unique count should be dynamic

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#454]
### Description

When using uniqueCount queries in pie charts within nerdpack application, this warning is automatically added and there’s
no easy way to remove it: “This pie chart uses uniqueCount, which may result in the facet sum exceeding 100%. Learn more in our documentation.”

### Steps to reproduce

1. Build a pie chart in a nerdlet
2. Use unique Count in the query

```query='SELECT uniqueCount() FROM `Synthetics` SINCE 1 DAY AGO TIMESERIES AUTO FACET jobType'```

3. See default error message.

<img width="1397" alt="Screen Shot 2020-07-16 at 6 01 41 PM" src="https://user-images.githubusercontent.com/1395158/87733987-87738600-c78e-11ea-8002-d73bfbf2ff98.png">

### Expected behavior

A developer can have control of what error message is displayed.

### Additional info

this may require an update the NR Core so the SDK bundler is accurate.

**Comment by jerelmiller** [comment]
@jpvajda Is this something that is happening on the component page? I'd like to better understand what we are looking for here.

**Comment by jpvajda** [comment]
@jerelmiller it's when a user actually uses the component within in application. There is default message that users would like controls over.

**Comment by jerelmiller** [comment]
@jpvajda sounds like maybe thats something for the one core team? I'm not sure thats something we are able to handle on the dev site since we don't own the SDK.

**Comment by jpvajda** [comment]
@jerelmiller for sure, I captured that in the additional info section. I though as we build a bridge to that team, we can just make this code change on behalf of our 3rd developers and ensure it get done.

**Comment by jpvajda** [comment]
@jpvajda will file this with the NR1 core team, it's out of scope for DevEx to do this change.

**Comment by jpvajda** [comment]
closing as this isn't an issue the devex team can actually resolve. the feedback has been shared with the NR1 Core Team
