### ISSUE TITLE
Provide an NR1 CSS stylesheet for starter apps

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#455]
### Describe the solution you'd like

It would be very helpful if New Relic provided a NR1 CSS stylesheet to help developers get started without spending too much time creating their own stylesheets.

### Describe why this important to you

Provide basic starter CSS code will help a new developer get up an running faster when building apps for the first time. 

We already provide a few helper libraries, but perhaps we can expand these:  https://github.com/newrelic?q=layout&type=&language=

**Comment by jerelmiller** [comment]
@jpvajda Does the [nr1-community](https://github.com/newrelic/nr1-community) library satisfy this requirement? That provides some out-of-the box components for devs to use in their own custom apps. Thoughts?

**Comment by jpvajda** [comment]
@jerelmiller  I think it does for now, we can close this, though it would be nice to enhance that CSS library over time from outside contributors.
