### ISSUE TITLE
This is a bug please fix!

### ISSUE THREAD

**Issue by xbriixog95** [newrelic/developer-website#459]
### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jerelmiller** [comment]
Hey @xbriixog95! Great to see you interested in the project! 

I see you've opened this issue, but it appears you haven't filled any of the information out. Would you mind updating both the title of this issue and the description above to describe a bug you are encountering with the site?

**Comment by jpvajda** [comment]
Closing due to lack of info on the bug
