### ISSUE TITLE
Highlight some of the popular Open Source Apps on the DevSite 

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#469]
### User Story

As a developer who is learning about New Relic I'd like to see open source applications I can use as I traverse the Developer Site, this will allow me to discover code libraries I can use to build something cool new relic. 

### User Experience Main Catalog Pages

We should add a section to the main navigation pages that highlights 9 applications from the OSS Sites.

- [Collect data](https://developer.newrelic.com/collect-data) should list instrumentation apps from [Instrumentation Collection](https://opensource.newrelic.com/instrumentation/)

- [Build apps](https://developer.newrelic.com/build-apps) should list apps from [Nerdpacks](https://opensource.newrelic.com/nerdpacks/)

- [Build apps](https://developer.newrelic.com/build-apps) should list Layouts from [Layouts](https://opensource.newrelic.com/layouts/)  - maybe? thinking through if we should surface this, it seems useful.

- A view all link should take the user to the OSS Site for that particular Collection so they can see all the apps available to them.

### App Usage Data

**Installs**
https://staging.one.nr/0qQamqPQ

**Usage**
https://staging.one.nr/0qQam4GQ

### User experience Right Rail

showcase particular open sources projects that actually relate A particular guide the user is looking at it. Say you are on the Collect Data From Any Source and if the page mentioned open source projects, we show that on the page, This could appear in the right rail, in a separate section, like **Related Apps**

### Dynamic vs. Static generation

It would be cool if this was dynamic and leveraged the the stats show on the OSS Site to showcase the most popular projects, perhaps an algorithm that uses: App Subscriptions + App Usage + Contributors + Commits + PRs  with some weighting to determine what projects to show. 

If we decide to go the dynamic route, we should exclude the [developer site project](https://opensource.newrelic.com/projects/newrelic/developer-website) from appearing in this section.

**Comment by jpvajda** [comment]
Before this is worked on I think @djsauble is accounting for this in the Right Rail feature. I saw it was put in proposed to I wanted to ensure we discussed where this functionality is going to live prior to starting coding on it.

**Comment by djsauble** [comment]
Yes, the right rail has a dedicated section for related apps. I don't know what all Swifttype takes into account when determining what to show, so this might be partly a research task.

**Comment by jpvajda** [comment]
We discussed in standup to to do this in as we originally specified and not use the right rail to showcase these apps.

**Comment by jpvajda** [comment]
one topic that came up with @markweitzel today was a way to showcase particular open sources projects that do actually relate A particular guide the user is looking at it. Say you are on the Collect Data From Any Source and if the page mentioned open source projects, we show that on the page. This definitely feels more like Right Rail functionality @djsauble so perhaps we can discuss.

**Comment by djsauble** [comment]
Chatted with @markweitzel about this.

* Adding apps to the right rail can wait, not gonna be a v1 thing.
* We should add a smattering of the most relevant apps to each of the guide landing pages.
    * "Collect data" should list instrumentation options from https://opensource.newrelic.com/instrumentation/
    * "Build apps" should list apps from https://opensource.newrelic.com/explore-projects

**Comment by jpvajda** [comment]
Updated with some clarifications.

**Comment by jpvajda** [comment]
Though I think this is useful, going to backlog for now for other priorities.

**Comment by jpvajda** [comment]
closing as this concept is part of a larger initiative for the DevEn team.
