### ISSUE TITLE
Create a guide for how to collect telegraf metrics

### ISSUE THREAD

**Issue by mmfred** [newrelic/developer-website#471]
Per Mark, turn this blog post into a guide for the developer site: https://blog.newrelic.com/engineering/how-to-collect-telegraf-metrics/

### Summary

While we will link to some content on the blog, this is one that Mark requested we turn into a guide.

### What type of documentation change are you suggesting?

New guide

**Comment by JimHagan** [comment]
Collecting metrics is going to depend on what the use case is.  Let's consider some "themed" guides.  For example these input plugins represent kind of the canonical set of infra gathering inputs...

```
[[inputs.cpu]]
[[inputs.disk]]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]```

Some themed guides I would help support are...

1. Infra monitoring
2. Scraping Prometheus Endpoints
3. Monitoring Common Open Source Services (Redis, MySQL, Postgres, etc.)
4. Netflow

Maybe some others.
