### ISSUE TITLE
[Setup] Add SwiftType `<meta>` tags for each page

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#475]
## Description
SwiftType is already set up to crawl and index the developer site. That said, we should add some `<meta>` tags to help give a little bit of context for each page. The the docs site currently has this set up, and can be used for reference (see screenshot). We should be able to use `<Helmet>` for this stuff.

## Helpful Links
* [SwiftType documentation](https://swiftype.com/documentation)

## Screenshots
<img width="1186" alt="2020-07-21_10-12-41" src="https://user-images.githubusercontent.com/1946433/88417230-6fa38f80-cd96-11ea-89ef-37dcd27955b4.png">

**Comment by caylahamann** [comment]
@zstix should we come up with a way that we want to add the meta tags to each side? or is there a way we can programmatically add them to the head by the use of helmet?

**Comment by zstix** [comment]
I think we can add these to each page via `Helmet`.

Perhaps the user can configure some of this stuff in the Gatsby theme, such as the type of page (docs, blog, dev site, etc). The rest we should already have access to in the dev site instance of helmet (the `SEO` component). I'm happy to work on this with ya after standup if you want.

**Comment by caylahamann** [comment]
@zstix yes please! I would love to pair on this
