### ISSUE TITLE
[Related Content] Call SwiftType to find content based on the current page

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#477]
## Description
When a user navigates to a page, we should make a call to SwiftType to search for pages similar to the one they're on. For now, we can use the following to learn about the page:
* Title
* URL
* Information in `<meta>` tags

_NOTE: this ticket is just for determining information about the page and fetching for results._

## Helpful Links
* [SwiftType documentation](https://swiftype.com/documentation)
* #475 (meta tags)
* #473 (SwiftType research)

## Screenshots
N/A

**Comment by zstix** [comment]
I'm going to remove this from the MMF (Milestone) and the board, as this is no longer within scope of the current MMF.

**Comment by jerelmiller** [comment]
We now have a process in place that will refresh the sidebar content on a daily basis. From what I can tell, that should satisfy the work required for this issue. I'm going to go ahead and close this. Feel free to reopen if there is something missing!
