### ISSUE TITLE
[Related Content] Display related content in right rail

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#479]
## Description
~Once we have fetched for related content (#477)~ we should display 5 - 7 related results in the right rail (#476). Each result should have a label explaining where the content will take the user (docs, blog, etc.) Designs for this are still in progress.

### Acceptance Criteria

- Related content URLS will be defined in the front matter of the page itself. 
- If there is no related content URL, don't show anything in the Right Rail.
- NOTE: in the next MMF dynamic search results will populate the Right Rail.
- We'll also be removing the related content info section on a page when transferring the URLs to the Right Rail as we don't want to show duplicate content.

_NOTE: this is just for related pages, not apps and not feedback._

## Helpful Links
~* #477 (SwiftType fetch)~
* #476 (right rail UI)

## Screenshots
**Work-in-Progress Wireframes**

![IMG_0218](https://user-images.githubusercontent.com/186715/88437164-bc995d00-cdba-11ea-8339-9d29f947c624.jpeg)

**Comment by jpvajda** [comment]
Updated the issue with some details on the related content URLs and the use of front matter.

**Comment by caylahamann** [comment]
Isn't this ticket done with the merge of Jerel's related content PR? @zstix

**Comment by zstix** [comment]
I believe so, just waiting to verify it on the site (in the process of fixing a build issue at the moment). I'll close this once it's verified...hopefully by E.O.D.

**Comment by zstix** [comment]
This is merged in!
