### ISSUE TITLE
[Right Rail] Ability to provide feedback if search results were helpful

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#485]
## Description
We would like to provide a similar feedback mechanism that exists on the docs site search (and similar in-product experiences 🤔) where a user can say whether or not the search results where helpful or not. We do not have designs for this at the moment, but can copy the look and feel found elsewhere.

At the moment, we will just be providing a 👍 and 👎 option. This feedback will be tracked using _Tessen_ (#472) and should contain the following:
* The search query entered
* Some information about the results provided
* The user sentiment

The feedback widget should also send this data with Tessen, to the same location that the in product XP feedback goes to.

We should also remove the buttons after feedback has been submitted (so no one smashes the buttons to throw off analytics).

## Helpful Links
* #472 (setup Tessen)
* [Example on the docs site](https://docs.newrelic.com/search#query=apm&page=1&webProperty=docs&docsContentType=&docsCategory=)
* 🤔 

## Screenshots

![IMG_0218](https://user-images.githubusercontent.com/186715/88436957-4268d880-cdba-11ea-93f4-1d46c5d103a4.jpeg)

**Comment by zstix** [comment]
I've updated this title to reflect that this will now be living in the "Right Rail" (related content) section.

**Comment by jpvajda** [comment]
updated that the feedback widget should send data to the same location as the In product XP Help Feature.

**Comment by zstix** [comment]
I'm removing this ticket from the MMF as the main deliverables (search and related content) are complete and I don't want to hold off calling the MMF complete while we troubleshoot this.

**Comment by jpvajda** [comment]
@zstix  - I spoke to Austin about how they track the thumbs, in the current Docs site, and they do send that data via Tessen but may be switching to amplitude... perhaps we can send this data to GA for the time being?

**Comment by jpvajda** [comment]
Now that we have created this component on the Doc Sites, we can look to implement this on the Dev Site. https://github.com/newrelic/docs-website/issues/300
