### ISSUE TITLE
[Search] Ability to filter search results by source

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#486]
## Description
On the [docs site search results page](https://docs.newrelic.com/search#query=apm&page=1&webProperty=docs&docsContentType=&docsCategory=), we have the ability to filter the results by source (i.e. docs, blog, etc).

Ideally, we would be able to do this in the query to SwiftType so that we can maintain accurate pagination and result counts.

## Helpful Links
* #473 (Swifttype research)
* #482 (search results UI)
* [Example on the docs site](https://docs.newrelic.com/search#query=apm&page=1&webProperty=docs&docsContentType=&docsCategory=)

## Screenshots
N/A

**Comment by caylahamann** [comment]
@djsauble is there a particular way that you would like this presented on the developer site?

**Comment by zstix** [comment]
I'm going to remove this from the MMF so that we can call it complete. Perhaps we can revist this when we have some additional time.

**Comment by djsauble** [comment]
Whoops! Just saw this. I chatted with @LizBaker about this and think a dropdown approach is best, but I think there were some open question around how difficult it was going to be to do that.

**Comment by jerelmiller** [comment]
After chatting with @djsauble we want to try and launch this feature without the ability to search. We will want to measure the impact of search as it exists now and see if this is something we want to add in the future. Closing this issue for now.
