### ISSUE TITLE
[Search] Update the URL based on the search state

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#487]
## Description
If possible, we should consider updating the browser URL based on the current state of the search (i.e. what they're searching for). This would allow a user to copy / paste a link to the search results and gives them the ability to use their browsers history to go forward / back.

## Helpful Links
* [Example on the docs site](https://docs.newrelic.com/search#query=apm&page=1&webProperty=docs&docsContentType=&docsCategory=)

## Screenshots
N/A

**Comment by LizBaker** [comment]
currently our swift search component is saving the query in the url, however, we will need to save the state of our overlay being open in order for a user to see the search they were linked to without clicking the icon
