### ISSUE TITLE
Headers (h1, h2, h3, etc) are inconsistent across the site

### ISSUE THREAD

**Issue by djsauble** [newrelic/developer-website#499]
### Description

Headers should be styled and nested consistently across the site.

### Steps to reproduce

1. Go to the [collect data|https://developer.newrelic.com/collect-data/collect-data-from-any-source] guide.
2. Note that the `<h2>` elements in the steps are sized `1rem`.
3. Go to [create custom events|https://developer.newrelic.com/collect-data/custom-events] guide.
4. Note that the top `<h2>` element is sized `1.5em` and is italicized, both differing from the other `<h2>` element.

### Expected behavior

* Every page should have only one `<h1>`
* Nested headers should not skip levels (BAD: `<h1></h1><h3></h3>`, GOOD: `<h1></h1><h2></h2>`)
* Each level should be styled consistently across the site (e.g. Every `<h3>` should have the same `font-size`)

### Additional context

@jerelmiller suggested setting up a markdown linter to help ensure proper nesting behavior.

**Comment by jpvajda** [comment]
set this as a P3, but I like consistency so maybe we can correct this quickly in the currrent sprint.

**Comment by LizBaker** [comment]
we may have other inconsistencies but with the steps we are purposefully styling any `h` tags to be the same size so we could control for consistency within step styles. we needed a tag that differed from `p` tags so we could style an optional title
