### ISSUE TITLE
Change the "Collect Data" icon to match the TDP icon on docs.newrelic.com

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#503]
consistency is key for usability across the product. we'll need a slightly different treatment on it, as our icons have no colors. But we should change the "Collect Data" [icon](https://docs.newrelic.com/sites/default/files/thumbnails/image/home-TDP-icon.svg) to match the new TDP icon on docs.newrelic.com.

**Comment by jpvajda** [comment]
moving to the current iteration as this will align with the NR marketing site well.

**Comment by djsauble** [comment]
Here's the recolorized version of that icon for use on the developer site.


https://drive.google.com/file/d/14S-VMqARrBwYl8Ryo69j8eFT1qkmf8PR/view?usp=sharing

**Comment by jpvajda** [comment]
@djsauble I can make this change if you want to either upload the image directly to this issue, or give me access to the location on google drive. Thanks!

**Comment by jpvajda** [comment]
I'll leave this for the team to resolve. I thought it be quick to change, but it's not as simple as I thought. :)

**Comment by jpvajda** [comment]
[Collect_data_icon.svg.zip](https://github.com/newrelic/developer-website/files/5018582/Collect_data_icon.svg.zip)

**Comment by jerelmiller** [comment]
Heads up, this icon does not look super great at a small size. Here is a screenshot of the nav if we kept the icon the same size as the others:

<img width="326" alt="Screen Shot 2020-08-06 at 11 25 01 PM" src="https://user-images.githubusercontent.com/565661/89615802-1d557a80-d83c-11ea-82f1-dbdd02fabc73.png">

Here's a more focused screenshot:

<img width="235" alt="Screen Shot 2020-08-06 at 11 24 14 PM" src="https://user-images.githubusercontent.com/565661/89615829-26464c00-d83c-11ea-9897-edc9142505ba.png">

As you can see, its very difficult to make out what the icon is.

@djsauble we may need to rethink the sizing of the icons in the sidebar a bit if we want them to match, or we may need to rethink how we can best make this icon look alright in the sidebar. I really like the icon itself, but it doesn't look like its meant to render at small sizes.

**Comment by jpvajda** [comment]
We can probably increase the icon sizes a little to get more clarity... They do look really small on most screens.

**Comment by djsauble** [comment]
Hrm, yeah, that doesn't look great. Let me play with the stroke width a li'l bit.

**Comment by djsauble** [comment]
I doubled the stroke width on it, let's see if that helps. https://drive.google.com/file/d/14S-VMqARrBwYl8Ryo69j8eFT1qkmf8PR/view?usp=sharing

**Comment by jpvajda** [comment]
We can also change the width height on these svg icons to 2em

![Screen Shot 2020-08-07 at 2 47 27 PM](https://user-images.githubusercontent.com/1395158/89687192-f68b5880-d8bc-11ea-9434-fc7d3e7f5ddb.png)

**Comment by jerelmiller** [comment]
The icon is a touch better, but at this size, its still just a bit hard to fully understand what the icon is. Should we consider a larger size like @jpvajda 's suggestion?

<img width="329" alt="Screen Shot 2020-08-17 at 3 41 39 PM" src="https://user-images.githubusercontent.com/565661/90451461-b9834b00-e0a0-11ea-97a1-ad8f78f738ad.png">

**Comment by jpvajda** [comment]
Bumping the icon size to 2em could look cool. @djsauble what do you think?
