### ISSUE TITLE
Add "How to contribute" to the Right Rail

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#504]
We should encourage community contribution by adding a "How to contribute" guide to the right rail.

### AC
1. add a link to the component of the right rail that links to our [CONTRIBUTING.MD](https://github.com/newrelic/developer-website/blob/main/CONTRIBUTING.md) file on Github.
2.  see design below

![Screen Shot 2020-08-11 at 11 29 45 AM](https://user-images.githubusercontent.com/1395158/90190163-bbd16680-dd7b-11ea-86e6-8a92a1f9420d.png)

**Comment by jpvajda** [comment]
We simplified this to just be about a link in the right rail, later on we can consider making this a proper page on the site: https://github.com/newrelic/developer-website/issues/600
