### ISSUE TITLE
Side Navigation onpage load improvement

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#505]
### Issue 
Now that we have more guides (and more top level items, e.g. podcasts), the top level items don't show. Let's think about how we can modify this to show all the top level items when a user first lands on the page.

### Design Considerations

One simple thing to do, is on page load, have the menus load as collapsed instead of expanded as they are now. Similar to how Apollo does it: https://www.apollographql.com/docs/

### Acceptance Criteria 

-  on page load show side navigation as collapsed instead of expanded.

**Comment by jpvajda** [comment]
One simple thing to do, is on page load, have the menus load as collapsed instead of expanded as they are now. Similar to how Apollo does it: https://www.apollographql.com/docs/

**Comment by jpvajda** [comment]
@djsauble  thoughts?

**Comment by djsauble** [comment]
I agree with all of the above. We have enough top-level nav items that loading them collapsed by default shouldn't look weird.
