### ISSUE TITLE
Update russ's app video on the DevSite and OSS Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#531]
@mbazhlekova is updating Russ's App demo video and recording a new version, when done we need to switch these pages to point to the new video.

https://opensource.newrelic.com/nerdpacks/
https://developer.newrelic.com/build-apps/build-hello-world-app

**Comment by jpvajda** [comment]
@veextee  - just let me know when you have the new video recording and what the new URL is.

**Comment by jpvajda** [comment]
Thanks for jumping on this @mbazhlekova

**Comment by jpvajda** [comment]
The production on this issue will occur next week as our main videographer is on FTO this week.

**Comment by jpvajda** [comment]
@veextee  confirmed Kyle is back from FTO and working on this video this week

**Comment by veextee** [comment]
Final video here: https://www.youtube.com/watch?v=7omo0qHxku8&feature=youtu.be
