### ISSUE TITLE
Provide documentation on this page for how to write to the NerdletStateContext

### ISSUE THREAD

**Issue by cirne** [newrelic/developer-website#538]
There is no documentation on this page for how to _write_ to the `NerdletStateContext`. Presumably that ends up modifying the url params. Please presume I don't have a thorough understanding of React Context stuff, which feels more like React 202, not the core stuff I would expect most React developers to fully understand.

Missing documentation would be added here: https://developer.newrelic.com/components/nerdlet-state-context

**Comment by jerelmiller** [comment]
Related #450

**Comment by jpvajda** [comment]
Hello @cirne We'll close this one as duplicate and work from #450  Thank you for reporting this!
