### ISSUE TITLE
Update Guides to be more dynamic

### ISSUE THREAD

**Issue by mmfred** [newrelic/developer-website#560]
### Summary

These pages aren't true guides like the ones we'd like to have. And they heavily reference Insights, which is less ideal than using more recent tech. Would be ideal to create new guides on these topics, using the appropriate products/features:

- add-custom-attributes.mdx
- collect-data-from-any-source.mdx
- quary-and-store-data.mdx

### What type of documentation change are you suggesting?

Revise these concepts into guides that don't rely on insights.

### Motivation

provide some essential information.

### Writing the documentation

If you are interested in helping us create this documentation please let us know. 
We encourage community contributions and can more quickly move your idea to publication if you suggest changes, or create an outline or rough draft. We'll collaborate with you to hone whatever content you provide.

**Comment by jpvajda** [comment]
@mmfred Can you break these into separate issues and better define the expectation here so it's more clear how a community member may help with this request?

**Comment by mmfred** [comment]
I've pulled the info from this ticket into several different issues. Closing as it's not relevant anymore.
