### ISSUE TITLE
Add hardcoded links to related resources that aren't indexed by Swifttype

### ISSUE THREAD

**Issue by djsauble** [newrelic/developer-website#573]
### Is your feature request related to a problem? Please describe

In the right rail, we show people related content based on sites indexed by Swifttype. However, there are resources _not_ indexed by Swifttype that we may want to link.

### Describe the solution you'd like

In front matter, make it possible for people to specify links to these non-indexed resources. For example:

* Apps on the open source site
* Repos on GitHub
* Links in New Relic One (if the user is authenticated)

### Describe why this important to you

We want to make sure the most relevant stuff gets elevated in the right rail and something like Swifttype is always going to have holes.

**Comment by jerelmiller** [comment]
@djsauble Reading this again, I _think_ we have all of this addressed. My question to you is are we going to have different visual treatments for any of these bits of content or are they all going to be a link with the source tag underneath it? If it is the latter, this should be addressed with the `resources` frontmatter item. Here is an example for the "Add custom attributes" page: https://raw.githubusercontent.com/newrelic/developer-website/main/src/markdown-pages/collect-data/add-custom-attributes.mdx

You'll see the `resources` frontmatter item that allows someone to specify a URL + title

**Comment by djsauble** [comment]
Cool! I'll let @markweitzel chime in if there's anything I didn't capture in this ticket, but it sounds like we may be good here.

**Comment by jerelmiller** [comment]
This this currently working. Feel free to reopen if there is something we missed!
