### ISSUE TITLE
4 commands for the NR1 CLI are missing from Developer Docs.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#591]
nerdpack:build     builds a Nerdpack
  nerdpack:clean     removes all built artifacts
  nerdpack:validate  validates artifacts inside your Nerdpack
  nerdpack:info      shows the state of your Nerdpack in the New Relic's registry

Please run nr1 nerdpack -h to see these command details and add to the Dev Site in the following locations:

https://developer.newrelic.com/explore-docs/nr1-cli

https://developer.newrelic.com/explore-docs/nr1-nerdpack

**Comment by jpvajda** [comment]
@mmfred did you still have time to make this change?

**Comment by mmfred** [comment]
@jpvajda - I've added it as a work item to our sprint that's starting tomorrow. [DOC-6042](https://newrelic.atlassian.net/browse/DOC-6042)

**Comment by jpvajda** [comment]
@mmfred  Thank you!
