### ISSUE TITLE
Add tags to existing guides

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/developer-website#595]
### Summary

In order to make the best of the automated related resources section in the dev site, we need to tag existing guides. This is currently done via frontmatter under a `tags` key. We have a few pages already tagged. You can see an example for the [Collect data from any source](https://raw.githubusercontent.com/newrelic/developer-website/main/src/markdown-pages/collect-data/collect-data-from-any-source.mdx) page.

#539 has a good approach for tagging that was done to test out tags and search

### What type of documentation change are you suggesting?

Additional tags for existing guides. 

### Motivation

Tags will help influence related content for each page and should help us improve those results.

**Comment by mmfred** [comment]
I added tags to all the pages that didn't have them... and committed them. Just realized someone might have liked to review those.

**Comment by jpvajda** [comment]
@mmfred what PR did you commit the tag changes in? I can glance at them now.
