### ISSUE TITLE
Create a develop branch that is used to merge into main 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#598]
### Summary
In an effort to merge changes on features that are currently in progress, we are creating a develop branch. If you would like to submit a PR to our repository, you would want to merge it into develop and develop will be periodically merged into main to act as a deploy to main. 

### Motivation
The reason for this is two-fold. The first is to prevent merges into main without review, the second reason is to be able to merge changes that don't necessarily represent a finished feature for small, iterative change. 

### Steps 
* [x] Create a `develop` branch in the developer site repository
* [x] Have `nr-opensource-bot` merge into develop 
* [x] Have `develop` act as the default branch 
* [x] Evaluate Github actions so they are pointing to the correct branch
* [x] Document in our `README.md` the process to merging into `develop`

**Comment by caylahamann** [comment]
@LizBaker created the `develop` branch

**Comment by jpvajda** [comment]
This can wait until we get the search feature out.

**Comment by jpvajda** [comment]
I've submitted a PR to document this process #809
