### ISSUE TITLE
Support the creation of an events template for new relic developer events

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#617]
As we're planning Nerd Days for October, Jemiah would like to get a couple landing pages added to the developer website. These pages will be used to register attendees and promote the event.  It’s been suggested that a template is created for this page type so it’s reusable. 

**Considerations**

- Jemiah is working with Daniel G on the implementation. 
- Ideally this leverages components that can be reused.
- This should have standard design that can be re-used
- These event pages would exist under the new Attend events side navigation
- The DevEx Team would just provide PR support and merging of code.

**Comment by jpvajda** [comment]
@danielgolden  and @jaesius were working on this for nerd days...

**Comment by djsauble** [comment]
A table component for listing talks within an event would be awesome! We don't currently have a table component to my knowledge.

**Comment by jpvajda** [comment]
@jaesius did the first events page and committed that on #640 he is also going to refactor this later to add reusable components for events.
