### ISSUE TITLE
Modify Sign Up button, remove icon adjust padding

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#629]
We want to remove the cloud icon as at this scale it's hard to tell what it actually is. Also when doing that increase the font size to .8 rem. 

When complete this should also be updated in our gatsby template and applied to the OSS site. 

<img width="200" alt="Screen Shot 2020-08-17 at 7 05 33 PM" src="https://user-images.githubusercontent.com/1395158/90536123-e1be8880-e138-11ea-8810-0399cf6b2fa5.png">

**Comment by jpvajda** [comment]
@djsauble is going to take this one.

**Comment by djsauble** [comment]
https://github.com/newrelic/gatsby-theme-newrelic/pull/82
