### ISSUE TITLE
Collect data icon in the "Get Coding" section is wrong

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#630]
The icon in the "Get coding" section for the "Create Custom Events" should match the new icon. 
<img width="866" alt="New Relic Developers 2020-08-18 15-38-03" src="https://user-images.githubusercontent.com/522116/90557829-206c3700-e169-11ea-9f85-ac4eb85ae733.png">

**Comment by jpvajda** [comment]
This is fixed. closing
