### ISSUE TITLE
Treat the edit and create issue buttons differently in the right rail: 9/2

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#643]
The opinion is that these current buttons call attention to the filing an issue as one is darker then the edit this page. Our goal isn't to call attention to one or the other, but to be consistent in these actions. 

![Screen Shot 2020-08-19 at 7 10 16 PM](https://user-images.githubusercontent.com/1395158/90705284-d611b580-e24f-11ea-9075-90005d5491c0.png)

The suggestion is to change the buttons to the treatment used on the OSS site or something similar.

![Screen Shot 2020-08-19 at 7 10 25 PM](https://user-images.githubusercontent.com/1395158/90705294-db6f0000-e24f-11ea-809b-fbe9e617bc41.png)

**Comment by zstix** [comment]
I'm estimating this ticket as a 2-point story, assuming this is completed _after_ #645 (where we abstract and set up much of the work). In theory, this should be as simple as using the existing components, and patterns to do the same thing as the other ticket.
