### ISSUE TITLE
Bring dark mode more in line with the product

### ISSUE THREAD

**Issue by djsauble** [newrelic/developer-website#664]
The dark mode in NR1 is very dark (some might say too dark 😉). Regardless, once the dust settles on that work, it would be great for the dark mode on our websites to approximate that color palette.

### Is your feature request related to a problem? Please describe

One specific issue is with the component library section on the developer site. Because NR1 didn't have a dark mode at the time, the components were given a fixed white background so they show up properly. Unfortunately, this white mode is very glaring when viewing the site in dark mode so it's not ideal.

### Describe the solution you'd like

* The dark mode color palette on the developer and open source sites should approximate the dark mode palette of NR1.
* When the developer site is toggled into dark mode, we should show the dark mode variant of all NR1 components on the site.

### Describe why this important to you

It's important from a consistency perspective. We want our websites to feel like they're an extension of the product.

#### NR1 dark mode

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/186715/90935462-1c822400-e3b8-11ea-926e-b1ef44b5e51b.png">

#### Developer site dark mode

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/186715/90935478-23a93200-e3b8-11ea-9e23-e188a1b3a9f1.png">

### Open source site dark mode

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/186715/90935488-29067c80-e3b8-11ea-8b1a-f8402fd01338.png">

**Comment by danielguillan** [comment]
The current dark mode implementation in the product is an initial, experimental version which is currently only available to ~60 users who requested it through the in-product feedback form. There are many tradeoffs with this "inversion filter" approach: overall poor or very harsh contrasts, low saturation colors, no box shadows, broken inversions, and more.

We have started exploring a properly designed version of a dark mode for the product using the existing color palette in NR1. It'll definitely look closer to what we currently have in the developer site than the interim solution.

I would hold off on making any changes to the developer site until we have a decision and/or plan for a proper dark mode in the product. I'll keep you updated @djsauble.

**Comment by jpvajda** [comment]
@danielguillan  Thank you for the insights on this.

**Comment by jpvajda** [comment]
closing for now, as the product is using a temporary work around to this that uses CSS Filtering, we can address when the product aligns on a global standard and more scalable implementation of dark mode
