### ISSUE TITLE
Create an Archived Event section on the site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#672]
### Describe the solution you'd like

as we add more and more developer focused events they will eventual age and no longer be valid events. We should come up with a way to organize older events, in an event archive to ensure the most current events are visible to a user.

### Additional context

1. Create a new sub navigation section called "Past events"
2. Move all expired events to this area.
3. Use an icon from the NewRelic icon library that signifies the _passage of time._ lol

### Expired Events

https://developer.newrelic.com/kubecon-europe-2020

![Screen Shot 2020-08-21 at 7 35 26 PM](https://user-images.githubusercontent.com/1395158/90945931-7fd67b00-e3e5-11ea-89e7-253217582075.png)

**Comment by djsauble** [comment]
A couple thoughts:

1. This section should live under the "Attend events" section.
2. Perhaps call it "Past events" instead of "Archived events", as the latter sounds like we're trying to keep our email inbox clean, haha.

**Comment by jpvajda** [comment]
@djsauble yes, that makes sense. we don't have the concept of a 2nd level of navigation in the developer site yet, so this would be the 1st we'd introduce this pattern.

**Comment by jpvajda** [comment]
Oh the component library works this way.. cool. I'll check that out.
