### ISSUE TITLE
Scrollable code blocks...

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#673]
Sometimes, when the code block is too long, it can't be read, making it hard to see what the corresponding text is describing. Is it possible to make this scrollable?

<img width="1082" alt="Automate tagging of your entire stack | New Relic Developers 2020-08-21 23-05-42" src="https://user-images.githubusercontent.com/522116/90947321-ecac3e00-e402-11ea-803b-64fac3bfbab5.png">

**Comment by jerelmiller** [comment]
This seems to be working properly. Perhaps it was fixed some time ago. Feel free to reopen if this is still an issue!
