### ISSUE TITLE
Create a landing page for Attend events

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#678]
An event landing page would act as destination for users to go to when the click on attend events. it will follow a similar pattern to our existing landing pages on primary navigation items.

### AC 

- Show events in a tile like display similar to how we show guides on this [page](https://developer.newrelic.com/automate-workflows)
- Past events link to old event page.
- New events link to existing events page.
- Ideally we'd have a component to manage events so it's just controlled by editing some markdown.

**Comment by jpvajda** [comment]
@djsauble  any Design thoughts on this?

**Comment by djsauble** [comment]
Only thought is that I'd split the upcoming and past events into separate grids so it's easy to scan and understand what's coming up.
