### ISSUE TITLE
Update tracking implementation for better split metrics

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#690]
Track split test data in Split.io via their metrics capabilities to return useful data on measuring the success of a split test.

**Comment by zstix** [comment]
I'm marking this as a 2 point ticket. Originally, I had it as a 1 pointer (just add the GA code), but I recognize that there is an opportunity to refactor the configuration code a little bit more so that it's easier to work with.

**Comment by zstix** [comment]
After speaking with split and reviewing the metrics their platform uses, we have decided that we can probably use their platform to gain insights into our A/B tests. I'm going to rename this ticket to reflect this decision.

**Comment by jerelmiller** [comment]
Completed with https://github.com/newrelic/gatsby-theme-newrelic/pull/98
