### ISSUE TITLE
MktoForms2 ReferenceError when using Firefox with Enhanced Tracking Protection set to Strict

### ISSUE THREAD

**Issue by dvanoni** [newrelic/developer-website#691]
### Description

When using Firefox with **Enhanced Tracking Protection** set to **Strict**, the site (any page) renders for a moment and then goes blank when the following error is encountered:

```
ReferenceError: MktoForms2 is not defined
```

It appears that the **Strict** setting blocks content from `https://app-abj.marketo.com` and causes the reference error. Changing from **Strict** to **Standard** resolves the issue.

### Steps to reproduce

1. In Firefox's privacy settings (`about:preferences#privacy`), set **Enhanced Tracking Protection** to **Strict**
2. Navigate to any page on `https://developer.newrelic.com`
3. Wait for page content to load
4. Observe page going completely blank
5. Open console to see error

### Expected behavior

The error should not occur and the page should not go blank.

### Screenshots

<img width="1080" alt="Screen Shot 2020-08-26 at 18 19 51" src="https://user-images.githubusercontent.com/299357/91372714-3dd47d00-e7c9-11ea-90db-cf2d4101ac11.png">

<img width="1080" alt="Screen Shot 2020-08-26 at 18 26 51" src="https://user-images.githubusercontent.com/299357/91372937-e4b91900-e7c9-11ea-827c-dff611d4bd73.png">

<img width="1080" alt="Screen Shot 2020-08-26 at 18 26 05" src="https://user-images.githubusercontent.com/299357/91372860-aae81280-e7c9-11ea-8823-756e67eaf35d.png">

**Comment by meems1996** [comment]
Yes! I had to whitelist the website on my machine for ad-blockers. The bug also seems to persist on safari on my phone. I believe chrome also shares the error.

**Comment by jerelmiller** [comment]
This seems to be fixed from my testing. We did some updates to the code that handle the marketo form and I believe that work has fixed it. Feel free to reopen if this is still an issue!
