### ISSUE TITLE
Audit of NR Alerts

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#736]
### Background
Currently, we are getting alerted for errors that are caused usually by only one user and are not caused by our website. We should do a review / audit of our current alerts to ensure that we're getting alerted when there are errors are on our end and for multiple users 

### AC 

- [x] Review alert conditions for Page views with JS errors 
- [x] Review alert conditions for Total page load 
- [x] Create new alert conditions as necessary

**Comment by zstix** [comment]
We met as a team on 9/16 to discuss the alerts that we have been getting. The decision was to tune the alerts that we get from page views with high JS error rates (most likely coming from browser plugins).

Relevant outcomes:

Page views with JS errors (High) | Proposed to keep it page after hours | Proposal options: 1) count of affected users larger than X 2) filter out specific error types

**Comment by zstix** [comment]
We added a new alert condition to better represent JS Errors: `High Percentage of Users with JS Errors`

**Comment by zstix** [comment]
Made a ticket to track the work needed to add / configure alerts via terraform: https://github.com/newrelic/developer-website/issues/786
