### ISSUE TITLE
Fixes to What's New on current docs site: Create template for front end view

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/developer-website#739]
Currently, the docs site uses a generic page template and Drupal core functionality to output field content. The team wants the view to resemble the NR1 What's New view, which requires creating a custom PHP template.

This is related to https://github.com/newrelic/developer-website/issues/703

**Comment by jpvajda** [comment]
@austin-schaefer Why would we do this work on the existing Drupal site? Can this just be part of the new sites templating?

**Comment by austin-schaefer** [comment]
@jpvajda : The content is live now, and the new site is still several months out. PMM has been asking for this view as soon as possible. And I want to start promoting this content and getting users visibility into cool new features ASAP.

**Comment by austin-schaefer** [comment]
See also issue #703

**Comment by austin-schaefer** [comment]
@jpvajda : See my comment on #703. In summary, PMM needs this now. And I also don't want to leave our users in the dark on new platform features while we build the new site. This was built into the scope in https://docs.google.com/document/d/1A2JXpyMm2-G9VO7o2u9q4Gk1HznMPeS5YZLmKXiSCkk/edit#bookmark=id.8nb991t397vr

**Comment by jpvajda** [comment]
@austin-schaefer cool. Thanks for the clarification!

**Comment by roadlittledawn** [comment]
added a side nav block and menu page via Views for listings of What’s New content. 

deploying forthcoming to add get started and learn more links and update the style / layout to better match NR1.

single whats new page: https://docs.newrelic.com/whats-new/new-relic-one-has-dark-mode

menu page: https://docs.newrelic.com/whats-new

**Comment by roadlittledawn** [comment]
template work in dev now and let team know. awaiting feedback / approval. there's also a drupal core update to apply before merging and deploying this work

**Comment by roadlittledawn** [comment]
Deployed to prod
