### ISSUE TITLE
add steps to run npm install before nr1 nerdpack:serve to the add-nerdgraphquery-guide

### ISSUE THREAD

**Issue by rajatagarwal** [newrelic/developer-website#750]
### Description

Bug in the documentation: https://developer.newrelic.com/build-apps/add-nerdgraphquery-guide

### Steps to reproduce

1. Go to https://developer.newrelic.com/build-apps/add-nerdgraphquery-guide documentation and follow all steps in the fresh environment.
2. After that you could see an error of `missing module` while running `nr1 nerdpack:serve`. 

### Expected behavior

This error is addressed in this documentation: https://discuss.newrelic.com/t/unable-to-deploy-nr1-open-source-app/94936/2 where it asks to execute `npm install` before `nr1 nerdpack:serve`. Hence it should be the part of documentation.

### Screenshots

Error screenshot:
![image](https://user-images.githubusercontent.com/4978846/93228931-f741c500-f76d-11ea-9ef2-3939d549cd74.png)

### Additional context

It resolved the error after `npm install`

**Comment by jpvajda** [comment]
@rajatagarwal thank you for reporting this. Would you be willing to make a docs contribution to fix this?  The site is open to contributions.  If not, no problem I can resolve.

**Comment by rajatagarwal** [comment]
Hey @jpvajda , i have created a PR: https://github.com/newrelic/developer-website/pull/758

Thanks!
