### ISSUE TITLE
annoucement banner is reverting to a weird state after dismiss action, top navigation impacted

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#760]
### Description

announcement banner is reverted to a weird state after dismiss action

### Steps to reproduce

1. visit the site 
2. dismiss the announcement banner
3. refresh and traverse some pages

### Expected behavior

after dismissing the banner the site navigation shows correctly

Pre dismiss:
![Screen Shot 2020-09-16 at 10 18 50 AM](https://user-images.githubusercontent.com/1395158/93376406-c8cbf480-f816-11ea-9dde-b7cf1c25b1c6.png)

Post dismiss: 
<img width="1690" alt="Screen Shot 2020-09-16 at 12 13 41 PM" src="https://user-images.githubusercontent.com/1395158/93376492-eac57700-f816-11ea-85f8-835b529a17ad.png">

**Comment by zstix** [comment]
We reverted the offending PR and the site is no longer broken. Revert PR: #761 

Going to look into the cause of the issue and a fix.

**Comment by zstix** [comment]
Possible fix implemented in the theme: https://github.com/newrelic/gatsby-theme-newrelic/pull/107
