### ISSUE TITLE
Load Component Documentation Bundle from DevEx S3

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#770]
## Description
We currently load the component documentation bundle from a S3 bucket that we don't have control over. Even though the bundle is versioned, it doesn't guarantee that the contents could get updated without us knowing. It would be safer to download the bundle and upload it to a bucket we own.

**Comment by jerelmiller** [comment]
We are in contact with the one core team and will instead work to build an integrated solution with that team.
