### ISSUE TITLE
Marketo breaks site for Firefox users with ad-blocker enabled

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#774]
## Description
Marketo (used for the Nerd Days signup form) throws an error that brings down the site if an ad-blocker is enabled in Firefox.

`ReferenceError: MktoForms2 is not defined`

## Steps to Reproduce
1. In Firefox settings, under "Enhanced Tracking Protection", choose "Strict".
2. Navigate to the developer site.

## Screenshot(s)
![image](https://user-images.githubusercontent.com/1946433/93634041-c5667380-f9a4-11ea-87cf-6896c5b608e9.png)

**Comment by jpvajda** [comment]
Merlyn Albery-Speyer offered to submit a PR to fix this.

**Comment by zstix** [comment]
We may want to wrap the site in an [Error Boundary](https://reactjs.org/docs/error-boundaries.html) to more gracefully handle _any_ error on the site.
