### ISSUE TITLE
Step 2 on the Nerdpack Metadata Guide overlaps with sidebar in Firefox

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#822]
### Description

The second step on the [Serve, publish, and deploy your New Relic One app](https://developer.newrelic.com/build-apps/publish-deploy#add-images-and-metadata-to-your-apps) page overlaps with the "right rail" sidebar in Firefox (see screenshot).

This does not appear to be an issue in other browsers.

### Screenshots

![Screen Shot 2020-10-07 at 8 49 55 AM](https://user-images.githubusercontent.com/1946433/95355964-ff77b680-087a-11eb-8fa5-355a1a4612e5.png)

**Comment by jpvajda** [comment]
This doesn't seem to be an issue anymore as I can't seem to replicate it. I did refactor some of these JSON blocks when I saw this problem in other guides, so it's possible I fixed it.

https://github.com/newrelic/developer-website/pull/697/files
