### ISSUE TITLE
Clarity needed around updating `icon.png` for Nerdlets

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#840]
## Description
I recently went through the [Hello, World guide](https://developer.newrelic.com/build-apps/build-hello-world-app) on the developer website and was very confused about _what_ `icon.png` I needed to update to see it in the catalog. The guide references the icon in the launcher directory, but the top-level directory is where the icon needs to live to show in the catalog (where I would expect).

Updating the documentation to explain this would be very helpful. Additionally, explaining the purpose of the top-level `nr1.json` vs. the ones in nerdlets and launchers would be a big help too.

**Comment by jpvajda** [comment]
@zstix I think, based on my testing, that you actually need an icon.png in 2 places for it to be representing properly in the app catalog, for a launcher to have an icon it looks like icon.png needs to be in the launcher directory, and for an icon to appear on the app details page, it looks like it needs to be in the root project folder. my setup looks like this:

<img width="309" alt="Screen Shot 2020-11-24 at 4 28 06 PM" src="https://user-images.githubusercontent.com/1395158/100163028-0b8ef600-2e72-11eb-8402-d1e6eb629481.png">

So I think it may be a good idea to update the guide to explain how the icon.png file is used and where.

**Comment by jpvajda** [comment]
Fixed in PR #980
