### ISSUE TITLE
Unable to hide Copy button with copy=false

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#853]
### Description

The [Component Guide](https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md#usage-4) states that authors can use `copy=false` to hide the **Copy** button. However, `copy=false` doesn't seem to have an effect.

### Steps to reproduce

1. Go to [Quickly tag a set of resources](https://developer.newrelic.com/automate-workflows/5-mins-tag-resources)
2. Navigate to Step 4
3. Observe that the code block has a **Copy** button

<img width="799" alt="Screen Shot 2020-10-16 at 12 48 01 PM" src="https://user-images.githubusercontent.com/8672090/96286101-d8716100-0fad-11eb-9ca3-730b98d2145e.png">

### Expected behavior

The markdown for that particular code block looks like:

<img width="678" alt="Screen Shot 2020-10-16 at 12 46 33 PM" src="https://user-images.githubusercontent.com/8672090/96285949-a4963b80-0fad-11eb-8589-a056accd99d6.png">

So I expect the code block to not have a **Copy** button.

### Screenshots

Here's another example:

<img width="675" alt="Screen Shot 2020-10-16 at 12 49 13 PM" src="https://user-images.githubusercontent.com/8672090/96286197-035bb500-0fae-11eb-8421-539a5cb0aeb4.png">

<img width="795" alt="Screen Shot 2020-10-16 at 12 47 49 PM" src="https://user-images.githubusercontent.com/8672090/96286147-f0e17b80-0fad-11eb-822b-c1ad27105a17.png">

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.80
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2 
    gatsby-image: ^2.4.14 => 2.4.14 
    gatsby-plugin-clearbit: ^1.1.0 => 1.1.0 
    gatsby-plugin-emotion: ^4.3.10 => 4.3.10 
    gatsby-plugin-google-analytics: ^2.3.10 => 2.3.13 
    gatsby-plugin-google-tagmanager: ^2.3.5 => 2.3.11 
    gatsby-plugin-layout: ^1.3.10 => 1.3.10 
    gatsby-plugin-manifest: ^2.4.20 => 2.4.20 
    gatsby-plugin-mdx: ^1.2.40 => 1.2.40 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-newrelic: newrelic/gatsby-plugin-newrelic.git#5cd42e832f0588764dc332ce7ebd05794de5106a => 1.0.2 
    gatsby-plugin-offline: ^3.2.17 => 3.2.17 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-robots-txt: ^1.5.2 => 1.5.2 
    gatsby-plugin-sass: ^2.3.12 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.21 => 2.6.21 
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11 
    gatsby-plugin-use-dark-mode: ^1.1.2 => 1.1.2 
    gatsby-remark-autolink-headers: ^2.3.11 => 2.3.11 
    gatsby-remark-images: ^3.3.17 => 3.3.18 
    gatsby-source-filesystem: ^2.3.21 => 2.3.21 
    gatsby-transformer-remark: ^2.8.26 => 2.8.26 
    gatsby-transformer-sharp: ^2.5.10 => 2.5.11 
```

**Comment by jerelmiller** [comment]
@alexronquillo turns out we renamed this field from `copy` to `copyable`, but forgot to update the documentation. I'll go update the docs really quick to reflect this. If you could use `copyable=false`, that should work!
