### ISSUE TITLE
Code blocks can show in the wrong section and cover content

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#854]
### Description

When the browser window gets big enough to show the code blocks on the side, the code blocks can move around unexpectedly and even hide some text.

### Steps to reproduce

1. Go to [Automated Tagging](https://developer.newrelic.com/automate-workflows/automated-tagging)
2. Navigate to Step 3
3. Observe that the `services` JSON block covers some of the text and, in fact, shouldn't be where it is at all

### Expected behavior

The `services` block is supposed to show in the **Understanding the deployment configuration file** sub section.

### Screenshots

How it looks in a larger window:

<img width="500" alt="Screen Shot 2020-10-16 at 1 04 46 PM" src="https://user-images.githubusercontent.com/8672090/96288080-dceb4900-0fb0-11eb-97e6-d19300659ad4.png">

How it looks in a smaller window:

<img width="500" alt="Screen Shot 2020-10-16 at 1 05 11 PM" src="https://user-images.githubusercontent.com/8672090/96288190-ff7d6200-0fb0-11eb-9356-15c1a47a36af.png">

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.80
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2 
    gatsby-image: ^2.4.14 => 2.4.14 
    gatsby-plugin-clearbit: ^1.1.0 => 1.1.0 
    gatsby-plugin-emotion: ^4.3.10 => 4.3.10 
    gatsby-plugin-google-analytics: ^2.3.10 => 2.3.13 
    gatsby-plugin-google-tagmanager: ^2.3.5 => 2.3.11 
    gatsby-plugin-layout: ^1.3.10 => 1.3.10 
    gatsby-plugin-manifest: ^2.4.20 => 2.4.20 
    gatsby-plugin-mdx: ^1.2.40 => 1.2.40 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-newrelic: newrelic/gatsby-plugin-newrelic.git#5cd42e832f0588764dc332ce7ebd05794de5106a => 1.0.2 
    gatsby-plugin-offline: ^3.2.17 => 3.2.17 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-robots-txt: ^1.5.2 => 1.5.2 
    gatsby-plugin-sass: ^2.3.12 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.21 => 2.6.21 
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11 
    gatsby-plugin-use-dark-mode: ^1.1.2 => 1.1.2 
    gatsby-remark-autolink-headers: ^2.3.11 => 2.3.11 
    gatsby-remark-images: ^3.3.17 => 3.3.18 
    gatsby-source-filesystem: ^2.3.21 => 2.3.21 
    gatsby-transformer-remark: ^2.8.26 => 2.8.26 
    gatsby-transformer-sharp: ^2.5.10 => 2.5.11 
```

**Comment by jerelmiller** [comment]
@alexronquillo This may or may not also be addressed as part of my innovation project. I'll have a preview link for it soon and will share to see if this fixes the issue.

**Comment by jerelmiller** [comment]
Also thanks for reporting these bugs! These are super useful!

**Comment by alexronquillo** [comment]
@jerelmiller No problem! Glad to help. Also, I added a request, separate from this bug, to just always display the code blocks in context (#856). Maybe we can chat there about some of the pros and cons about doing this arrangement in the first place. Thanks!
