### ISSUE TITLE
Auto-generate a styled TOC for every guide

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#857]
### Is your feature request related to a problem? Please describe

Unless a user navigates to the developer site through a specific link with a fragment identifier, they have to scroll through the content to find a specific section.

### Describe the solution you'd like

I'd like to see every guide have an auto-generated (and styled) table of contents.

### Describe why this important to you

This is important to me for a few reasons:

- Authors craft descriptive and informative headings for sections, sub-sections, and steps. These headings tell the story of what the guide/article is about and allow the reader to quickly understand where the article covers particular material.
- A table of contents allows readers to jump to specific content. If there is no table of contents, it's harder for the reader to make use of these headings because they have to scroll through the content anyway.
- This would be consistent with the docs site, which has a table of contents on every content page.

### Additional context

The style guide [mentions creating tables of contents](https://github.com/newrelic/developer-website/blob/develop/STYLE_GUIDE.md#updating-table-of-contents) as an option for particular articles and suggests using a tool like `Markdown-TOC` for automating that process. I think the "optional" nature of this makes it less likely that authors will create one and more difficult for editors to keep them updated. The table of contents that `Markdown-TOC` produces is also just a bulleted list, so not the best UX.

**Comment by paperclypse** [comment]
On the Docs site, we have each page's table of contents in the right nav. For more complicated docs, this allows for a next TOC: https://docs.newrelic.com/docs/query-your-data/explore-query-data/data-explorer/introduction-data-explorer

It's pretty unobtrusive, which I like, but I'm not sure people always notice it's there.

I absolutely prefer an auto-generated TOC over a manually crafted one (especially given the quantity of docs we're dealing with on docs.newrelic.com.)
