### ISSUE TITLE
remove split.io test code from developer site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#869]
Now that we've concluded the split test, we can remove the split test code from the developer site to ensure we don't leave extra code we don't need in the source code:

**Right Rail Buttons**
https://github.com/newrelic/developer-website/blob/45e22b7e190d3f9e560f1b0fee9968df00fd5fa8/src/components/RelatedContentModules/Contribute.js

**Constants**
https://github.com/newrelic/developer-website/blob/45e22b7e190d3f9e560f1b0fee9968df00fd5fa8/src/data/constants.js

**Global Header Buttons**
https://github.com/newrelic/gatsby-theme-newrelic/blob/21aa339e43ff7e919ec438d68510ec071654b1dc/packages/gatsby-theme-newrelic/src/components/GlobalHeader.js

**Comment by jpvajda** [comment]
@jerelmiller I was looking for all the code that ran those split tests, was thinking of removing the code to clean it up. What do you think?

**Comment by jerelmiller** [comment]
Oops, we removed this a while ago in https://github.com/newrelic/gatsby-theme-newrelic/pull/130. Closing!

**Comment by jerelmiller** [comment]
@jpvajda any reason you reopened this? Did you find a place that we forgot to remove? This was done via the comment above.

**Comment by jpvajda** [comment]
@jerelmiller  I saw the split code in those links, then I realized they are commit references. sorry!
