### ISSUE TITLE
Add oss and devsite domains to google search console

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#888]
Google Analytics is user-oriented, providing data related to those who visit and interact with your website. Google Search Console, on the other hand, is search-engine focused, providing tools and insights that can help site owners improve visibility and presence in the SERPs.

We currently don't have our domains verified in Google Search console which we should do to get search analytics. 

Google has 4 ways to validate your site We just need to decide which approach to use and implement that approach

<img width="610" alt="Screen Shot 2020-10-23 at 1 21 13 PM" src="https://user-images.githubusercontent.com/1395158/97052105-a461e700-153d-11eb-9c32-e988b24ce4f3.png">

**Comment by jpvajda** [comment]
I tried all those verification methods, and they don't validate we are looking into it and think that the Google UA tag is not being fired due to our cookie acceptance component, so Google isn't able to validate it.  @jerelmiller thinks  its because we don’t install the tracking code until after the user agrees to accept the cookies

**Comment by caylahamann** [comment]
For this we might have rewrite the way we do cookie consent in our site, so I'm going to read through the google analytic docs to see if we're able to correctly configure this.

**Comment by jpvajda** [comment]
We've tried several approaches to this and none have worked unfornately so we are going to go with the simplest which is the HTML meta tag. 

@caylahamann here are the instructions, when I return I can validate this in Google Search Console. OR @zstix may have access to Search Console and he can validate it. :) 

To validate you just click on the menu in the right corner of the console:

![Screen Shot 2020-10-30 at 6 09 55 PM](https://user-images.githubusercontent.com/1395158/97766216-1eb0df00-1adb-11eb-91ff-62cf476e15d7.png)


1. Copy the meta tag below, and paste it into your site's home page. It should go in the <head> section, before the first <body> section.

**developer site**
<meta name="google-site-verification" content="He_vizRXYX_mUhwBe3BmyaMxNnVRAZbq_Jtm2A0e4WY" />

**oss site**
<meta name="google-site-verification" content="He_vizRXYX_mUhwBe3BmyaMxNnVRAZbq_Jtm2A0e4WY" />

**Comment by roadlittledawn** [comment]
FWIW, we're verified with Google Search Console. not sure if there's anything to do except give additional peoples access?

**Comment by jpvajda** [comment]
this is done. :)
