### ISSUE TITLE
Fix Broken links in Telco Lite Guide

### ISSUE THREAD

**Issue by Julien4218** [newrelic/developer-website#901]
The 3 links at the top of the page under prerequisites are also broken.

The 2 links at the bottom of this page "other issues" and "tear down" are getting 404.
https://developer.newrelic.com/automate-workflows/diagnose-problems/error-alerts

**Comment by jpvajda** [comment]
These are broken as well.

<img width="782" alt="Screen Shot 2020-10-29 at 4 12 59 PM" src="https://user-images.githubusercontent.com/1395158/97638181-a9251000-1a01-11eb-87d8-8b10234a6417.png">

**Comment by jpvajda** [comment]
@mmfred has a fix for this.
