### ISSUE TITLE
Issue while installing nr1 cli on my ubuntu (16.04) box

### ISSUE THREAD

**Issue by soumarshi** [newrelic/developer-website#946]
### Description

When installing nr1 CLI with "**curl -s https://cli.nr-ext.net/installer.sh | bash**" as per documentation, I am getting error.

### Steps to reproduce

1. Open terminal
2. sudo su to log to root
3. curl -s https://cli.nr-ext.net/installer.sh | sudo bash
4. Below error 
 
W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
W: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com stable InRelease: The following signatures were invalid: KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372
W: http://www.openprinting.org/download/printdriver/debian/dists/lsb3.2/Release.gpg: Signature by key F8897B6F00075648E248B7EC24CBF5474CFD1E2F uses weak digest algorithm (SHA1)
W: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/stable/InRelease  The following signatures were invalid: KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/cache/app-info -a -e /usr/bin/appstreamcli; then appstreamcli refresh > /dev/null; fi'
E: Sub-process returned an error code
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Translations (main/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2

### Expected behavior

CLI should be installed and nr1 --version should give me the version installed
### Screenshots

![image](https://user-images.githubusercontent.com/55271299/98506024-9ec80900-2280-11eb-8091-98d9a9d77c13.png)

### Additional context
update: Also tried with ubuntu 20.04 which gives different error
![image](https://user-images.githubusercontent.com/55271299/98506518-b227a400-2281-11eb-8be4-53b119e94ec3.png)

Want to use the Observability Maps app to view transactions between applications

### Environment

Ubuntu 16.04

**Comment by jpvajda** [comment]
https://newrelic.atlassian.net/browse/DEVEX-1465

**Comment by jpvajda** [comment]
@soumarshi the actually command is  `curl -s https://cli.nr-ext.net/installer.sh | sudo bash`  We are going to fix that in Developer Center so it's not as confusing. 

![Uploading Screen Shot 2020-11-12 at 4.32.31 PM.png…]()

**Comment by soumarshi** [comment]
hi @jpvajda , even after running this command I get the below error

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com stable InRelease: The following signatures were invalid: KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372
W: http://www.openprinting.org/download/printdriver/debian/dists/lsb3.2/Release.gpg: Signature by key F8897B6F00075648E248B7EC24CBF5474CFD1E2F uses weak digest algorithm (SHA1)
W: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/stable/InRelease  The following signatures were invalid: KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372  KEYEXPIRED 1580922760  KEYEXPIRED 1580922781  KEYEXPIRED 1580922760  KEYEXPIRED 1589481372
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/cache/app-info -a -e /usr/bin/appstreamcli; then appstreamcli refresh > /dev/null; fi'
E: Sub-process returned an error code
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Translations (main/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/elastic-6.x.list:1 and /etc/apt/sources.list.d/elastic-6.x.list:2

**Comment by jpvajda** [comment]
@soumarshi ok thanks for trying this and reporting the issue, we'll take a look at what may be occurring here.

**Comment by jpvajda** [comment]
@soumarshi so I was unable to reproduce this on a fresh install of ubuntu 20.04.1 from the US, where are you located?

**Comment by soumarshi** [comment]
> @soumarshi so I was unable to reproduce this on a fresh install of ubuntu 20.04.1 from the US, where are you located?

I did a fresh install of ubuntu 20.04.1 on a colleague's box but it was still unsuccessful. I am located out of India.

**Comment by jpvajda** [comment]
Ok  @soumarshi Let me look into again there may be something going on based on the region you are in.

**Comment by jpvajda** [comment]
@soumarshi This problem seems to be related to the change Google did signing their packages distributed through Linux repositories. I would recommend to fix the missing GPG key by following the instructions in here: https://www.omgubuntu.co.uk/2017/08/fix-google-gpg-key-linux-repository-error
