### ISSUE TITLE
Incorrect file path reference in Automated Tagging guide on Step 3

### ISSUE THREAD

**Issue by sanderblue** [newrelic/developer-website#958]
### Description

While going through the `demo-deployer` "Automated Tagging" guide, I ran into an error on Step 3 "Run the application" due to incorrect paths being referenced in the provided command(s) to copy and paste.

<img width="920" alt="Screen Shot 2020-11-17 at 1 00 02 PM" src="https://user-images.githubusercontent.com/2590905/99435523-d7499180-28d5-11eb-9c72-b2efcf8c2853.png">

When running the provided command below:
```sh
docker run -it -v $HOME/configs/:/mnt/deployer/configs/ --entrypoint ruby deployer main.rb -c configs/{my-config-file}.json -d documentation/tutorial/user_stories/Hello/hello.json
```

This results in the following error:
```
[INFO] Executing Deployment
[|] Parsing and validating Deployment configuration[ERROR] No such file or directory @ rb_sysopen - documentation/tutorial/user_stories/Hello/hello.json
```

It looks like the paths have changed to `demo/catalog/hello.{vendor}.json`, which seems to have worked for me.

### Steps to reproduce

1. Navigate to the Automated Tagging guide: https://developer.newrelic.com/automate-workflows/automated-tagging 
2. Run through the steps to Step 3
3. Run the command that's provided (see screenshot and code block above)
4. See error described above

P.S. `demo-deployer` is pretty darn cool 👏 😎

**Comment by jerelmiller** [comment]
@sanderblue thanks for reporting this! Do you know by chance what the correct command is? Or who best to talk to to get that?

**Comment by sanderblue** [comment]
The command is correct, it just has an incorrect path within it. 

`documentation/tutorial/user_stories/Hello/hello.json` should be `demo/catalog/hello.aws.json` for example. It could also be one of the several other catalog json files. `demo/catalog/hello.gcp.json` is another example :)

**Comment by jerelmiller** [comment]
Ah gotcha! Is there a preferred one of the two? Or maybe we need to list both so AWS or GCP users can use the appropriate one?

**Comment by jpvajda** [comment]
this seems to be currently written just for AWS but if we want to generalize it we could go with `demo/catalog/hello.{vendor}.json`and we can specify that vendor should replaced with the aws, gcp, azure.

**Comment by jpvajda** [comment]
@sanderblue any opinions on generalizing this guide? (see above comment)

**Comment by sanderblue** [comment]
I would probably go with the generic form and specify the need to adjust the `{vendor}` part like @jpvajda mentioned. But honestly, I think it would be just fine to have the whole guide be for AWS because the guide could also mention how to make the small adjustment for the other vendors.

**Comment by jpvajda** [comment]
@sanderblue  I was trying to fix this guide, but it seems the repo a lot of the commands points to has changed, for example the file reference in this command

```
docker run -it\
    -v $HOME/configs/:/mnt/deployer/configs/\
    --entrypoint ruby deployer main.rb -c configs/creds.json -d documentation/tutorial/user_stories/Hello/hello.aws.json

```

seems to now reside here: 

https://github.com/newrelic/demo-deployer/tree/main/demo/catalog

so it seems we need to point all these commands to this location now: 

https://github.com/newrelic/demo-deployer/blob/main/demo/catalog/hello.aws.json

Which I did this PR https://github.com/newrelic/developer-website/pull/973
