### ISSUE TITLE
Write a guide on using charts based on the old dev site Chart library page

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#975]
In the previous version of the developer site we had a lot more specifics around using chart components that aren't really covered in the component documentation, it would be useful to provide a guide on using chart components as that's a common question we receive.

### Tools to get started on this task

1. You'll need access to AEM -Adobe Exp. Manager to view the old [Chart library page](https://author-newrelic-prod2.adobemsbasic.com/sites.html/content/newrelic/developer/build-tools/new-relic-one-applications/chart-library)
2. Compare the old chart page information to the component content and write a guide that better articulates the use of chart components in building a Nr1 App.

**Comment by jpvajda** [comment]
@alexronquillo let me know if this is something you'd be interested in creating.

**Comment by alexronquillo** [comment]
@jpvajda I'm actually almost done with it!

**Comment by jpvajda** [comment]
This is done
